### ISSUE TITLE
Unable to open large images

### ISSUE THREAD

**Issue by imms93** [photopea/photopea#684] opened 2018-04-30 10:24 UTC
As the title says, I'm trying to open a big image I scanned from a book but this is what I get:
![shot](https://user-images.githubusercontent.com/30982542/39423192-0f3ecc84-4c71-11e8-97bb-5f55579430f5.PNG)
This is the image file I'd like to open (unless I resize it in Microsoft Paint first, I can't open it, while on another web-based image editor named Pixlr the file opens without issues even though it's large)
![img20180312_16321911](https://user-images.githubusercontent.com/30982542/39423260-483aa08a-4c71-11e8-9d39-4b64271bf656.png)

**Comment by photopea** [comment] 2018-04-30 10:25
Hi, how big is your image? Can you send it to us to support@photopea.com ? Maybe the problem is not in the file size.

**Comment by imms93** [comment] 2018-04-30 10:43
I've uploaded it here on github :D it's full size

**Comment by photopea** [comment] 2018-04-30 13:01
I was able to open your PNG file in Photopea. Note, that it requires 1.3 GB of free RAM.

Is your WebGL disabled after you open a file (See More - Use WebGL). Can you try to disable it manually before opening a file?

**Comment by imms93** [comment] 2018-04-30 16:09
WebGL was already disabled. I tried activating it before opening the file but it has come out a message saying Disabling WebGL after the file has opened. And now the other document I was working on has disappeared too :(

**Comment by photopea** [comment] 2018-04-30 16:15
WebGL is disabled, when the width or the height of the image is larger, than the size limit of WebGL textures on your device (usually 8192 on desktops and 4096 on phones). But if you have enough free RAM, it should be displayed. Do you see any errors in the web console?

**Comment by imms93** [comment] 2018-05-01 19:30
I'm sorry but I'm kind of a tech illiterate, how do I open the web console?

**Comment by photopea** [comment] 2018-05-01 19:32
you should right-click - Inspect element, switch to console

**Comment by photopea** [comment] 2018-05-25 13:36
It should be fixed now. You steel need quite a lot of RAM.

**Closed by photopea** 2018-05-25 13:36 UTC
