### ISSUE TITLE
Layers get glitched out

### ISSUE THREAD

**Issue by raivologo** [photopea/photopea#4723] opened 2022-06-11 13:14 UTC
Hello!

So, I've been working on a project since a few days (more specifically, a Mortal Kombat stage concept), and it is a complex edit so it has a good amount of layers. The thing is, when I try to work with the lower layers, they disappear and I can't do anything with them, until I scroll up and down for them to reappear. Then I do one thing with a layer and they disappear again, making me repeat this process over and over to work with them.

Is it, like, Photopea struggling to load all the layers at once?

**Comment by photopea** [comment] 2022-06-11 13:35
Could you describe, how can I make this problem happen myself? Maybe save your document as a PSD and send it to me to support@photopea.com . 

Also, does it happen in an updated browser with no extensions? We do not react to problems in old browsers (like Internet Explorer) or browsers with extensions, which modify the content of websites.

**Comment by raivologo** [comment] 2022-06-11 13:52
I use the Photopea app itself, not the browser version. 

Describing it better, when I click on one of the lower layers (the ones that are more below), this happens to them:
![image](https://user-images.githubusercontent.com/87151260/173190756-4eb6bb94-81df-4631-b401-1a284ab9e5a7.png)
So, to fix that, I have to scroll all the way to the top of the layers, then to the bottom, then search the layer I want to work on, then this bug happens again when I click on it.

**Comment by photopea** [comment] 2022-06-11 14:00
But still ... Could you describe, how can I make this problem happen myself? Maybe save your document as a PSD and send it to me to [support@photopea.com](mailto:support@photopea.com) .

**Comment by raivologo** [comment] 2022-06-11 15:47
I'll be sending the PSD to your email just soon; it is quite large in size though, so Gmail will send it as a Google Drive link.

So, to make this problem happen, you simply have to click on one of the lower layers of the PSD.

**Comment by popbee** [comment] 2022-06-11 20:22
NOTE: Installing a web page as an "App" does not stop chrome extensions from being enabled. So make sure you don't have any when reporting a bug.

![image](https://user-images.githubusercontent.com/1083830/173203673-c298aadc-1aa3-43a6-87f5-f5a817ae843c.png)

**Comment by photopea** [comment] 2022-06-12 07:03
It should be fixed now, thanks for reporting it :)

**Closed by photopea** 2022-06-12 07:03 UTC

**Comment by raivologo** [comment] 2022-06-12 17:08
Hello!

I have successfully fixed that problem once disabling my extensions from
Photopea as advised by popbee. So, I've come to thank you for your
assistance! ✌

Em dom., 12 de jun. de 2022 às 04:03, Photopea ***@***.***>
escreveu:

**Comment by raivologo** [comment] 2022-06-12 17:08
Hello!

I have successfully fixed that problem once disabling my extensions from Photopea as advised by popbee. So, I've come to thank you for your assistance! ✌

**Comment by photopea** [comment] 2022-06-12 18:54
Actually, it was not caused by extensions, I have fixed the bug today :) I think you can keep using your extensions if you need them.
