### ISSUE TITLE
photopea freezing and affecting other tabs

### ISSUE THREAD

**Issue by JustTryingToDraw** [photopea/photopea#1643] opened 2019-08-30 17:04 UTC
By trying to utilize Photopea online, the program has been freezing up more frequently with each use, and has also been affecting other Chrome tabs I have open (i.e. Youtube, etc.) and the Ads in Photopea have been taking longer to cycle through also, which is causing the program to freeze.

**Comment by photopea** [comment] 2019-08-30 17:24
Hi, it is really strange. The slowness of one tab should not influence the speed of another tab. Can you update your browser? Can you try to disable WebGL? More - Use WebGL.

**Comment by calclover2514** [comment] 2019-09-01 01:25
This is entirely a Chrome issue, and will be impossible for anyone but Google to fix.

**Comment by photopea** [comment] 2019-09-01 08:19
I can ask Google developers to fix it, they usually fix problems quite quickly, when I describe it to them in an email.

But first, I need to reproduce the problem somehow (so that I am sure there is something to be fixed).

**Comment by photopea** [comment] 2019-09-03 13:58
I have to close it because of lack of details.

**Closed by photopea** 2019-09-03 13:58 UTC
