### ISSUE TITLE
Projects Opening Automatically

### ISSUE THREAD

**Issue by Machroma1** [photopea/photopea#6652] opened 2024-04-14 13:14 UTC
Win10 / Ryzen 7 2700, RX 570 8GB, 16GB DDR4 2666, 1TB HDD (secondary), 1TB SSD (primary)
Google Chrome Ver: 123.0.6312.107
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. Projects open automatically, projects have been stacking up (around 7-8 .psd files are opening automatically now). Good feature for auto-saving but when I am wanting to just create a new project from dashboard, i have to close these tabs everytime as they keep coming back. Sure I can click new then a new project but all these psd files that are on the website slow down the performance of the website itself for me.

https://github.com/photopea/photopea/assets/167003921/aa976f80-cfa4-44ab-a322-2e14e46d83c4

**Comment by Machroma1** [comment] 2024-04-14 13:18
And its also really annoying to close these tabs "Are you sure you want to close this project" every time

**Comment by photopea** [comment] 2024-04-14 20:14
This problem is caused by your browser extensions, see https://www.photopea.com/tuts/photopea-opens-up-old-files/

**Comment by photopea** [comment] 2024-04-28 12:50
I have to close it because the person did not respond.

**Closed by photopea** 2024-04-28 12:50 UTC
