### ISSUE TITLE
Color replacement tool Not replacing color

### ISSUE THREAD

**Issue by Web-mainiac** [photopea/photopea#4302] opened 2022-02-06 08:36 UTC
I use this tool a lot and it always works for me, just pick a color and replace. Simple, except now it isnt doing that but instead giving off this black and white POS and i hate it, tried changing the blend and no dice
Help

**Comment by photopea** [comment] 2022-02-06 13:11
Hi, I just tried it and it works great for me.

Could you show us a screenshot or a video of what is happening in your case?

**Comment by Web-mainiac** [comment] 2022-02-10 02:49
> Hi, I just tried it and it works great for me.
> 
> Could you show us a screenshot or a video of what is happening in your case?

No because its some private stuff I have going on but no matter the color or blend mode except luminosity which makes it green. But it just does this Black and white stuff no matter my choice. No matter the color or blend except luminosity, it just gets Black and white stuff on it.

**Comment by photopea** [comment] 2022-02-10 09:06
Could you show us a screenshot of what is happening in your case, but do not use your "private stuff", but some image from the internet instead?

**Comment by photopea** [comment] 2022-02-21 16:02
I have to close it because of lack of details :(

**Closed by photopea** 2022-02-21 16:02 UTC

**Comment by Web-mainiac** [comment] 2022-02-21 17:51
> I have to close it because of lack of details :(

Ive litterally described the problem in every detail possible.

**Comment by photopea** [comment] 2022-02-21 19:39
I still can not reproduce what you describe. And I think I do not fully understand what you describe.

Could you show us a screenshot of what is happening in your case, but do not use your "private stuff", but some image from the internet instead?
