### ISSUE TITLE
When trying to do 'color overlay', the error message SBOX_FATAL_MEMORY_EXCEEDED appears

### ISSUE THREAD

**Issue by NicolasNolmans** [photopea/photopea#5102] opened 2022-11-07 09:45 UTC
![image](https://user-images.githubusercontent.com/26227686/200278867-44fc0169-45a1-493f-b920-70e099afef86.png)

**Comment by photopea** [comment] 2022-11-07 10:09
What should I do after opening www.Photopea.com to see such error?

**Comment by NicolasNolmans** [comment] 2022-11-07 10:20
You should open an JPG image, and then double click on the 'background' layer, and click on 'color overlay'. When this is done click on the black color box after the percentage. 
![image](https://user-images.githubusercontent.com/26227686/200286215-2e2d2d08-93ee-4d01-887e-a7b947bf14e8.png)

**Comment by photopea** [comment] 2022-11-07 11:02
I just tried and it seems to work fine. Did you try to do it with a different JPG image, e.g. a smaller one?

**Comment by NicolasNolmans** [comment] 2022-11-07 12:02
A smaller one will not do. I need to use this JPG.

**Comment by photopea** [comment] 2022-11-07 12:14
The problem is not in Photopea, it is in your computer. Photopea works fine for millions of people.

If you want me to help you find out what is wrong with your computer, you should cooperate with me, to rule out possible reasons of your problem.

**Comment by photopea** [comment] 2022-11-07 12:16
First, let me know if it still happens when you disable all your browser extensions. In 95% of cases, similar problems are caused by an extension, which decided to break Photopea.

**Comment by NicolasNolmans** [comment] 2022-11-07 13:30
I've done it and the issue is still there.

**Comment by photopea** [comment] 2022-11-07 13:41
Could you try a different JPG file? Which is under 200 kB

**Comment by photopea** [comment] 2022-11-07 14:28
So how large is your old JPG file in terms of pixels? Are you doing it on a PC or a phone?

**Comment by NicolasNolmans** [comment] 2022-11-07 14:41
It is 22677 x 12756, and I'm using a pc

**Comment by photopea** [comment] 2022-11-07 15:18
That is 289 million pixels, you would need like 16 GB of free RAM for this. Do you have that much RAM? Also, could you try it in Firefox?

**Comment by photopea** [comment] 2022-11-15 14:27
I have to close it because of lack of details.

Keep in mind, that every pixel needs four bytes of RAM, so do not use too many pixels when your RAM is small.

**Closed by photopea** 2022-11-15 14:27 UTC
