### ISSUE TITLE
Magic Replace Not Working

### ISSUE THREAD

**Issue by apicazo98** [photopea/photopea#6302] opened 2024-01-09 01:11 UTC
Your Operating System: IOS 13.5.2
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Does not remove or change the things I want on images, small circles as large things, it just does not do anything, it gives message "processing" and stays forever

**Comment by camoody1** [comment] 2024-01-09 01:31
Other people on the Dezgo Discord are also saying that API requests are not being processed. I have sent Discord messages to both Will and Clem, but they are currentlly offline. I assume they're asleep since it's the middle of the night in France.

**Comment by apicazo98** [comment] 2024-01-09 01:38
Thanks for letting me know! You are the best

**Comment by photopea** [comment] 2024-01-09 01:58
Yes, it seems like the problem is at Dezgo. We must wait for them to fix it.

It stopped working at the Europes midnight - 00:00:00. It is 2:57 AM now, so I am going back to bed.

**Comment by camoody1** [comment] 2024-01-09 07:10
Dezgo has their systems back up and running, now. Photopea is able to process AI calls, again.

Here is the response I received from Will at Dezgo.
![image](https://github.com/photopea/photopea/assets/73725653/0a0a2f75-dc0a-4b6a-b972-84f1d94e6764)

Looks like he got it back up and running around 1:30AM my time, or 7:30AM Paris, France time. So, it may have been down for close to 8 hours. Bad timing for the outage to start.

**Comment by camoody1** [comment] 2024-01-09 07:39
More information from Will on the Discord server:
![image](https://github.com/photopea/photopea/assets/73725653/d29a1122-13b8-4230-a77d-b98e4611e737)

**Comment by photopea** [comment] 2024-01-09 08:24
It seems to be fixed now, so I will close this now.

**Closed by photopea** 2024-01-09 08:24 UTC
