### ISSUE TITLE
Random pixel and frame distortion

### ISSUE THREAD

**Issue by TurkeyJoke** [photopea/photopea#2005] opened 2020-03-22 19:44 UTC
When trying to edit text on a canvas, it all of a sudden looks like it dramatically zoomed in to where each pixel is clearly seen. I cannot zoom in or out, use the hand tool to reposition it. select any other layers to edit, or revert back to any prior action in History.

![Screenshot at 2020-03-22 14:39:40](https://user-images.githubusercontent.com/62519057/77258885-910b3800-6c4b-11ea-9efc-166151daf5ca.jpg)

**Comment by photopea** [comment] 2020-03-22 19:50
Hi, can you help us reproduce this problem? E.g. send us a PSD and tell us, which text layer should we enter?

Also, did you see a message about any font being loaded? Photopea tries to load font files (.OTF) from our server, when you try to edit a text.

**Comment by photopea** [comment] 2020-03-30 13:33
I have to close it because of lack of details.

**Closed by photopea** 2020-03-30 13:33 UTC
