### ISSUE TITLE
File Getting Corrupted

### ISSUE THREAD

**Issue by StrizerX** [photopea/photopea#6175] opened 2023-11-16 10:51 UTC
I have been having this issue where whenever I delete, or edit one part/layer of a .eps or .svg file, the whole image breaks such as random empty spots and holes, objects disappearing, etc. Even when I undo it, the deleted part comes back but the broken parts remain. I have tried with multiple files, and all are having the same problem. Even when I export, it is like that. I have attached an image that shows what is happening. Thank you and please get back to me ASAP.
![bug](https://github.com/photopea/photopea/assets/119974202/98b5f65a-ead9-48a4-acff-853c0b63e827)

**Comment by photopea** [comment] 2023-11-16 12:27
What should I do to see this problem myself? I have opened www.photopea.com , what should I do next?

**Comment by StrizerX** [comment] 2023-11-19 07:38
> What should I do to see this problem myself? I have opened [www.photopea.com](http://www.photopea.com) , what should I do next?

upload the .eps file, then remove any one layer. you will see other layers getting distorted like shown in image, even after pressing CTRL + Z

**Comment by photopea** [comment] 2023-11-19 11:24
I just did it, but I can not see any strange behaviour as in your screenshot. Could you maybe send us your EPS file to support@photopea.com ?

**Comment by photopea** [comment] 2023-11-19 11:24
Also, could you make sure that it happens even after you disable all your browser extensions? Maybe it is caused by your browser extensions.

**Comment by photopea** [comment] 2023-11-27 22:50
I have to close it because of lack of details.

**Closed by photopea** 2023-11-27 22:50 UTC
