### ISSUE TITLE
 The color of the same element will deviate, and the saturation and brightness will decrease in photopea.

### ISSUE THREAD

**Issue by isme856** [photopea/photopea#4905] opened 2022-08-11 10:23 UTC
The first picture belongs to illustrator, and the second picture is photopea.
The color of the same element will deviate, and the saturation and brightness will decrease in photopea.

Thank you very much ^_^

![image](https://user-images.githubusercontent.com/111053988/184113218-2c6bae36-c7fc-4ac7-978a-3d93e02cf8c5.png)
![image](https://user-images.githubusercontent.com/111053988/184113260-7586710b-f152-4e28-926b-94326699725d.png)

**Comment by photopea** [comment] 2022-08-18 22:24
Hi, could you share your AI file with us? Also, if you can delete all layers and leave just one, on which the problem is visible, it would be nice.

**Comment by photopea** [comment] 2022-08-21 13:06
I have to close it because of lack of details :(

**Closed by photopea** 2022-08-21 13:06 UTC
