### ISSUE TITLE
When importing my pixel art then clicking anything, the image turns into a blocky mess of pixels

### ISSUE THREAD

**Issue by FartMaster57** [photopea/photopea#3501] opened 2021-07-05 23:13 UTC
I'm trying to edit pixel art and when importing one of my layers it was fine and then it turned into like 5 pixels when I did anything

Right after importing the image: 
![image](https://user-images.githubusercontent.com/58342249/124523295-7ae3a580-ddc4-11eb-8c73-a23288f2c055.png)
After rotating the image or moving it: 
![image](https://user-images.githubusercontent.com/58342249/124523332-a9618080-ddc4-11eb-8204-8f27f6043bd8.png)
This seems to be temporary as when you click the check mark it applies it like nothing happened, but I swear it was permanent just a few minutes ago so I don't know what's going on. Also I'm using nearest-neighbor.

**Comment by FartMaster57** [comment] 2021-07-05 23:16
Actually yes, it is permanent. But more so semi-permanent. Sometimes I'll import it and it will break if I try to select part of it, and I can't revert it. But then other times I'll import it and then nothing will be wrong with it

**Comment by photopea** [comment] 2021-07-05 23:23
Could you describe some steps, how can I reproduce the issue? Maybe share your image with us?

**Comment by photopea** [comment] 2021-07-05 23:24
Are you talking about the Free Transform tool? Do you know what a Free Transform tool is?

**Comment by FartMaster57** [comment] 2021-07-05 23:25
![BallisticLeftArms](https://user-images.githubusercontent.com/58342249/124523821-a2d40880-ddc6-11eb-80d2-ce3e7137e618.png)
This is the exact image I'm experiencing trouble with, I am using the free transform tool. It does not just happen when using that though, it also happens when clicking any other tools or trying to edit the layer. Basically just deselecting it breaks it.

**Comment by FartMaster57** [comment] 2021-07-05 23:26
I'm not sure how you would go about recreating this

**Comment by FartMaster57** [comment] 2021-07-05 23:54
My only guess is that is happens due to the amount of layers I have on my project. I'm making a spritesheet and there's probably like 100 layers at this point

**Comment by photopea** [comment] 2021-07-06 07:40
I opened your file in Photopea and zoomed in. This is what I see. I applied the rotation and got what you see on the right. Do you consider this result to be correct? Or you expected to see something else?

![image](https://user-images.githubusercontent.com/15955558/124561460-34329180-de3e-11eb-935d-290eb598b650.png)

**Comment by FartMaster57** [comment] 2021-07-06 20:03
That is not the same result. That is just what happens when you rotate it with bilinear. I was rotating using nearest-neighbor

**Comment by photopea** [comment] 2021-07-06 20:37
How exactly did you create this imag? 

![image](https://user-images.githubusercontent.com/58342249/124523332-a9618080-ddc4-11eb-8204-8f27f6043bd8.png)

I need to reproduce it to be able to fix it.

**Comment by FartMaster57** [comment] 2021-07-07 02:42
I created it by rotating the image in photopea. It also happens when clicking anything. It gets fixed if you do CTRL + Z after it breaks

**Comment by photopea** [comment] 2021-07-07 06:40
Are you able to do it again? Does it happen every time? I was not able to reproduce it.

**Comment by FartMaster57** [comment] 2021-07-08 21:35
I was able to recreate it here. I seriously have no idea what is causing it, I opened a new project and imported the same image and it didn't happen again.
https://user-images.githubusercontent.com/58342249/124993674-afe53780-e012-11eb-9110-9cfb20e10aca.mp4

**Comment by photopea** [comment] 2021-07-08 21:45
You are pasting a new layer in your video as a smart object. Are you aware of it?

**Comment by FartMaster57** [comment] 2021-07-08 21:52
No I don't know what that means. I was importing it from file explorer you just can't see it.

**Comment by photopea** [comment] 2021-07-08 22:02
Did you use File - Open and Place? I still don't understand what is wrong in your video and what you actually do in it.

**Comment by FartMaster57** [comment] 2021-07-08 22:38
When I click the zoom in button, the image becomes all pixelated. In the video example I wasn't even trying to import pixel art, it was just art. When you see it changing that's me doing Ctrl + Z and then Ctrl + Shift + Z.

**Comment by FartMaster57** [comment] 2021-07-08 22:38
Also no, I did not use Open and place, I simply dragged the image from file explorer into photophea

**Comment by photopea** [comment] 2021-07-08 22:45
I will close it now.

Please, file a new issue. Attach all files, which are needed for reproducing the problem, and describe precisely the steps, that are needed to reproduce the problem. And make sure, that whenever you follow the steps, the problem happens every time.

**Closed by photopea** 2021-07-08 22:45 UTC

**Comment by photopea** [comment] 2021-07-08 23:16
Also, try if it happens in a browser with no browser extensions (e.g. in Incognito mode).
