### ISSUE TITLE
PhotoPea Text

### ISSUE THREAD

**Issue by jaynalei** [photopea/photopea#2867] opened 2021-02-14 07:13 UTC
I’m trying to enter text into the text box, but nothing shows up in the box

**Comment by photopea** [comment] 2021-02-14 07:49
Have you tried this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by jaynalei** [comment] 2021-02-14 08:02
> Have you tried this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

Have tried all of the above that I can do in iPad

**Comment by photopea** [comment] 2021-02-14 08:10
Can you access our fonts directly at http://photopea.com/rsrc/fonts/fs/DejaVuSans.otf ? Are you using Photopea at www.Photopea.com ?

**Comment by jaynalei** [comment] 2021-02-14 09:08
Yes I am, any default font doesn’t show up

**Comment by photopea** [comment] 2021-02-14 10:00
do you have any browser extensions? Could you show me a proof that you don't have any extension? I am not very familiar with iPads.

**Comment by jaynalei** [comment] 2021-02-14 10:10
How do I show proof, I don’t know how to check ?

**Comment by photopea** [comment] 2021-02-14 10:14
Could you connect to a different wifi? E.g. enable a wifi hotspot on your phone? Does it work then?

**Comment by jaynalei** [comment] 2021-02-14 10:19
It still doesn’t work

**Comment by photopea** [comment] 2021-02-14 10:31
I still believe that the problem is not in Photopea, but in your device. Can you look into the settings of your Safari and change something?

Also, try to ask here, maybe there will be some users who use iPads: https://www.reddit.com/r/photopea

**Comment by photopea** [comment] 2021-02-17 08:37
You need at least Safari 11 (released in September 2017) to be able to use the Type tool. What version of Safari do you have? Can you update it? I believe Safari can be updated by updating iOS.

**Comment by photopea** [comment] 2021-02-25 15:41
I have to close it because of lack of details.

**Closed by photopea** 2021-02-25 15:41 UTC
