### ISSUE TITLE
Vanishing Point problems

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#5168] opened 2022-12-09 12:23 UTC
1) When creating new plane and I click to make corners in counterclockwise direction (first top corner, second bottom left, third bottom right) it refuses to make fourth corner and only creates red triangle with blue point in top left position of entire image - see screenshot
![image](https://user-images.githubusercontent.com/6370548/206700777-cae65a8a-2041-4f32-8831-e6f4ba853b8a.png)
2) When I click on Hand, Zoom In or Zoom Out tool icon it generates this error in console for some reason but works correctly afterwards it seems. 
![image](https://user-images.githubusercontent.com/6370548/206701028-10f51fa0-e9b0-4def-8fe6-649fdb559715.png)

**Comment by bluep55** [comment] 2022-12-09 13:41
Same for me. No problem clockwise, but counter clockwise it just creates a red triangle.

**Comment by photopea** [comment] 2022-12-14 15:48
Thanks for reporting, both problems should be fixed now!

There was one more problem. When you save the document with vanishing planes as a PSD, and then, open it again, adjacent planes are not adjacent to each other anymore. But it happened just once, I could not reproduce it again. @hxim maybe you can?

**Closed by photopea** 2022-12-14 15:48 UTC
