### ISSUE TITLE
I can't view mouse pointer in white background

### ISSUE THREAD

**Issue by anibalardid** [photopea/photopea#1007] opened 2018-10-22 18:58 UTC
When I use brush tool (ubuntu 16.04, with chrome latest version), In white background, I didn't see the brush pointer ... In black background yes .

regards !

**Comment by photopea** [comment] 2018-10-22 19:11
Hi, the brush cursor is usually a black circle with a white glow around it. Can you send us a screenshot of how your cursor looks like on a black background? Does it have a white glow around it?

**Comment by anibalardid** [comment] 2018-10-22 19:17
I recorded a video :)

https://drive.google.com/file/d/1ri7SWKuacmykD-6TdpqJf49LbJpQk0Nq/view?usp=drivesdk

**Comment by photopea** [comment] 2018-10-22 19:41
I don't have rights to watch your video :(

**Comment by anibalardid** [comment] 2018-10-22 19:43
now ? 
https://drive.google.com/file/d/1ri7SWKuacmykD-6TdpqJf49LbJpQk0Nq/view?usp=sharing

**Comment by photopea** [comment] 2018-10-22 19:49
You said, that the cursor does not work on a white background, but I can not see it at all in your video :(

Are you sure you can see it on on black background? Can you see custom cursors on this website? http://www.ivank.net/veci/cursors.html

**Comment by anibalardid** [comment] 2018-10-22 19:56
yeah, thats how i see ... but in black background I saw white cursor.

I change background painting it and it works ... with red backgorund too...

Maybe in white background the "glow" of cursor doesnt work very well, maybe linux+chrome ... 

In http://www.ivank.net/veci/cursors.html
I saw cursor like magic wand in 32x32, 64x64 and 128x128 ... but in 256x256 and 512x512 I only saw the normal cursor pointer.

**Comment by photopea** [comment] 2018-10-22 20:02
When you have a cursor on a red background, there should be a black circle with white glow ... maybe you see transparent circle instead of a black circle (you have to look really close)?

Could you try to update your system (ubuntu, drivers etc...) ?

**Comment by anibalardid** [comment] 2018-10-22 20:10
My fault ... in red is same that white backgound ... now in white background I saw it ... but very very very light ... very different than firefox.

I'm executing now apt update && apt upgrade ;)

**Comment by anibalardid** [comment] 2018-10-22 20:36
I recorded new video ... BUT ... I don't see like the video hahaha, I saw the cursor more lighter, similar to transparent :(

https://drive.google.com/open?id=1xms1Cm7Dhpjo-8uMAiKY-SxmGZAPWc-g

**Comment by anibalardid** [comment] 2018-10-22 20:37
latest chrome stable in ubuntu repo is this 65 ... with this source:
deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main

**Comment by photopea** [comment] 2018-10-22 20:54
I am pretty sure it is a bug in a browser. But it is a bit hard for me to report it, when I can not reproduce it myself :(

**Comment by photopea** [comment] 2018-10-22 20:56
Also, they will not try to solve a bug in an old version, because it could be already fixed in a new version. Chrome 65 is like a year old.

**Comment by anibalardid** [comment] 2018-10-22 21:08
In chromium works perfect ... i will check why ubuntu doesn't update to the latest version of chrome

**Comment by photopea** [comment] 2018-10-22 21:33
Ok, I will close it for now.

**Closed by photopea** 2018-10-22 21:33 UTC

**Comment by anibalardid** [comment] 2018-10-22 23:48
I updated chrome to v70 and it works perfect now ;)

best regards at all !!!
