### ISSUE TITLE
Error exportar PDF Vector

### ISSUE THREAD

**Issue by JordiD111** [photopea/photopea#4247] opened 2022-01-18 07:44 UTC
buenos días,

desde ayer día 17/1/2022 al dar en archivo/exportar como/ PDF, Photopea no exporta PDF Vectorizados como si hacia hasta ahora. solo saca PDF's rasterizados.

por favor corregir

**Comment by photopea** [comment] 2022-01-18 09:07
Hi, can you send me a PSD file, which can not be exported to a vectorized PDF, to support@photopea.com ?

**Comment by matteo05vava** [comment] 2022-01-18 10:19
Hi, i can confirm that there is a bug in vectorized pdf exporting.
I've noticed that if i deactivate the levels that contains paths originally from an svg everything works correctly.

Here you can see that ext.js generate an uncaught error.
![Schermata 2022-01-18 alle 11 17 28](https://user-images.githubusercontent.com/23584085/149918125-8b15862a-d790-4777-b23b-b3ea817c9190.png)

**Comment by photopea** [comment] 2022-01-18 10:27
I still can not make the bug happen, exporting a PDF always works for me :( Could you please share a PSD, which can not be exported to PDF?

**Comment by photopea** [comment] 2022-01-18 10:36
I see the bug now, I am working on a fix.

**Comment by photopea** [comment] 2022-01-18 10:53
It should be fixed now. I am very sorry for this.

**Closed by photopea** 2022-01-18 10:53 UTC
