### ISSUE TITLE
Crashing-Lag-Not Loading

### ISSUE THREAD

**Issue by lxryn** [photopea/photopea#5607] opened 2023-05-07 21:54 UTC
I was having problems with it a couple days ago, didn't think nothing of it. But now it's gotten worse. It won't open at all and when it does, it shows as if I need to log in and when I do. Nothing changes. Beyond frustrating

**Comment by photopea** [comment] 2023-05-07 22:23
Are you using Photopea at www.Photopea.com ? What should I do after opening www.Photopea.com to see what you see? 

What is " it shows as if I need to log in"? Could you show us a screenshot of how it looks?

**Comment by lxryn** [comment] 2023-05-09 01:05
<img width="1280" alt="Screenshot 2023-05-08 at 8 04 53 PM" src="https://user-images.githubusercontent.com/132114446/236968260-30bb24db-2c38-4a04-afc2-089761885b0c.png">

now it just does this

**Comment by photopea** [comment] 2023-05-09 09:08
So you can not open www.Photopea.com at all? Can you try it in the incognito mode?

**Comment by photopea** [comment] 2023-05-09 09:09
Try these steps: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by lxryn** [comment] 2023-05-09 15:36
<img width="494" alt="Screenshot 2023-05-09 at 10 34 04 AM" src="https://github.com/photopea/photopea/assets/132114446/0aac4126-fa74-4d41-abf5-7b0b8361aa86">
<img width="274" alt="Screenshot 2023-05-09 at 10 34 37 AM" src="https://github.com/photopea/photopea/assets/132114446/8608a530-90e0-4456-8876-298a5c1bbdc3">

maybe I'm not understanding something - could be my internet?

**Comment by lxryn** [comment] 2023-05-09 15:37
> So you can not open [www.Photopea.com](http://www.Photopea.com) at all? Can you try it in the incognito mode?

not at all

**Comment by photopea** [comment] 2023-05-09 16:25
So did you try it in the incognito mode or not? What were the results?

**Comment by lxryn** [comment] 2023-05-09 16:28
> So did you try it in the incognito mode or not? What were the results?

yes, I did. did not work, the same results.

**Comment by photopea** [comment] 2023-05-09 17:04
I think you have problems with the internet connection. Can you open e.g. www.Google.com ?

**Comment by lxryn** [comment] 2023-05-11 05:35
Not a he. And I honestly gave up. Idk what’s going on. I’m at a different location. Stronger internet  and it still does the same. I. Give. Up. If you don’t know what’s going on. Then I surely don’t. On May 10, 2023, at 9:04 AM, 97Buckeye ***@***.***> wrote:﻿

I think you have problems with the internet connection. Can you open e.g. www.Google.com ?

Well, we know he can open GitHub.com. 🤷🏽‍♂️

**Comment by photopea** [comment] 2023-05-11 06:58
Could you record a short video of opening a new Incognito browser window (Chrome, Edge or Firefox, ad I dont know if Safari has Incognito) and typing www.Photopea.com, and what happens next?

**Comment by photopea** [comment] 2023-05-11 20:43
I have to close it. We have hunrdeds of thousands of users using Photopea in Safari on Mac, and nobody reported a problem. I think the problem is with your computer, but it is hard for us to fix it from a distance.

**Closed by photopea** 2023-05-11 20:43 UTC

**Comment by lxryn** [comment] 2023-05-12 06:10
👍🏻Sent from my iPhoneOn May 11, 2023, at 3:43 PM, Photopea ***@***.***> wrote:﻿
I have to close it. We have hunrdeds of thousands of users using Photopea in Safari on Mac, and nobody reported a problem. I think the problem is with your computer, but it is hard for us to fix it from a distance.
