### ISSUE TITLE
Save for Web freezed

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2048] opened 2020-04-17 19:32 UTC
1. Reload photopea and open "milk.sketch"
2. In menu I selected File-Export as-More-RAW
3. In Format dropdown I change to PNG
4. In Format dropdown I change back to RAW
5. In Format dropdown I change to SVG
6. In Format dropdown I try to change to PNG
7. Photopea freeze for long time before switching to PNG (around 30 seconds  on my computer) and every time I try to export this file to PNG after that.
(happens to me only in Google Chrome browser not in Mozilla Firefox, and also if I go in different order it seems to work fine)
![obrazek](https://user-images.githubusercontent.com/6370548/79605802-d9096780-80f0-11ea-8777-080126626b12.png)

**Comment by photopea** [comment] 2020-04-19 22:39
Hi, I can not reproduce it. Can you still reproduce it? Can you update your browser?

**Comment by hxim** [comment] 2020-04-20 04:42
@photopea 
Yes I can still reproduce it. Here I recorded short video what it does on my computer:
https://youtu.be/4bSiMJlfLB8

My browser is updated:
```
Google Chrome je aktuální
Verze 81.0.4044.113 (Oficiální sestavení) (64bitový)
```

**Comment by photopea** [comment] 2020-04-20 07:22
That is so weird. I still can not reproduce it, I tried it multiple times.

PNG encoding and decoding is done with our custom JS, which should not depend on HW acceleration. But I found out, that the latest Chrome might slow down a part of code depending on a completely different part of code https://bugs.chromium.org/p/chromium/issues/detail?id=1065717

Can you confirm, that it does not happen in Firefox for you?

**Comment by hxim** [comment] 2020-04-20 07:34
I confirm it does not happen in Firefox.
But there was another isssue when I tried in firefox see #2059

**Comment by photopea** [comment] 2020-04-20 22:22
Can you try choosing the PNG option directly, but move the Quality slider? Does it get stuck too?

**Comment by hxim** [comment] 2020-04-21 05:18
> Can you try choosing the PNG option directly, but move the Quality slider? Does it get stuck too?

Hello I just tried repeating steps from first message/video and it now works fine (no freeze). Did you fixed something?
Also tried PNG directly and moving Quality slider and there is no freeze.

**Comment by photopea** [comment] 2020-04-21 07:21
I did not change the part related to saving images. Does it depend on whether your laptop is charging / discharging?

**Comment by hxim** [comment] 2020-04-21 08:48
> Does it depend on whether your laptop is charging / discharging?

This is desktop computer I do not have any laptop :)

**Comment by photopea** [comment] 2020-04-21 13:25
I will close it now. Let me know if it happens again. Also, I am more and more skeptical about the performance of V8 because of your report and this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1065717

**Closed by photopea** 2020-04-21 13:25 UTC
