### ISSUE TITLE
Work in template/canvas disappearing

### ISSUE THREAD

**Issue by wasdwasdwasd121** [photopea/photopea#6479] opened 2024-03-04 00:52 UTC
OKAY. this has happened WAY TOO MANY TIMES. i am trying to do my graphic designing and MAKE MY MONEY and DO MY ORDERS, but photopea keeps erasing ALL. OF. MY. WORK.

this happens everytime i'm trying to change the color of a brush and i can't confirm or exit the ui, and then it glitches and whenever i click the screen my work disappears and it just shows a blank transparent canvas. i have restarted my pc, i waited a few days too, i closed photopea and re-opened it, i've tried using the app and the web version, and so much more.

don't close this ticket because "lack of detail :(" or "discussed elsewhere"...I NEED ANSWERS and i need to finish my orders!!

BTW, i've tried saving it as a PSD before it glitches and it's stuck on "saving..." then it all disappears and it never saves. FIX THIS. i have the latest version as i just re-downloaded it a few days ago.

**Comment by photopea** [comment] 2024-03-04 08:57
" i have the latest version as i just re-downloaded it a few days ago." - what does it mean? What did you re-download?

**Comment by Pt-home** [comment] 2024-03-04 13:52
It’s strange that when asking for help with a problem, you don’t specify it... What browser is yours? What is your operating system? What does it show? Are there any add-ons in your browser that may conflict? If this is repeated many times, is it possible to record a video of the error process or describe in detail, and not with emotions, the algorithm for its occurrence? Hundreds of thousands of people are now successfully working and fulfilling orders even on Photopea - which means statistics say that the cause of the problem lies in a combination of factors with which you were unlucky

**Comment by photopea** [comment] 2024-03-08 17:42
I have to close it, because nobody replied in four days :(

**Closed by photopea** 2024-03-08 17:42 UTC
