### ISSUE TITLE
Dithering suggestions

### ISSUE THREAD

**Issue by jayneogithub** [photopea/photopea#3627] opened 2021-07-30 09:52 UTC
### Adding more dithering features.

Hey there! I would like to have **more dithering features.**, here's what i want:

-  Add either a **RGB 8x8x8 palette** or a **custom palette option**

![RGB 8x8x8 in context menu](https://user-images.githubusercontent.com/77931550/127630280-5d51399b-697e-4b83-95b5-d4555130ea43.png)

Here's how I imagine the **8x8x8 palette** in action:

![iWhat it would look like in action](https://user-images.githubusercontent.com/77931550/127630714-d0cf4cf6-3d4b-45f6-a8a9-176ea7b96f15.png)

_Note: I can't think of a concept for the custom palette option._

- Add **more options to dithering**

1. **Photopea** (default)
2. **Steinberg**
3. **Positional**

Here's how they look like:

![Photopea Default](https://user-images.githubusercontent.com/77931550/127634982-bcadbdc9-b3d6-4c21-bee9-788d76b37529.png)
![Steinberg](https://user-images.githubusercontent.com/77931550/127635464-abe0e46b-ed67-45c8-9eda-df3be202d3bd.png)
![Positional](https://user-images.githubusercontent.com/77931550/127635731-4aabc5e8-cadc-4421-acef-0beddda856b1.png)

I hope you would like my suggestions and put them to the website/app!

-Jeremy Andrew

**Comment by jayneogithub** [comment] 2021-07-30 12:57
**Also, I would like you to fix the aliasing of text.**

- Photopea:
![image](https://user-images.githubusercontent.com/77931550/127656173-33f646af-cf7e-4c42-9b3d-3baaed1cca0a.png)
- GIMP:
![image](https://user-images.githubusercontent.com/77931550/127656049-4f418475-cfc7-444a-b313-e002e748560e.png)

The aliasing of Photopea seems kind of "janky", I should say.

**Comment by photopea** [comment] 2021-07-30 16:09
The Dithering in Photopea uses the Steinberg algorithm. I think it is the best algorithm, there is no need for any other.

What is a 8x8x8 palette?

How would you provide a custom palette? Should we expect the user to enter e.g. 100 colors manually?

Text Aliasing - how can I reproduce such problem?

**Comment by jayneogithub** [comment] 2021-07-30 18:20
@photopea Here's my response:

Q: The Dithering in Photopea uses the Steinberg algorithm. I think it is the best algorithm, there is no need for any other.
**A: I think I can agree with you there. The Steinberg algorithm is the best for dithering in my opinion.**

Q: What is a 8x8x8 palette?
**A: By a 8x8x8 palette, I mean a 256 dithering color lookup. Here's what it looks like:**

![image](https://user-images.githubusercontent.com/77931550/127693304-04dd0e8b-69f9-4fea-9e90-875d857e5d5c.png)
Here's what I mean: https://en.wikipedia.org/wiki/8-bit_color

Q: How would you provide a custom palette? Should we expect the user to enter e.g. 100 colors manually as RGB values?
**A: I _still_ can't think of a concept for the custom palette option. However, I know what you mean. Here's what I thought of when I saw your reply. I would rather set the limit to 24-bit, which is true color.** 

![image](https://user-images.githubusercontent.com/77931550/127694289-bd64fc6b-b239-49e1-a2d2-06e0cddf460b.png)

Q: Text Aliasing - how can I reproduce such problem?
A: I think it's about font hinting and rasterization. Here's what I found:
https://en.wikipedia.org/wiki/Font_hinting
https://en.wikipedia.org/wiki/Font_rasterization

**Comment by photopea** [comment] 2021-08-02 11:46
The palette, which you show, is called "8x8x4" in Photopea, because there are 8 possible values for red (3 bits), 8 for green (3 bits) and 4 for blue (2 bits). You can not just come up with random names like "8x8x8" for things :D

If you want to convert your image into a good palette of N colors in Photopea, you can use Image - Reduce Colors.

I wanted to know, what should I do to see a "problem" in Photopea. The text always looked well in Photopea for me.

**Comment by photopea** [comment] 2021-08-02 13:21
I will close it now, as the palette is already in Photopea, and the text problem should be properly described in a separate issue.

**Closed by photopea** 2021-08-02 13:21 UTC
