### ISSUE TITLE
Rasterize Layer Error

### ISSUE THREAD

**Issue by felipeballesteros** [photopea/photopea#1892] opened 2020-01-12 13:37 UTC
When doing File > Export As > PDF
there is a dialog window that provides some options to save the file, when I selected 'Rasterize text', the text layers sometimes will not display properly, in my case some text field was being overwritten with another

**Comment by photopea** [comment] 2020-01-12 22:50
Hi, I have never seen such issue, and I can not reproduce it with any files that I have.

Could you send us your document, for which it happens, to support@photopea.com ?

**Comment by felipeballesteros** [comment] 2020-01-14 12:31
I will try to replicate and send something soon. Thanks!!

**Comment by photopea** [comment] 2020-01-19 23:05
I have to close it because of lack of details :/

**Closed by photopea** 2020-01-19 23:05 UTC
