### ISSUE TITLE
corrupted saving producing 0 byte psd file

### ISSUE THREAD

**Issue by DragonLemonade** [photopea/photopea#4222] opened 2022-01-09 00:36 UTC
the issue:

![window snip for support](https://user-images.githubusercontent.com/97369043/148664517-f40a24b0-afa0-48f8-a790-064d437b4272.PNG)

i hit save and everytime i press ctrl s the screen fills with "saving", realising my file wasnt saving properly i attempted to overwrite it which produced a 0 byte empty file, and when you attempt to load it back into photopea it comes up with 
" Unknown file format: "\u0000\u0000\u0000\u0000" "

in the screenshot atttatched above there is the issue + the history of what i was last doing.

i'm still able to edit my image and click everything (even with the saving on my screen) and i can still export images as pngs/jpegs, etc. i cannot save as psd/psb it saves as a text file named "null" and i cannot export the layers as it says there are 0

i do have several browser extensions but they shouldn't be conflicting, i use photopea daily and have already used it once today before this, so i feel confident in saying it has nothing to do with my extensions. my browser is updated.

i have lost a good hour or so of work, please fix this!

Thanks!

people with a similar issue:
#4181 
#4160

**Comment by photopea** [comment] 2022-01-09 00:41
Can you describe, how can I make Photopea produce a zero-byte file?

Unless you try to run Photopea with no extensions at all (e.g. in the Incognito mode), we can not be certain, that your problem is not caused by your extensions.

**Comment by photopea** [comment] 2022-02-07 00:34
I have to close it because of lack of details. Also, I think Google has fixed it in the latest Chrome. If the website does not perform the saving properly, the original file is not modified.

**Closed by photopea** 2022-02-07 00:34 UTC

**Comment by BiancaG7** [comment] 2022-04-03 23:02
im having the same problem

**Comment by Y3SS1N** [comment] 2024-11-19 12:40
Your fucking program got stuck and I couldn't click most buttons but saving produced an empty file. Lost several fucking hours of work. I'm pissed off rn.
