### ISSUE TITLE
Cant move the layers

### ISSUE THREAD

**Issue by minionworkingonafriday** [photopea/photopea#3219] opened 2021-05-07 10:13 UTC
cant move the layers up or down or anywhere. please help!

**Comment by photopea** [comment] 2021-05-07 10:41
could you show us a screenshot? Have you tried to close and open Photopea?

**Comment by minionworkingonafriday** [comment] 2021-05-07 11:46
Don’t think a screenshot will help as the it won’t show the problem of not being able to move the layers on the right up or down or anywhere.. 

Yes, I’ve closed and open the photopea. Have also tried using on website and the standalone version.

**Comment by photopea** [comment] 2021-05-07 11:52
does it happen on one specific PSD or on all images that you open in Photopea?

It could be a Quick Mask mode, which we would see in a screenshot.

**Comment by photopea** [comment] 2021-05-13 09:56
I have to close it because of lack of details :(

**Closed by photopea** 2021-05-13 09:56 UTC

**Comment by minionworkingonafriday** [comment] 2021-05-13 12:48
Hi, sorry for the lack of response. Photopea is working fine the next day. Thank you for responding previously.

**Comment by photopea** [comment] 2021-05-13 14:09
You probably created an empty layer. Moving an empty layer will not change the picture.

**Comment by zimbo86** [comment] 2023-01-25 19:12
Hi all, I can confirm this behaviour.
From one to the other second I wanst able to move layers. 
I created a completely new project from the template store - same behaviour.
Edge InPrivate Mode - same behaviour
Edge New Profile (normally completely separated from default profile) - same behaviour
Moved my psd to an Azure VM, also Edge, I can move the layers.

**Comment by photopea** [comment] 2023-01-25 22:22
@zimbo86 What should I do to not be able to move layers?

If you can not describe it, could you record a short vido of what you do?
