### ISSUE TITLE
Windows not responding

### ISSUE THREAD

**Issue by Neum0** [photopea/photopea#6860] opened 2024-06-15 08:46 UTC
The filter gallery window wouldn't close or respond for some reason. I finished making a design and added a filter in the filter gallery. As I clicked "OK" nothing seemed to happen. I tried closing it, but it wouldn't close. It seems like the window itself doesn't want to respond

**Comment by photopea** [comment] 2024-06-15 19:39
What should I do to see such a problem? Everything works fine when I try it :(

**Comment by photopea** [comment] 2024-06-16 17:32
I have to close it because of lack of details :(

**Closed by photopea** 2024-06-16 17:32 UTC

**Comment by Neum0** [comment] 2024-06-18 02:15
Here's a video of it 

https://github.com/photopea/photopea/assets/88815920/de150b75-c505-4789-b26a-2f9948e68996

**Comment by photopea** [comment] 2024-06-18 07:19
So it happened more than once? Can you make it happen on purpose? Could you tell me how do you make it happen?

**Comment by photopea** [comment] 2024-06-18 07:20
Also try it in the Incognito mode of your web browser, before trying anything else. To make sure it is not caused by your browser extensions.

**Comment by Neum0** [comment] 2024-06-18 07:38
I have tried it in Incognito mode and other browsers. Seems like nothing is working. How I made it happen, is that I used the grain tool in the filter gallery and changed some settings in it. Then I clicked OK, but it didn't close or apply the filter to the image. I'm not sure if this happens with the other filters as well since I haven't tested it

**Comment by photopea** [comment] 2024-06-18 08:15
Could you please write down steps, which lead to the problem?

1) open www.Photopea.com
2) open this file in Photopea (give us your file)
3) ....

**Comment by Neum0** [comment] 2024-06-18 10:04
1. Open Photopea
2. Open this file
[Neumo.zip](https://github.com/user-attachments/files/15884303/Neumo.zip)
3. Select the text layer and convert it to a smart object
4. Selecting the text smart object and applying a field blur to it
5. Added points and adjusting the field blur to make it look good
6. Selecting the finished text smart object and the background (which in this case is Layer 1) and converting both of them to a single smart object
7. Go to the filter tab and click on the filter gallery
8. Scroll down until you see the "grain" filter
9. Change the grain type to vertical
10. Messed around with the intensity and contrast

And those are the steps that I did to get the issue. After doing those steps, I couldn't apply the filter to the image. I'm not sure if this also applies to other filters as well.

**Comment by photopea** [comment] 2024-06-18 11:41
I just tried these steps, but I could close the Filter Gallery by clicking "OK".

Did you try these steps more than once? If no, could you try them right now?

**Comment by Neum0** [comment] 2024-06-18 11:50
I have, it seems to not respond when I click OK or the close button

**Comment by photopea** [comment] 2024-06-18 12:10
did you try it in the Incognito mode? What web browser do you use?

**Comment by Neum0** [comment] 2024-06-18 12:27
I have tried it in incognito, i use brave browser

**Comment by photopea** [comment] 2024-06-18 14:18
could you try a different web browser? Like Edge or Opera?

**Comment by Neum0** [comment] 2024-06-19 05:10
I tried it in 2 other browsers, Arc and Edge. Still, they don't seem to work. I did find a workaround to the issue, I just needed to save the text that was given the field blur as an image and then apply the grain effect from there.

**Comment by photopea** [comment] 2024-06-19 06:19
do you confirm the field blur (with a checkmark at the top) after setting it up?

**Comment by Neum0** [comment] 2024-06-19 06:34
Ah, it seems like that was the issue this whole time. Thank you

**Comment by photopea** [comment] 2024-06-19 09:52
I think it is a bug, and I have fixed it. Now, if you do not confirm the blur, and do something else, the blur will be confirmed automatically.
