### ISSUE TITLE
Bug: Fill Colors change when Ctrl + Click on multiple Shape Layers

### ISSUE THREAD

**Issue by KyoGrou** [photopea/photopea#4129] opened 2021-12-16 04:37 UTC
The problem occurs when trying to select / unselect multiple Shape Layers, makes all the selected Shape Layers change its Fill Colors to the last selected layer's color.
![image](https://user-images.githubusercontent.com/30156458/146308699-29d41f4f-14b4-46ad-8297-41a76ee617c8.png)
![image](https://user-images.githubusercontent.com/30156458/146308776-59339434-4ad9-424b-8e60-a397d113972d.png)
![image](https://user-images.githubusercontent.com/30156458/146308838-897a8f31-75f0-4d13-932b-bc9b3ca8741a.png)

**Comment by photopea** [comment] 2021-12-16 12:22
Hi, I am not able to make it happen :(  In my case, no layer ever changes color, when I select more than one.

Could oyu describe how can I reproduce it? What tool is active in a toolbar at that point? Do you have any other windows opened?

**Comment by KyoGrou** [comment] 2021-12-16 14:54
This is quite hard to reproduce, I don't really the exactly cause of this, but I tried these steps and reproduce the bug without fail:

- Create a new project (could be blank or templates), draw, duplicate lots of shape layers, change their fill colors
- Shift + Click select, Ctrl + Click to select and unselect, duplicate layers, draw new shape using rectangle tool, cycle between those action again and again.
- If nothing happened, create a new project without closing the one you was working on, repeat the steps above.

You will see the bug will happen eventually after around 5-10 minutes, on the 3rd or 4th project. After closing Photopea, you will have to repeat those steps again to see it.

**Comment by photopea** [comment] 2021-12-16 18:00
I still can not reproduce it :(  Your description is very vague, you are saying, that even after 10 minutes, it might happen, or might not :/  Could you maybe record a video (shorter than 30 seconds) of how you make the bug happen?

**Comment by photopea** [comment] 2022-10-02 14:55
I have to close it because of lack of details.

**Closed by photopea** 2022-10-02 14:55 UTC
