### ISSUE TITLE
Fonts dont keep after restart

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1980] opened 2020-03-11 18:14 UTC
This will be a bad bug report, but the problem is that i load fonts on photopea and it is all fine.

I can cloase chrome, then open again, and all fine.

But when i turn off my chromebook and the turn on again and open Photopea, the fonts are not loaded.

This have happened long ago, but i don't remember if at some point it was different. Or maybe it has always been like this and just noticed.

I can help you trouble shoot if you like.

Cheers!

**Comment by photopea** [comment] 2020-03-11 18:27
Hi, Photopea uses "IndexedDB" web technology to store data after the webpage is closed. This storage is considered permanent and nothing should delete it (except of you).

I don't know much about Chrome OS, but are you using any browser extensions, which could delete your browsing history, cookies, etc? Could you disable your extensions, load a font into Photopea, and reboot your computer, to see if it stays there?

**Comment by avagp** [comment] 2020-03-17 03:20
I have no extensions enabled :/

I tested to load a font and then inmediatly restart. Photopea keeps the
font.

But i still get the fonts deleted from day to day.

So maybe is something different  :/

**Comment by photopea** [comment] 2020-03-17 08:18
So it is not because of restart.

Do you ever clear browsing history, cache, etc? Do you log in just with one account on your chromebook?

**Comment by avagp** [comment] 2020-03-17 17:51
No and no.

I only have one account.

I never delete history, caché, cookies, none of those.

I will try to replicate it. But it keeps happening to me.

**Comment by photopea** [comment] 2020-03-25 12:56
BTW. this post tells, that Safari will delete all local storage once a week: https://ar.al/2020/03/25/apple-just-killed-offline-web-apps-while-purporting-to-protect-your-privacy-why-thats-a-bad-thing-and-why-you-should-care/

**Comment by avagp** [comment] 2020-03-27 16:43
Chrome as well, 18 months by default and can be configured:
https://searchengineland.com/you-can-now-automatically-set-your-google-history-to-be-deleted-316266

But i should not be my case :/

I should create a bug report on chromiun

**Comment by photopea** [comment] 2020-03-27 16:56
I think you should find a way to reproduce this bug (find a way to make it happen). You are the only one who reported it, so I think there could be something special about your case.

**Comment by photopea** [comment] 2020-04-20 22:23
I will close it now. Let me know if you find a reason why it happens.

**Closed by photopea** 2020-04-20 22:23 UTC

**Comment by avagp** [comment] 2020-10-15 14:38
Hi again.

I still have this problem. And i have a new chromebook.

I feel it is related to chromebooks  :/

**Comment by avagp** [comment] 2020-10-15 14:43
No i don't
[image: image.png]

Please give me your address and i will send you a cheap chromebook!

It is weird, because it keeps the font. But after a couple of days, it
disappeared.

Let me do a little research and i will contact you again  :)

**Comment by photopea** [comment] 2020-10-15 14:47
I will probably buy a chromebook, if there are more issues like that :)

Have you looked into Chromebook settings? Maybe there is a checkbox "Clear all website data every 30 days" :/

**Comment by avagp** [comment] 2020-10-15 20:44
on the browser side, chromebooks are equal.

on the OS side is the difference. So the caché related settings come from
chrome web browser, the same you have.  :/

**Comment by photopea** [comment] 2020-10-15 21:07
I am sure there are many settings in Chrome OS, which are not available in Chrome browsers.

**Comment by avagp** [comment] 2020-12-17 18:15
After a couple of weeks, this issue does not exists.

The fonts are kept how it is meant to be.

So, for chromebooks this is solved.
