### ISSUE TITLE
Photopea Ouvre les fichier PSD de mauvaise qualité

### ISSUE THREAD

**Issue by NonoLexeFR** [photopea/photopea#6097] opened 2023-10-12 22:54 UTC
Your Operating System: Window 11
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. .... lauch https://drive.google.com/drive/folders/1JDOjAmnTWE5-6GQ8WF9XLAb4ZF43xWls
3. .... https://i.imgur.com/MRfhMy5.png
4. ....

**Comment by photopea** [comment] 2023-10-13 08:15
It is a bug in Windows 11. Could you try to update your operating system or your drivers?

I was never able to reproduce it in order to fix it :(  It is a bug in WebGL, so you can simply disable WebGL using More - Use WebGL. But Photopea is very slow without WebGL.

**Comment by photopea** [comment] 2023-11-06 15:27
I have to close it because of lack of details :(

**Closed by photopea** 2023-11-06 15:27 UTC
