### ISSUE TITLE
Broken shapes that makes it unable to save as PSD/PSB

### ISSUE THREAD

**Issue by Furthir** [photopea/photopea#4683] opened 2022-05-30 12:31 UTC
I found shapes in my project that are "corrupted" in a sense. Randomly switching between tabs, changing visibility, or some other actions can make all of the shapes in the project invisible. 

The preview before saving the project as a normal image like PNG, JPG, or BMP has the same visibility issues, but the preview for saving it as PDF or SVG work fine. Trying to save it as a PSD does nothing and throws an error in the console, and saving it through the Save PSD/PSB button just gives me a blank null.txt file. 

Changing or clicking on any of the paths on a shape using the path select tool will make the shapes reappear. Some shapes seem to have no effect on saving it as a PSD, though still has visibility issues. I'm gonna assume this is a rare one-off occurrence but still kind of interested how this happened. I also doubt I can recreate this so yeah.
![image](https://user-images.githubusercontent.com/89289837/170992274-eccba8aa-7b5b-480e-b8e9-b13a98fed2bc.png)
![image](https://user-images.githubusercontent.com/89289837/170992278-c254b2b7-69f2-4a1f-927f-c07a44a9e980.png)
![image](https://user-images.githubusercontent.com/89289837/170992284-36337498-2080-4f8e-aefb-6864dfb4657a.png)

**Comment by photopea** [comment] 2022-05-30 12:54
Could yu try to reproduce it? We can not fix problems which cannot be reproduced :(

**Comment by photopea** [comment] 2022-07-31 23:30
I have to close it because of lack of details.

**Closed by photopea** 2022-07-31 23:30 UTC
