### ISSUE TITLE
Photopea doesn't open offline on Vivaldi Browser

### ISSUE THREAD

**Issue by Devetec** [photopea/photopea#5693] opened 2023-05-29 17:47 UTC
On Chrome and Firefox, when you go offline, you are still able to open Photopea. However, on Vivaldi, this doesn't work for some reason.

**Comment by photopea** [comment] 2023-05-29 19:57
Is there any website that you can open in Vivaldi when you go offline? Why do you think the problem is in Photopea and not in Vivaldi? Did you report this to Vivaldi?

**Comment by photopea** [comment] 2024-01-03 22:21
I have to close it because of lack of details :(

**Closed by photopea** 2024-01-03 22:21 UTC
