### ISSUE TITLE
PSDs with blank files

### ISSUE THREAD

**Issue by Wolvenhyde** [photopea/photopea#2309] opened 2020-07-20 01:14 UTC
I haven't tested this fully, but a lot of the time I save an image as a PSD and it won't open in my program. Other people with other programs can open it, but the layers show as blank...

What I know is this:
- It usually has to do with files in folders, files outside folders are generally showing
- When there's no blank files it opens fine in my program (Paint.net)
- Exporting Layers works, but I don't want a bunch of files, just one.
- Other programs (Photoshop, metabang, clip studio paint, sai) will open the file, but anything in folders shows as not having anything whether the layer is visible or not.
- Resaving it doesn't do anything different, so it isn't corruption during saving.
- Reopening the file in Photopea shows the files as they're supposed to be, so it's not they go blank, but rather the programs can't read the contents of the layer

I don't know anything else, but I am willing to answer questions and try to figure this out because it's been a pain...

**Comment by Wolvenhyde** [comment] 2020-07-20 01:27
Slight update, tested removing folders, still shows blank. Wondering if it might have to do with duplicating layers into other files now.

**Comment by photopea** [comment] 2020-07-20 06:42
Hi, that sounds to me like a bug in Paint.net , not in Photopea.

How do we prove, that there is something wrong with Photopea? Could you prepare the same file (same structure of layers and folders) both in Photopea and some other PSD program (e.g. Photoshop) and  save both as PSD? Will they both work in Paint.net ?

**Comment by photopea** [comment] 2020-07-22 10:20
I have to close it because of lack of details.

**Closed by photopea** 2020-07-22 10:20 UTC

**Comment by Wolvenhyde** [comment] 2020-07-22 15:34
@photopea I'm sorry I didn't notice your reply and only just got back.

As said, It's not an issue with Paint.net. Paint.net cannot open the file, but that's not my issue.

My issue is that other programs, ie Photoshop, Sai, Clip Studio Paint, etc CAN open the file, but the layers don't have anything in them and show blank.

**Comment by Wolvenhyde** [comment] 2020-07-22 15:41
@photopea 

That said, I can make the same file in the other programs by exporting the layers and organizing in a PSD on the other programs and it opens fine in Paint.net. Paint.net can open PSDs and usually does this just fine. Even files from Photopea it's fine with.

HOWEVER on occasion a file will have that issue. It's NOT Paint.net, or Paint.net would have issues with more files. Every file it has issues with, when opened in other programs one or more layers has nothing on it.

Again, I'm not trying to figure out the issue with Paint.net. I already know that issue.
My issue is that on occasion I'll save it, and when opened in Photoshop, Sai, Paint Studio, etc layers will show blank.

**Comment by photopea** [comment] 2020-07-22 15:43
If I understand correctly, you export a PSD from Photopea, which looks differently in Photoshop, than how it looked in Photopea. Could you show us such PSD? We can not do much without having a PSD file, or without knowing how to reproduce it.

**Comment by Wolvenhyde** [comment] 2020-07-22 15:48
@photopea Yes, basically I have a png image which I open on photopea. I duplicate that png over to another file in which I have folders to organize the layers. It shows normal, everything works fine. I save it to my computer as a PSD. Sometimes it's fine, and looks the same. Sometimes, the layers will have miscoloring or some kind of green along the lines. Sometimes, the layer is just simply blank.

That is how it shows in other programs. I reopen it in photopea, and it looks fine. Let me get you images and files 1 sec

**Comment by Wolvenhyde** [comment] 2020-07-22 15:59
Here's one example, this was sent to me by someone trying to use one of the files, I had to get someone who it somehow didn't glitch for to resave the PSD on their program and it worked for people then on:
https://cdn.discordapp.com/attachments/588119200829276184/684177246985912320/unknown.png (Glitched)
https://cdn.discordapp.com/attachments/588119200829276184/684177523688341512/unknown.png (What it's supposed to look like)
Let me save the current PSD I'm having the blank layer issue with to drive real fast for you

**Comment by Wolvenhyde** [comment] 2020-07-22 16:03
https://drive.google.com/file/d/1S64qj5aobbbk7g2pqT-1AQW5LFoQktLC/view?usp=sharing
Here's the PSD. As you can see, it shows the preview on drive just fine. it opens fine in photopea. when opened with clip studio paint (most of) the layers are blank, idk if Sai or Photoshop have the issue with the file, as I haven't yet checked, but I can in a moment if you need. I have had issues where they show blank with those programs as well though. @photopea

**Comment by Wolvenhyde** [comment] 2020-07-22 16:17
I asked a friend and they said the file in question is working for their Sai. But I have had instances where it is blank for them in the past.

**Comment by photopea** [comment] 2020-07-22 16:17
I opened your PSD in Photopea and Photoshop, it looks the same in both programs. The layers contain the same images, too.

**Comment by Wolvenhyde** [comment] 2020-07-22 16:21
Yeah, my friend said the same.
They resaved the file not changing anything on their program, then it opened fine in the ones that were having the issues, so now I'm confused.
It won't view properly when opened after saving off photopea, but opens fine if resaved off other programs? IDK what issue that could be...

**Comment by photopea** [comment] 2020-07-22 16:28
If you make a PSD in Photopea and open and resave it in Photoshop, the new PSD may not be identical to a Photopea PSD (in terms of ones and zeros). But both of them are correct PSDs, and both Photoshop and Photopea can open both PSDs.

So I think the bug is in Clip Studio Paint, as it can not open a PSD from Photopea, while Photoshop can.

**Comment by Wolvenhyde** [comment] 2020-07-22 16:33
Alright, thanks. If I have any issues with it in the future/updates I'll reach out. Thanks.

**Comment by photopea** [comment] 2020-07-22 16:37
Have you tried to do what you do in Clip Studio Paint in Photopea instead? Are there any crucial features you are missing in Photopea?
