### ISSUE TITLE
FONTS?

### ISSUE THREAD

**Issue by ktdid518** [photopea/photopea#1925] opened 2020-02-06 16:48 UTC
I am using Photopea to convert sketch files to Photoshop for developers.

What does the future of proper font rendering look like?

The absolute most time consuming and inefficient part of using Photopea is that I have to select every text box to update to the correct font. Some of my files are really complex and this is not a sustainable way to update them.

Thanks!

**Comment by photopea** [comment] 2020-02-06 16:58
Hi, the problem is, that no fonts are included in Sketch files, and Photopea can not use fonts installed in your computer (like Photoshop or Sketch App can). We have many free fonts on our server, that can be used, but we don't have a licence to commercial fonts like Helvetica or Arial.

If you have the required fonts (OTF or TTF files), drag-and-drop them to Photopea before opening a Sketch file. Then, these fonts will be used during the rendering of Sketch and other files.

Photopea allows you to keep your fonts in a local storage, so they will stay even after closing Photopea.

**Closed by photopea** 2020-02-06 16:58 UTC

**Comment by ktdid518** [comment] 2020-02-06 17:12
Clearly I did not know that I could upload fonts. That is FANTASTIC! Thank you!
