### ISSUE TITLE
Feature Request: Full access to Dezgo

### ISSUE THREAD

**Issue by AviceProjects** [photopea/photopea#5362] opened 2023-02-11 23:47 UTC
We really need access to Dezgo's models and the rest of its settings.

Possible values:

stablediffusion_1_5
stablediffusion_1_4
stablediffusion_2_0_512px
stablediffusion_2_0_768px
stablediffusion_2_1_512px
stablediffusion_2_1_768px
waifudiffusion_1_3
anything_3_0
trinart_2_0
openjourney
synthwavepunk_v2
redshift_diffusion
analog_diffusion
disco_diffusion_style
iconsmi_appiconsmodelforsd
lowpoly_world
vintedois_diffusion_v0_1

**Comment by camoody1** [comment] 2023-02-11 23:57
Yesssss. Please add these parameter options. It may require a rework to the current Text-to-Image configuration menu, of course. 

The other option that Dezgo offers, in addition to text-to-image and Inpainting, is upscaling! We should totally be taking advantage of that option within Photopea. When I have a low resolution background image that I want to pair with a high resolution foreground image, it would be great to be able to upscale that background layer first.

**Comment by photopea** [comment] 2023-02-12 00:08
I think these things cost money. You would enter your own API key into Photopea? Or how is it supposed to work?

**Comment by camoody1** [comment] 2023-02-12 00:26
Most of the additional parameters cost nothing. They just allow us to select an option instead of using whatever the default value is. The only options that affect cost are number of pixels processed, whether or not an image is upscaled (upscaling a 512x512 image is actually cheaper than processing a 1024x1024 image), and increasing the number of steps used to process an image (the default is 30, but it goes up to 150 - the max anyone ever really recommends is 100).

**Comment by AviceProjects** [comment] 2023-02-12 03:59
> I think these things cost money. You would enter your own API key into Photopea? Or how is it supposed to work?

Changing the seed, guidance, sampler, negative prompt, and 
model is completely free. Lowering the steps and size is also completely free.

The API page tells you what will increase the cost.
https://rapidapi.com/dezgo/api/dezgo

**Comment by photopea** [comment] 2023-02-12 10:07
Are you talking about the Window - More - Text to Image feature of Photopea? You never mentioned it.

**Comment by camoody1** [comment] 2023-02-12 10:53
> Are you talking about the Window - More - Text to Image feature of Photopea? You never mentioned it.

Yes, sir. That's what we're talking about. You're using Dezgo for your API calls, and were just reading the available configuration parameters for those API calls off their website and suggesting that you allow the user to choose their own values to send in the API instead of just using the default values. Of course, in order to give the user access to select his/her own values for these parameters, you would need to redesign your current gui layout for the Window -> More -> Text-ro-Image feature.

**Comment by AviceProjects** [comment] 2023-02-23 22:42
Yeah, if you gave users a couple of dropdown boxes, they could access all of the features that come free with a Dezgo subscription. Even if you require a manual API key, it would still be worth it since you could fully utilize stable diffusion inside of Photopea.

**Comment by AviceProjects** [comment] 2023-02-23 22:42
> Are you talking about the Window - More - Text to Image feature of Photopea? You never mentioned it.

Yeah, if you gave users a couple of dropdown boxes, they could access all of the features that come free with a Dezgo subscription. Even if you require a manual API key, it would still be worth it since you could fully utilize stable diffusion inside of Photopea.

**Comment by photopea** [comment] 2023-02-24 00:44
Right now, there are about 15 users who use Text to Image, and none of them entered their own API key (i.e. users expect us to pay for them). I don't know if it is worth paying Dezgo hundreds of dollars a month for something what is used by a couple of non-paying users.

**Comment by AviceProjects** [comment] 2023-02-24 00:56
> Right now, there are about 15 users who use Text to Image, and none of them entered their own API key (i.e. users expect us to pay for them). I don't know if it is worth paying Dezgo hundreds of dollars a month for something what is used by a couple of non-paying users.

You are already paying for the features I talked about. You can see all the parameters here: https://rapidapi.com/dezgo/api/dezgo

**Comment by camoody1** [comment] 2023-02-24 04:12
The reason I don't use the option that much is twofold:

1. It doesn't offer enough options to be able to use it to its full extent to get good images.
2. It doesn't really the AI steps that I use most often.

AI Image creation is super interesting and fun, but there are just too many other dedicated sites that do it better (understandably) because that's all they do. Photopea can't really compete with those offers and it shouldn't be trying to keep up with their rapid advancements.

What AI does that I would LOVE to have in Photopea, however, is Enhancing low resolution, blurry or damaged images AND Enlarging images to higher resolution. I use two sites constantly to perform these functions outside of Photopea. It would be amazing if functionality of this type and capability were available inside Photopea.

The two sites I use every day are:
https://www.cutout.pro/photo-enhancer-sharpener-upscaler (for Image Enhancement and Upscaling)
https://bigjpg.com/ (for simple Image Upscaling)

**Comment by AviceProjects** [comment] 2023-02-25 19:07
It may seem pointless to add more features to the text-to-image feature even if it wouldn't cost you any money, but I think it's a great opportunity considering the fact A.I. art is blowing up right now. Something like this would be perfect.
![image](https://user-images.githubusercontent.com/125163447/221375155-1af91d04-b30d-49b1-a92a-951a64efe3dc.png)

**Comment by camoody1** [comment] 2023-02-25 21:54
> It may seem pointless to add more features to the text-to-image feature even if it wouldn't cost you any money, but I think it's a great opportunity considering the fact A.I. art is blowing up right now. Something like this would be perfect. ![image](https://user-images.githubusercontent.com/125163447/221375155-1af91d04-b30d-49b1-a92a-951a64efe3dc.png)

I would say, if Ivan intends to keep the text-to-image option available, something like this gui is absolutely a necessity to make it worthwhile.

Additionally, if he's going to keep the Dezgo access, Photopea should take advantage of the post/upscale API call that it offers to double the size of images. I often have a low resolution image that I want to combine with a high resolution image and they just look terrible together until I upscale the lower resolution image. If I could do that upscale inside Photopea instead of another website, that would be very useful.

**Comment by photopea** [comment] 2023-02-27 13:23
The inpainting from Dezgo works really well. I could add a button "Heal Selection AI" next to "Heal Selection" (when using a spot healing brush). But inpainting a 512 x 512 area costs 20x more than our background removal (Select - Remove BG).

**Comment by camoody1** [comment] 2023-02-27 15:18
I don't think that would really do what we'd want it to do, anyway. Imagine if I had a 2000x2000px image with a tree I needed to "heal" out. If I masked out the tree and then used the existing AI Inpainting that we have, that entire image would downsized, modified and then sent back to us at a maximum size of 512x512px. The detail loss would be pretty unacceptable... unless you could paste the fix JUST back over the masked out pixels while leaving the rest of the 2000x2000px image alone.

That sounds like a lot of work, but really the only way to get a decent result.🤷🏽‍♂️

**Comment by AviceProjects** [comment] 2023-02-27 21:10
I think adding the rest of Dezgo's parameters could bring a lot of new users to Photopea. Dezgo is an amazing Stable Diffusion service but there are zero websites actually utilizing it. You could add all of the parameters completely for free, and probably gain a fair amount of exposure from doing so.

**Comment by camoody1** [comment] 2023-02-28 10:18
To be clear, "Heal Selection AI" is just Inpainting without sending any prompt parameter, correct? And you would be handling the required "mask" via code after the user selects the area to be healed? And then, ACTUAL "Inpainting" would still be a separate option under the Text-to-Image panel that would still work as it currently does... a masked area created by the user to be filled in based on prompt text chosen by the user.

**Comment by AviceProjects** [comment] 2023-03-03 05:08
Yeah, I think he's talking about an AI-powered healing tool similar to the Remove BG feature. And yeah, whether we are talking about healing or inpainting, we should try to prevent downscaling as much as possible. And also, for confirmation, the documentation at https://rapidapi.com/dezgo/api/dezgo now says "The following parameters influence the request cost: width, height, steps, upscale"

**Comment by AviceProjects** [comment] 2023-03-03 19:03
You could also give a credit allowance to each premium user, and use Dezgo's credit calculator: 
pixels = max(width * height, 512 * 512)
credits_cost = (pixels * 6.849e-006 - 1.133) * max(steps, 10)

**Comment by camoody1** [comment] 2023-03-05 18:22
Checkout this new Photoshop plugin for Stable Diffusion/Automatic1111/Control.Net. This is the way to truly integrate Stable Diffusion into an image editor.

https://www.reddit.com/r/StableDiffusion/comments/11iuqhv/major_update_automatic1111_photoshop_stable/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

I assume it's all being done locally on the user's PC. Likely requires an Nvidia RTX 3000+ card to work well. Impressive, nonetheless.

**Comment by AviceProjects** [comment] 2023-03-14 18:11
So, is this feature request something you plan to add @photopea? Right now would be the perfect time to add it if you want more people using Photopea. Dezgo also now has a discord, so you can now easily communicate with its developers. https://discord.gg/NRVjXFW6Cq

**Comment by photopea** [comment] 2023-03-14 18:47
The problem is, that I dont want users of Photopea use Dezgo services, as I can not afford paying for Dezgo.

Right now, only about 50 people use Dezgo in Photopea, but if it is more than that, I will remove this feature. And it makes no sense to do the work that only 50 users will use.

**Comment by AviceProjects** [comment] 2023-03-14 18:58
If you gave each user a credit allowance, you could grow the image generation feature without having to worry about losing money.

**Comment by photopea** [comment] 2023-03-14 19:53
Do you mean each paying user or each user who has logged in?

We have 1 million users who log into Photopea, and if we gave $1 of credit to everyone, we would go bankrupt a long time ago.

**Comment by AviceProjects** [comment] 2023-03-14 20:10
I meant each paying user. You could give each paying user a 40,000 credit allowance which is around 2105 images and still make money. The minimum a user can pay for Photopea is $4.17 when spending $50 for 365 days, which is around 41,700 credits.

**Comment by photopea** [comment] 2023-03-14 20:58
I dont want to be just a reseller of Dezgo services :D

**Comment by AviceProjects** [comment] 2023-03-14 21:26
Well, you already have the Dezgo incorporated into Photopea. And I'm sure the developers of Dezgo would be honored to work with you.

**Comment by camoody1** [comment] 2023-03-14 22:21
Ivan, remind me, who are you using for the Remove BG option? I wonder if they've added any more functionality. I forget who it was.

**Comment by photopea** [comment] 2023-03-14 22:41
I am using these guys https://rapidapi.com/organization/api4ai

**Comment by AviceProjects** [comment] 2023-04-15 17:36
> I am using these guys   @@https://rapidapi.com/organization/api4ai

With Dezgo releasing a new API, I'll make my last attempt to persuade you. So even if Dezgo wanted to work with you, and every Photopea wanted full Dezgo in Photopea, you still wouldn't work with them? You are already a reseller of Dezgo's services, you literally charge people for unlimited Dezgo access.

**Comment by camoody1** [comment] 2023-04-15 19:08
@AviceProjects What is the new API? 

@photopea I'm still begging you to implement their Super Image API. I would love to be able to use AI to double or quadruple smaller images for mixing with higher resolution images. And it says that the API is totally FREE! So, that would be a nice win for the app.
https://rapidapi.com/sensorai-sensorai-default/api/super-image1/

**Comment by AviceProjects** [comment] 2023-04-15 19:19
@camoody1 

It's on their website https://dezgo.com, and uses the website's credits for API payment. The RapidAPI version is now legacy.

**Comment by photopea** [comment] 2024-01-03 22:43
I will close it now, as I think we have moved quite a lot from this point.

**Closed by photopea** 2024-01-03 22:43 UTC
