### ISSUE TITLE
to many issues time to move on

### ISSUE THREAD

**Issue by Bigangrydog** [photopea/photopea#6935] opened 2024-07-03 17:10 UTC
the move tool works half the time, ctrl A works half the time, the key board shortcut barley work at all. I understand its free but why even bother if it doesn't work half the time

**Comment by photopea** [comment] 2024-07-03 17:44
What should I do to see such a problem myself? Do you use Internet Explorer?

**Comment by camoody1** [comment] 2024-07-03 22:30
@Bigangrydog The app works perfectly fine for me when we I use it. Have you considered this might be a "you" problem? There's a 95% chance your issues are being caused by a browser extension or by the browser you're using not supporting all of the necessary browser requirements. Try running Photopea in Chrome or Edge with all browser extensions disabled. See if it works correctly then. If it does, start adding back browser extensions one at a time to find out which one is causing you problems.

**Comment by Bigangrydog** [comment] 2024-07-03 22:46
I appreciate getting back to me so fast, it does show that your
customer service is top notch. After seeing this response I went back to
check and the hotkeys do seem to be working much better. Earlier in the day
the ctrl alt T wouldn't work, ctrl A didn't select any text in the text
box, and the ctrl V did absolutely nothing.     I am using Edge on a
windows 11 laptop. Thank you again for responding. I am in the process like
a  lot of other people in finding an adobe alternative, I will be giving
this another shot.

**Comment by photopea** [comment] 2024-07-04 08:02
Do you have the AZERTY keyboard? In that case, you must press A where it is located on your keyboard (it is different than on the english keyboard). Or switch your keyboard language to English.

**Comment by photopea** [comment] 2024-07-07 09:58
I have to close it because of lack of details.

**Closed by photopea** 2024-07-07 09:58 UTC
