### ISSUE TITLE
Text box will not go away

### ISSUE THREAD

**Issue by JanRowland11** [photopea/photopea#1717] opened 2019-10-04 21:58 UTC
I used the text key hoping to enlarge the letters and change the font. It is one layer with two words.
The thumbnail is clicked on and it will not let me click on any other layer. I cannot get rid of the box.  It won't give me a cursor for typing text, it just moves the layer around. The tools are showing the box at the top that lets you resize images, which I did before this . I tried double clicking the thumbnail to get the text working, but it doesn't work. Any help will make my day!

**Comment by photopea** [comment] 2019-10-04 22:04
Hi, if you try it multiple times (and you start from opening Photopea.com), does it happen each time? If yes, could you explain, what exactly did you do, and maybe send us your files?

We need to be able to make it happen ourselves. It is not possible to reproduce it from your description (text tool always works well for me).

**Comment by photopea** [comment] 2019-10-15 22:12
I have to close it because of lack of details :(

**Closed by photopea** 2019-10-15 22:12 UTC
