### ISSUE TITLE
Keeping this short: Holding in the mouse longer gets me faster and smoother rendering on the app

### ISSUE THREAD

**Issue by NullyTheNuggat** [photopea/photopea#1580] opened 2019-07-25 18:57 UTC
Firefox 68.0.1 (64-bit)
GTX 1080
I7 7700K
144Hz Gsync 1440p

So the longer I hold in my mouse the smoother, faster and more responsive the rendering/action the brush gets. ex: eraser brush -- starts out choppy and laggy then slowly gets wayyyyy better

**Comment by photopea** [comment] 2019-07-25 20:09
It is hard to say what is a reason of this. Can you try any other browser?

BTW. Photopea produces the set of pre-rendered brush samples during the beginning of the stroke, but it only uses them later. So I think it is an expected behaviour for very large brushes - 400px and more.

**Comment by photopea** [comment] 2019-07-31 18:54
I have to close it because of lack of details :(

**Closed by photopea** 2019-07-31 18:54 UTC
