### ISSUE TITLE
Editing is impossible

### ISSUE THREAD

**Issue by jgmosquera2016** [photopea/photopea#3457] opened 2021-06-26 00:14 UTC
Hi! Photopea is excellent. But today, at this time, for some reason, the working plane is slowly shifting to the left and it is impossible to edit. Greetings! Juan, from Buenos Aires, Argentina.

**Comment by photopea** [comment] 2021-06-26 07:21
Hi, did it happen more than once? Can you describe steps, how to reproduce it?

**Comment by photopea** [comment] 2021-06-30 20:11
I have to close it because of lack of details :(

**Closed by photopea** 2021-06-30 20:11 UTC
