### ISSUE TITLE
Cannot preview layer

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#5664] opened 2023-05-24 17:35 UTC
I am attaching a PSD that i cannot see the preview of the smart objects.

![image](https://github.com/photopea/photopea/assets/11801254/05ad060d-38c2-4614-b540-57644eb8ae4c)

[Patrón de Caras2.zip](https://github.com/photopea/photopea/files/11557423/Patron.de.Caras2.zip)

[Screen recording 2023-05-24 13.33.47.webm](https://github.com/photopea/photopea/assets/11801254/c62098f7-8b07-4793-9d59-e3ba19a0b688)

**Comment by TheRadicalDreamer** [comment] 2023-05-24 17:55
On the same file.

If you go to pattern view, the adjustment layer is applied hundred of times, so you cannot see the proper created pattern

![image](https://github.com/photopea/photopea/assets/11801254/5b45295b-f199-4303-91ee-4709b291c94a)

![image](https://github.com/photopea/photopea/assets/11801254/45d42c1c-f48f-4068-87ba-780a85a8009c)

**Comment by camoody1** [comment] 2023-05-24 17:58
I've had this happen occasionally. It's always been on very large files for me. I've just assumed it was caused by a lack of VRAM.

**Comment by photopea** [comment] 2023-05-24 18:05
It has nothing to do with VRAM, it is a bug in Photopea.

**Comment by camoody1** [comment] 2023-05-24 18:13
> It has nothing to do with VRAM, it is a bug in Photopea.

Good to know it's your fault and not mine. 😂

**Comment by photopea** [comment] 2023-06-01 19:24
it should be fixed now :)

**Closed by photopea** 2023-06-01 19:24 UTC

**Comment by TheRadicalDreamer** [comment] 2023-06-07 21:05
It happened again in another file i have.

I am uploading it:
[GL - Fases.zip](https://github.com/photopea/photopea/files/11681930/GL.-.Fases.zip)

**Comment by photopea** [comment] 2023-06-12 17:30
fixed! :)
