### ISSUE TITLE
Issue when logging in with GitHub

### ISSUE THREAD

**Issue by Frater-Galaxy** [photopea/photopea#479] opened 2018-02-16 02:58 UTC
I've been attempting to sign in to Photopea with GitHub, but it results in the login tab saying "photopea didn't recieve your email address." Then when then I reopen to open the website it still requires me to login again. Is there a reason why my GitHub isn't going through?
![screenshot 2018-02-15 at 9 55 01 pm](https://user-images.githubusercontent.com/36263540/36291791-0ff7b428-12c5-11e8-8531-545883f9f128.png)

**Comment by photopea** [comment] 2018-02-16 08:32
Hi, you should set up some email address in your GitHub / Facebook / Twitter account.  So if you log in from different services (once from GitHub, once from Facebook), Photopea would be able to identify you as the same person by that email address.

You should be able to enter your email address somewhere in GitHub settings.

**Comment by spicydonuts** [comment] 2018-02-26 17:25
I tried logging in with Github and received the same error.  Github's OAuth screen and my account settings both show my email address as the shared scope and I log in with Github on other sites.

**Comment by photopea** [comment] 2018-02-27 01:13
Hi. That is really strange. Are you sure you allowed 3rd party services to read your email? Or maybe you have to allow it to Photopea specifically somehow.

**Comment by spicydonuts** [comment] 2018-02-27 06:35
That's how it works, and yes, the Photopea Github app is specifically allowed my email.  Are you not able to reproduce on a first time sign in from Github?

**Comment by photopea** [comment] 2018-02-27 14:22
Ok so I made Photopea print the whole response, that it gets from GitHub. Can you try it again and show us the response that is printed to you?

**Comment by photopea** [comment] 2018-03-31 22:50
I have to close it because of the lack of details.

**Closed by photopea** 2018-03-31 22:50 UTC

**Comment by biziclop** [comment] 2018-05-02 08:10
Hi, this is the response I got:

    array(3) {
      ["result"]=>
      array(30) {
        ["login"]=>
        string(8) "biziclop"
        ["id"]=>
        int(904630)
        ["avatar_url"]=>
        string(51) "https://avatars3.githubusercontent.com/u/904630?v=4"
        ["gravatar_id"]=>
        string(0) ""
        ["url"]=>
        string(37) "https://api.github.com/users/biziclop"
        ["html_url"]=>
        string(27) "https://github.com/biziclop"
        ["followers_url"]=>
        string(47) "https://api.github.com/users/biziclop/followers"
        ["following_url"]=>
        string(60) "https://api.github.com/users/biziclop/following{/other_user}"
        ["gists_url"]=>
        string(53) "https://api.github.com/users/biziclop/gists{/gist_id}"
        ["starred_url"]=>
        string(60) "https://api.github.com/users/biziclop/starred{/owner}{/repo}"
        ["subscriptions_url"]=>
        string(51) "https://api.github.com/users/biziclop/subscriptions"
        ["organizations_url"]=>
        string(42) "https://api.github.com/users/biziclop/orgs"
        ["repos_url"]=>
        string(43) "https://api.github.com/users/biziclop/repos"
        ["events_url"]=>
        string(54) "https://api.github.com/users/biziclop/events{/privacy}"
        ["received_events_url"]=>
        string(53) "https://api.github.com/users/biziclop/received_events"
        ["type"]=>
        string(4) "User"
        ["site_admin"]=>
        bool(false)
        ["name"]=>
        NULL
        ["company"]=>
        NULL
        ["blog"]=>
        string(0) ""
        ["location"]=>
        NULL
        ["email"]=>
        NULL
        ["hireable"]=>
        NULL
        ["bio"]=>
        NULL
        ["public_repos"]=>
        int(4)
        ["public_gists"]=>
        int(0)
        ["followers"]=>
        int(2)
        ["following"]=>
        int(0)
        ["created_at"]=>
        string(20) "2011-07-09T13:04:46Z"
        ["updated_at"]=>
        string(20) "2018-04-18T00:15:47Z"
      }
      ["code"]=>
      int(200)
      ["content_type"]=>
      string(31) "application/json; charset=utf-8"
    }
    Photopea didn't receive your email address.

**Comment by photopea** [comment] 2018-05-02 08:14
You have to set some email address in your GitHub account. Photopea identifies users by their email addresses.

**Comment by biziclop** [comment] 2018-05-02 08:16
Yes, I just did that and edited my comment, but you were faster. That error message is a bit scary, and it's not easy that there is a human-readable error message at the bottom. :)

**Comment by photopea** [comment] 2018-05-02 08:19
I printed it out, because we needed to debug it with one user. So do you understand everything? Or do you want me to do anything?

**Comment by biziclop** [comment] 2018-05-02 08:31
Well, you could print something like this:

> `if( empty( $result['email'])) : ?>`
> 
> Photopea could not determine your email address.
> 
> Please visit your your [GitHub profile page](https://github.com/settings/profile) and fill in the `Public email` field, and try again.
> 
> ![untitled-1](https://user-images.githubusercontent.com/904630/39513013-2cad4470-4df3-11e8-939e-84b8e618e0f6.png)
> 
> Error dump:
> 
> ```
> array(3) {
>   ["result"]=>
>   array(30) {
>     ["login"]=>
> ```

**Comment by photopea** [comment] 2018-05-02 08:38
The mechanism of changing an email can be different for GitHub, Google, Facebook or other services in the future. We can not educate people on how to use these services, it is no the goal of Photopea. Also, these mechanisms of changing email can change in the future, it would be too hard to keep our instructions up to date.
