### ISSUE TITLE
Preview image is invisible unless its edges are outside the window (Google Chrome 103 x64)

### ISSUE THREAD

**Issue by 6bzt** [photopea/photopea#4875] opened 2022-07-31 11:13 UTC
This bug occurs in Export, Filter Gallery, Camera Raw, Liquify, Magic Cut, and Refine Edge.
When the user chooses to export to a raster format (PNG, JPG, GIF, WebP, BMP, TIFF, ICO, DDS, TGA, PPM), the visual bug occurs when the preview image's edges are inside the frame, thus hiding the preview. In cases where the image is small enough, the preview has to be zoomed in to be displayed.
For other menus mentioned above, the preview is displayed at first, but disappears when it has been panned, zoomed, or interacted with.

This visual bug doesn't occur in other browsers. In Firefox and Microsoft Edge, it can't be reproduced.

https://user-images.githubusercontent.com/110330989/182023059-bf3b3e7f-f551-43e1-a820-f2e125c656d9.mp4

**Comment by photopea** [comment] 2022-07-31 11:56
I can not reproduce it :( Do you see any errors in the web console?

**Comment by 6bzt** [comment] 2022-07-31 15:03
Not much luck with the console.
Most of the output in the console was from advertising. Fortunately, I was able to make the logs look cleaner.
What's more strange is that the preview flickers when panning, but that's only when Developer Tools are open.

The only thing related to the aforementioned menus is the "creating image data" information.
The handler delay is normal, so it's not the issue. 
The FetchEvent is most likely not the problem, as it's only related to advertising.
Maybe it's the blocked access to a fetch or the non-passive event listener, I'm not sure.

![Logs_Compressed](https://user-images.githubusercontent.com/110330989/182032188-7f52b672-1631-4c08-b05b-ebef185a4240.png)

**Comment by photopea** [comment] 2022-07-31 18:14
Could you reset your Chrome to factory settings? Are you sure no extensions are running in the Incognito mode? Is Chrome translating the website automatically?

**Comment by SmuckLord** [comment] 2022-08-01 00:07
Im also having a similar problem magic cut and refine edge just go invisible when trying to interact with it. changing the zoom size seems to fix it but not really?



https://user-images.githubusercontent.com/110360113/182051130-48db580f-81fe-4903-8a8a-2c75ab751c2c.mp4

**Comment by photopea** [comment] 2022-08-01 09:33
Could you share a screenshot of about://gpu of your browser? Also, is it really Chrome and not Brave, Vivaldi etc?

**Comment by photopea** [comment] 2022-08-01 09:52
Can you confirm, that it happens for every file you try, and it happens in the incognito mode?

**Comment by photopea** [comment] 2022-08-01 14:34
Turns out the bug happened only on Intel machines, that is why I could not reproduce it on an AMD machine.

**Comment by photopea** [comment] 2022-08-01 14:34
It is fixed now.

**Closed by photopea** 2022-08-01 14:34 UTC
