### ISSUE TITLE
stuck at saving 

### ISSUE THREAD

**Issue by karlagpalo** [photopea/photopea#6708] opened 2024-04-29 13:29 UTC
Your Operating System: Processor	AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx, 2100 Mhz, 4 Core(s), 8 Logical
512gb rom / 8gb ram
Your Web Browser: chrome
The problem happens in the Incognito Mode, too: n/a

**This must be done to see the problem**
1. 
2. ....
3. ....
4. ....

**Comment by photopea** [comment] 2024-04-29 13:54
What should I do to see it happen myself? People saved over 3 million files in Photopea in the last 24 hours, so I think it works for most of them. It is usually caused by your browser extensions.

**Comment by photopea** [comment] 2024-05-27 22:00
I have to close it because of lack of details.

**Closed by photopea** 2024-05-27 22:00 UTC
