### ISSUE TITLE
Gifs fail

### ISSUE THREAD

**Issue by angelaiaru** [photopea/photopea#7171] opened 2024-09-21 02:07 UTC
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
![Captura de tela 2024-09-20 230735](https://github.com/user-attachments/assets/602574b7-3e01-42c1-abda-5b585985c61a)

1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment] 2024-09-21 06:23
I do not understand what the problem is :( Why cant you write down your web browser etc?

**Comment by photopea** [comment] 2024-10-04 19:30
I have to close it because of lack of details :(

**Closed by photopea** 2024-10-04 19:30 UTC
