### ISSUE TITLE
Cant open brush tool

### ISSUE THREAD

**Issue by JUVKY** [photopea/photopea#6515] opened 2024-03-12 23:10 UTC
When i go to the brush tool then the tab to change the brush it can not open, the rest of the app is working fine

**Comment by MagicMoc54** [comment] 2024-03-12 23:23
Same here. Need a solution to this fast as I use this software for Graphic Design.

**Comment by zefelectro** [comment] 2024-03-12 23:30
Looks like the code for opening tool windows is having some trouble. I can confirm it was working successfully in my previous use 12 hours ago.

Some things not working (tested in Chrome and Edge):
- Changing brush size (from the toolbar, or from right-click.....nothing shows).
- Other kinds of "open a tool window / a slider window". Eg. The arrows for opening sliders, to change brush opacity or feather px.
- Opening the font tool from the toolbar.

**Comment by photopea** [comment] 2024-03-12 23:58
I am very sorry, it should be fixed now. Just clear your cache.

**Comment by JUVKY** [comment] 2024-03-12 23:59
Thank you

**Closed by photopea** 2024-03-12 23:58 UTC
