### ISSUE TITLE
The cmd key on the mac (FF browser) has stopped working

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#763] opened 2018-06-18 09:03 UTC
As in the title. Any of shortcuts with cmd button doesn't work (cmd + a, cmd + z, etc.)

Ctrl + "any key" work good - but Mac users doesn't use ctrl :)

OS - High Sierra, El capitan.
Browser - newest Firefox.
Polish keyboard

**Comment by photopea** [comment] 2018-06-18 09:16
Hi, could you do a little experiment for us?

Please, go here, click on the bottom right area, and press some keys: http://jsfiddle.net/p45f44zb/14/  It should show all keys, that are pressed at the moment.

What you see when you press Command? Is it "MetaLeft" or "OSLeft"?

Can you try shortcuts with Alt with different order of keys? Does it happen, that after you release all keys, you still see, that some keys are pressed?

**Comment by MichalSZZ** [comment] 2018-06-18 09:31
In FF - "OSLeft"

In Chrome, Opera and Safari - "MetaLeft"

When I make many combination (on this jsfiddle page), then some of keys didn't disappear after all keys are released. They are still showed...

**Comment by photopea** [comment] 2018-06-18 09:38
Ok, thanks. I just gave the "OSLeft" the same meaning as "MetaLeft", so it should work now.

Could you please find specific shortcuts, that leave a "pressed key" after you release all keys? Do they work similarly in all browsers, or just in FF?

**Comment by photopea** [comment] 2018-06-18 09:53
Can you go here http://jsfiddle.net/p45f44zb/14/  and find key combinations, which leave pressed keys?

**Comment by MichalSZZ** [comment] 2018-06-18 09:55
cmd + z for example :)

**Comment by photopea** [comment] 2018-06-18 10:16
Is it every combination, that contains Cmd? Is it the same in every browser? I am not sure, if I should report it to Mozilla or to Apple.

**Comment by photopea** [comment] 2018-06-18 10:39
Photopea should work exactly the same as 3 months ago (I fixed the problem with Command in Firefox). Is there anything what works differently in Photopea than 3 months ago?

**Comment by MichalSZZ** [comment] 2018-06-18 10:58
> I fixed the problem with Command in Firefox
Thanks. Works good now :)

> Is there anything what works differently in Photopea than 3 months ago
Now I see only that bug with cmd + something (on Mac only), that makes some keys looks like that they are still press. I'm pretty sure, that 2 weeks ago, that bug doesn't appear to me
With ctrl, shortcuts works good (but I prefer to use cmd like in other programs on mac).

**Comment by MichalSZZ** [comment] 2018-06-19 21:52
Should I make new issue for a second bug? Today another (3th) friend with Macbook told me, about bug with keys pressed and problems in work with Photopea (FF and Chrome). Photopea (and keyboard shortcuts) worked good for her before.

On this site http://jsfiddle.net/p45f44zb/14/ i can prepare situation, when it looks like that 4 keys are pressed in one time (but for real - any of they arn't in use). To undo one of (fake) pressed state, I must hit again that button with or without cmd.

I can make video with that problem using phone (showing keyboard and jsfiddle result on screen) to show more clearly this bug. My english isn't so good to explain everything here :)

**Comment by photopea** [comment] 2018-06-19 21:59
But only letter keys remain in the text area, right? Command is always removed, when you release it.

So maybe we can "reset" all keys artificially, after the Command is released. What do you think?

**Comment by MichalSZZ** [comment] 2018-06-20 06:09
Please try to make this patch. This is my only hope...
Today I have practical exam with my students (making graphic in Photopea), and I even have trouble to make 2 exercises for them in Photopea...

**Comment by photopea** [comment] 2018-06-20 06:40
Hi Michal,

ok I am very sorry. I just noticed, that the "old" Photopea (a month ago) contained a code, saying, that if Command key is released, all keys should be reset (because Browsers can not detect key release, when Command is down).

I didn't notice this part and did not transfer it, when changing the Keyboard handling mechanism. I just fixed it and Photopea should work at least as good as a month ago now.

Thank you very much for your hard work and your patience! Let me close it now :)

**Closed by photopea** 2018-06-20 06:40 UTC

**Comment by photopea** [comment] 2018-06-20 09:19
Sorry, I did not fix it properly :( now it should be fixed.

**Comment by photopea** [comment] 2018-06-20 09:20
I am very sorry for all this. All this was caused by a really big change in the core of Photopea. I am sure we will not have to do such changes ever in the future. So things should only improve from this point.

**Comment by MichalSZZ** [comment] 2018-06-20 09:38
Now I think it works OK. Most of my students have Windows, but this bug on Macs was frustrating for me.
Thank you again!
