### ISSUE TITLE
Unresponsive when trying to name 2 layers the same thing

### ISSUE THREAD

**Issue by nickolasjadams** [photopea/photopea#3323] opened 2021-05-29 18:10 UTC
I accidently tried to name a second layer the same as another.  
It wouldn't let me rename it or exit the renaming action.
I tried naming it something else. I tried renaming the other layer. 
Now a lot of stuff isn't working. 
![image](https://user-images.githubusercontent.com/15788998/120080563-c6dd5500-c076-11eb-986a-7de2c4fc0a6e.png)

**Comment by photopea** [comment] 2021-05-29 18:38
Hi, what should I do to make this problem on my computer? I tried naming two layers the same, but it works well.

**Comment by photopea** [comment] 2021-05-31 08:37
I have to close it because of lack of details.

**Closed by photopea** 2021-05-31 08:37 UTC

**Comment by nickolasjadams** [comment] 2021-06-01 01:15
I'm not sure what I did to break it.  Should have investigated more before opening an issue. Sorry!

**Comment by photopea** [comment] 2021-06-01 06:40
It would be really useful if you try to reproduce an issue right after it happens, while you still remember, more or less, what you did :)
