### ISSUE TITLE
New PhotoShop Remove Tool

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5516] opened 2023-04-09 15:38 UTC
I saw this video today about a new PhotoShop Remove Tool that is in Beta. It is super impressive. I thought I would share it with you so that you could see what was coming from your biggest competitor. Use this as a goal to try to achieve with your tools. Along with the video, there is a blog post from an Adobe designer describing how the tool works.

Additionally, at the end of the video, the presenter uses the Content-Aware Fill option where he tells PS to ignore parts of the image when considering what to fill with. That is SUPER powerful. I would LOVE to see that option implemented in Photopea.

Video:
https://youtu.be/dSrhB4e5DW0

Blog Post:
https://community.adobe.com/t5/photoshop-beta-discussions/remove-tool-in-beta-for-photoshop-desktop/td-p/13694923

**Comment by photopea** [comment] 2023-05-06 13:08
I have implemented it. When you choose a "Spot Healing Brush Tool", there are two buttons at the top - "Heal Selection" and "Remove with AI".

It is bad at generating faces, but it can generate missing parts of the object quite well. See here:

![image (1)](https://user-images.githubusercontent.com/15955558/236625678-ed0f9b30-573d-4db0-b9de-7ad9678cc556.gif)

I use the Dezgo API. Each click on this button costs me $0.002, so if it is clicked 100k times a day, it will cost me $6,000 a month. That is why I limited clicks to 1 per minute for non-Premium users.

The maximum area is limited to 250,000 pixels (e.g. 500x500), so it can not remove large objects (larger areas cost significantly more, e.g. 1 million pixels for 10x the price - $0.02).

**Comment by photopea** [comment] 2023-05-06 14:17
I switched to a newer model, which is better at making faces (but made only blondes this time).

![ynews-peabody-curators-srgb (1)](https://user-images.githubusercontent.com/15955558/236629542-8bc91dee-6d86-45bf-8f35-2d82798c027d.gif)

**Comment by camoody1** [comment] 2023-05-06 19:59
Wow. Yeah. This is pretty amazing. Checkout this test image I just messed with.

Before
![Reddit Help - black skirt 2 (1)](https://user-images.githubusercontent.com/73725653/236644228-eaa4c8b7-9495-4063-8bc8-f16208cabd35.png)

After
![Reddit Help - black skirt 2](https://user-images.githubusercontent.com/73725653/236644238-618d3540-7bc1-4e5f-85f7-8a8e3c26e018.png)

**Comment by camoody1** [comment] 2023-05-06 20:01
The 500x500 limitation could be tricky to work with, but I completely understand your budget needs.

Really great stuff, Ivan.

**Comment by photopea** [comment] 2023-05-06 22:20
I could make the interface similar to the Spot Healing Brush (paint to remove). 

Maybe we could accept areas of a million pixels (e.g. 1000x1000) by scaling them down 2x, sending small images to Dezgo, and scaling them up 2x at Dezgo. It is hard to tell what the quality would be. It would be only 30% more expensive instead of 900% more.

**Comment by camoody1** [comment] 2023-05-07 00:41
I think painting like the Spot Healing brush would be a great change.

I think trying the scaling option would be nice. We're dealing with such a small image at that point, that I can't imagine it could mess up too much in scaling. Definitely worth a try. Maybe do a check on the selected area before downscaling it though... if the area is under 500x500 - no scaling... if it's over 500x500 - do the scaling.

**Comment by Kryptortio** [comment] 2023-05-07 04:29
If a payed API becomes an issue [Stable horde](https://stablehorde.net/) could be a fallback it can be called for free [directly from a browser](https://aqualxx.github.io/stable-ui/) but it will be a bit slower unless you add an [API](https://stablehorde.net/api/) key (ideally with some "[kudos](https://dbzer0.com/blog/the-kudos-based-economy-for-the-koboldai-horde/)") or if you have a [worker node](https://github.com/db0/AI-Horde-Worker) where you can give yourself priority (or all Photopea users if they use a shared default account).

**Comment by camoody1** [comment] 2023-05-07 13:35
> @photopea FYI: As of this morning, I am being prompted to wait a full minute before being able to repeat an AI call to the Dezgo API - even though I am a Premium member. I don't think this was your intention.

NEVERMIND 😂
Apparently, my Premium account expired last night. I was thrown off by the European dates in my account. 😂

**Comment by camoody1** [comment] 2023-05-07 15:08
I was just looking at the Dezgo API online documentation, again. May I ask you a question? With this new removal process, what information are you sending to the API? Their online documentation says that you need to include the original image, a masked area, and text describing what you want to be placed into the masked area. Obviously, you aren't prompting users for text describing our desired changes, so how are you doing the call? Just curious.

**Comment by photopea** [comment] 2023-05-09 20:47
I deleted everything and added a new tool: "Magic Remove", it is below the Healing Brush tool.

Basically, it is a Lasso, with a "Remove" button at the top. You can also specify the new content of the area with a text description. It can handle areas of up to 1 million pixels now (e.g. 1000x1000).

@bluep55 I have entered "empty meadow" and it worked quite well
![image (4)](https://github.com/photopea/photopea/assets/15955558/6033e471-4ece-47ee-ae8d-851a3414c4f2)

**Comment by camoody1** [comment] 2023-05-10 03:05
This is REALLY great, Ivan! Well done! Any chance we could get a "Clear" or "Reset" button next to the new text field?

Great Inpainting like this is super powerful once you learn how to write good prompts. Love it.

**Comment by photopea** [comment] 2023-05-10 08:47
You can apply this several times to the same area, there is no need to do a step back.

**Comment by camoody1** [comment] 2023-05-10 17:22
> What should "Clear" and "Reset" do?

Clear or Reset would clear whatever you've typed into the "Remove" box. And, actually, it would probably be better to rename the "Remove" button to "Replace" since that's actually what you're doing. Heck, maybe "Remove/Replace" is better. And finally, since a longer, more detailed prompt for that tool will give a better result, it may be better to replace that small type box with a larger multi-line type box so that it's possible to see the entire prompt you've typed in, instead of having to scroll back and forth to read it all. It's such a powerful option, I think it deserves a nice GUI interface. 😁

**Comment by camoody1** [comment] 2023-05-10 22:16
This is so great 😆
![20221021_174940 (1)](https://github.com/photopea/photopea/assets/73725653/0fd0a0bf-a2ae-4339-8533-cc3a018106e2)

**Comment by photopea** [comment] 2023-05-11 19:17
Maybe we should rename it from "Magic Remove" to "Magic Replace".

E.g. here: www.photopea.com/#i4mWds8Rz.psd  the content-aware fill works much better than the AI Remove, and we are not paying anyone.

**Comment by camoody1** [comment] 2023-05-11 22:56
Yeah, both tools worked really well for me on the sample project you provided. But you're right... The Content-Aware Fill definitely still has its place for more simple areas. You could maybe move the new AI tool to its own section (maybe just give it its own window called "Inpainting") so fewer people will use it needlessly.

To get more people interested in Content-Aware Fill (and to save you some money),ci think you could do a few things:
1. Under the Healing Tools section, add a new "Content-Aware Fill" tool button. Make it work just like the current AI Heal tool works where you lasso an area to fill and then click a fill button. But in addition to that...
2. In order to make people, like myself, really prefer the Content-Aware Fill tool, it needs to be better about what parts of the existing image it pulls from when filling. The existing Content-Aware Fill tool often uses parts of the existing image that are just completely wrong for the area we're trying to fill. And that results in a terrible fill. I know myself and others have opened requests to get Photopea to match Photoshop with their tool where they allow the user to specifically choose with areas of the existing image to use when filling the selected area. I'm sure you know what I'm talking about. Allowing the user to tell Photopea which parts of the image to use when filling an area would make Content-Aware Fill a much more powerful Remove tool. Then, I wouldn't be nearly as likely to use the new AI Inpainting tool to perform a simple remove - and that would save you money.

**Comment by photopea** [comment] 2023-05-11 23:23
Yes, I know about this feature of Adobe Photoshop. But I simply dont know how to make it. Adobe did not publish the source code of Photoshop :( You could just as well show me a Falcon 9 rocked and ask me to build a similar one, but I dont know how.

**Comment by camoody1** [comment] 2023-05-11 23:34
Check this out. I bet this is how they cheat it. I bet you could do a similar cheat by letting us choose the areas we want to select from, turning that into a "mask layer" as seen here, and then applying your Content-Aware Fill.

The important section is between 2:32 and 4:20...
https://youtu.be/VvIF0eOg25k

**Comment by bluep55** [comment] 2023-05-12 10:03
Something pretty similar here using a mask layer:
https://www.youtube.com/watch?v=d-iYe3ZIEb8

**Comment by camoody1** [comment] 2023-05-12 10:24
@bluep55 Yes, exactly. Unfortunately, I tried this cheat in Photopea and it didn't work for me. It looks like Photopea pulls from All Layers to determine its fill, instead of just the available pixels on the current layer. So, that's something else that would need to be changed. It would be a great change, but I have no idea how involved it would be.

**Comment by bluep55** [comment] 2023-05-12 11:09
That's a big shame, it works fine in Photoshop.

**Comment by bluep55** [comment] 2023-05-13 11:08
I have a very old version of Photoshop ( pre CC ) and the method used in the video works perfectly as shown.
https://www.youtube.com/watch?v=d-iYe3ZIEb8.
Being able to select separate areas of the image and just have those areas in the mask to use as an analysing source ( shown from 3.40 onwards ) completely transforms the Content Aware tool.
If possible, It would be great if this could be implemented into Photopea.

**Comment by Pt-home** [comment] 2023-05-13 14:38
Magic substitution is fine, of course ... Another would be a guarantee of repeating the result for a similar request)))

**Comment by camoody1** [comment] 2023-05-14 04:19
People are loving the new AI Inpainting Tool.
https://youtu.be/g0zKzAo595U

I think we can make it even more powerful by providing more tool options to be passed to the API:
1. Prompt
2. Negative Prompt
3. Model
4. Guidance (optional)
5. Sampler (optional)

You could have a button in the top tool bar (instead of the current text field) that would open a new popup window with all of these options. Maybe call the window "Inpaint/Replace Options". And change the current "Remove" button to "Replace". Probably should change the current tool name from "Magic Remove" to "Magic Replace" so people have a better idea of what to expect.

Adding an options window like this would even allow you to give the option between Text-to-Image and Image-to-Image, since Dezgo provides both API calls at the same price (I think). This could allow people to draw a very basic idea of what they want to appear and then let the AI make it pretty. This would be SUPER powerful and not that much more involved to add since the API is so similar and going to the same provider.

**Comment by gse123** [comment] 2023-05-14 05:01
I just want to leave feedback to say that I think this is an incredible feature to have in Photopea, and in my opinion the simplicity of its current state is what makes it so appealing to all. I just did a video about it on my youtube channel and people seem to be really loving it. https://youtu.be/X_jRqH0eKtE 

So thank you Ivan for implementing such a great tool so well! 

My only comment would be to change the icon so it is somehow not identical to the lasso tool, but that is a small nit-pick.

**Comment by camoody1** [comment] 2023-05-14 05:35
@gse123 Yes, your video is the one I linked in my comment above.

We can still have a "simple" version for those who don't want to use the more powerful options, but there's no reason to limit the power of the tool to others who might want to dig into the more advanced options. Everything is difficult until we learn how to use it. 🙂

**Comment by photopea** [comment] 2023-05-14 22:55
@bluep55 I have implemented this feature! If a layer has a mask, the content-aware fill will use only non-masked areas as a source of new content.

**Comment by photopea** [comment] 2023-05-14 23:31
I have renamed the tool to "Magic Replace" and added a little star to a lasso icon. Now, there are two buttons, "Remove" and "Replace". "Remove" has a very high chance of removing the object :D

Here is the original image, "Remove", and "Replace" with a prompt "parrot" (or try it here www.photopea.com/#isFPtqRhW.psd).

![original](https://github.com/photopea/photopea/assets/15955558/16fe390c-6806-46b3-a734-05ea8b5601f4)
![remove](https://github.com/photopea/photopea/assets/15955558/b8048707-3de3-4f5b-8e06-cf5098772656)
![Background](https://github.com/photopea/photopea/assets/15955558/b127048d-6483-4cc1-883a-9dce8851bf48)

**Comment by MichalSZZ** [comment] 2023-05-15 06:36
> I just want to leave feedback to say that I think this is an incredible feature to have in Photopea, and in my opinion the simplicity of its current state is what makes it so appealing to all. I just did a video about it on my youtube channel and people seem to be really loving it. https://youtu.be/X_jRqH0eKtE
> 
> So thank you Ivan for implementing such a great tool so well!
> 
> My only comment would be to change the icon so it is somehow not identical to the lasso tool, but that is a small nit-pick.

I want to say that your videos are amazing and you have the best Photopea's Channel on YT. Good job!

**Comment by MichalSZZ** [comment] 2023-05-15 06:43
> I have renamed the tool to "Magic Replace" and added a little star to a lasso icon. Now, there are two buttons, "Remove" and "Replace". "Remove" has a very high chance of removing the object :D
> 
Excellent! We talked about AI in Photopea a year ago and now - your software jumped to the next level. Even if this costs some money - it is the perfect form of advertising. People will talk about it, more YouTubers will create engaging videos and more people will use Photopea in the future.

**Comment by gse123** [comment] 2023-05-15 07:17
> > I just want to leave feedback to say that I think this is an incredible feature to have in Photopea, and in my opinion the simplicity of its current state is what makes it so appealing to all. I just did a video about it on my youtube channel and people seem to be really loving it. https://youtu.be/X_jRqH0eKtE
> > So thank you Ivan for implementing such a great tool so well!
> > My only comment would be to change the icon so it is somehow not identical to the lasso tool, but that is a small nit-pick.
> 
> I want to say that your videos are amazing and you have the best Photopea's Channel on YT. Good job!

Thank you! Much appreciated :)

**Comment by gse123** [comment] 2023-05-15 07:18
> I have renamed the tool to "Magic Replace" and added a little star to a lasso icon. Now, there are two buttons, "Remove" and "Replace". "Remove" has a very high chance of removing the object :D
> 
> Here is the original image, "Remove", and "Replace" with a prompt "parrot".
> 
> ![original](https://user-images.githubusercontent.com/15955558/238214613-16fe390c-6806-46b3-a734-05ea8b5601f4.jpg) ![remove](https://user-images.githubusercontent.com/15955558/238214618-b8048707-3de3-4f5b-8e06-cf5098772656.jpg) ![Background](https://user-images.githubusercontent.com/15955558/238214621-b127048d-6483-4cc1-883a-9dce8851bf48.jpg)

Great additions! Looks like i'll be making an updated Youtube video soon then! :)

**Comment by photopea** [comment] 2023-05-15 08:13
@gse123 your video is amazing! If I knew someone is going to make a video, I would think it through more (the name, the interface, etc)! :)  It usually takes a week or two for a new tool to "settle down"

We can also add the "evolve" feature. Right now, the "Replace" forgets the old content and invents the new content. But "Evolve" could "develop" the old content according to your text (i.e. build on top of the old content).

**Comment by camoody1** [comment] 2023-05-15 08:25
> We can also add the "evolve" feature. Right now, the "Replace" forgets the old content and invents the new content. But "Evolve" could "develop" the old content according to your text (i.e. build on top of the old content).

Would you use the Image-to-Image option that they offer for this functionality? Is that what you're thinking? Because that would be great. Also, add in some "Advanced" options to allow for Negative Prompts, Model to be used andaybe even a Guidance slider like Dezgo shows on their sample pages. I like that a lot. Very helpful.

**Comment by bluep55** [comment] 2023-05-15 10:51
> @bluep55 I have implemented this feature! If a layer has a mask, the content-aware fill will use only non-masked areas as a source of new content.

Brilliant. Works perfectly now. Thank you 👍.

**Comment by camoody1** [comment] 2023-05-17 07:28
I've been playing around with the new Content-Aware Fill changes you made that allows us to exclude parts of a layer from the content sample by masking them out.  It's great that this is now available to us as an option, but unfortunately, it is very cumbersome process to actually use. If you want people to actually use the Content-Aware Fill option instead of the new Magic Replace tool, the process to exclude parts of an image has to be made much simpler.

Here is my vision for how it should work now that you have made the base ability.

1. Add a new tool listing under Edit -> Fill - Stroke - **Content-Aware Fill**.

2. When a user clicks on this new tool option, a new separate pop-up window opens, similar to the current perspective tool or the Magic Cut window.

3. (Option 1) This window will have an image of the fully merged project (ie. all visible layers will be appear as one layer). You would create a temporary merged layer for just this purpose and then delete it once the process is complete.
  (Option 2) This window will include ONLY the layer on which the user has chosen to perform the Content-Aware. Fill.
  (You choose whichever option makes the most sense. I'm leaning towards Option 2 for simplicity sake. The user could merge the layers themselves, I suppose, if they wanted to work use them all in the fill process.)

4. On this new window, the user will select the area to be filled using any of the Select tools available in Photopea. If they already had an area selected prior to clicking the new "Content-Aware Fill" tool, this selection should be brought forward into this window if possible.

5. After making their selection, the user clicks a "Test Fill" button and Photopea performs an initial Content-Aware Fill process using all "available" pixels in the image.

6. If the user does not like the result of the fill, they can choose a new "Exclude" tool that works like an opaque brush they use to paint over areas of the image they want to exclude from the fill possibilities. These excluded areas would be considered "masked areas" by your code and no longer used in the Content-Aware Fill process.

7. The user then clicks the "Test Fill" button again, repeating this process until they are happy with the fill they have achieved.

8. Once they are happy with the fill, the user clicks an "Accept Fill" button that accepts the change and returns them to their main project window. 

This process would be much easier than the current convoluted process and would be very similar to what is currently available in Photoshop. I think this would make the Content-Aware Fill tool a much more viable option going forward.

**Comment by photopea** [comment] 2023-05-23 15:15
@gse123 Hey, could you make a short "fast" video showing off the Magic Remove in Photopea, with no voice, just a sound? Similar to this video: https://www.linkedin.com/posts/scottbelsky_generative-fill-a-new-superpower-integrated-activity-7066768438181916673-aFGW  . I would like to promote this feature on our social networks, but I never did any video editing.

You can get in touch with me at support@photopea.com

**Comment by photopea** [comment] 2023-05-26 14:24
I have added the "..." button into the Magic Replace. You can specify more options, if you are into these things :)

**Comment by camoody1** [comment] 2023-05-26 23:57
> I have added the "..." button into the Magic Replace. You can specify more options, if you are into these things :)

This is great, Ivan!
There's just one more outstanding option that you can easily add as a drop-list... the AI Model to be used. Dezgo has several and they occasionally add more. And I bet they would add additional models if we asked. 

Their current options are:
* Anything 3.0 (anime)
* Anything 4.0 (anime)
* Anything 5.0 (anime)
* Deliberate 2 (general)
* Dreamshaper 5 (general)
* Dreamshaper 6 (general)
* Epic Diffusion 1.1 (general)
* Stable Diffusion 1.4 (general)
* Stable Diffusion 1.5 (general)
* Stable Diffusion 2.1 (512px) (general)
* Vintedois Diffusion (simple, general)
* Waifu Diffusion 1.3 (anime)
* Waifu Diffusion 1.4 (anime)

If you wanted to limit the number of models available, you could choose to include the most up to date versions of the duplicate models as they should provide the best output of their type.

Well done!!
[bitmoji](https://sdk.bitmoji.com/render/panel/fc6258f1-bd24-443a-8e03-7962fb44e28f-33290fb4-ad75-46e6-8062-305f1f5378d9-v1.png?transparent=1&palette=1&width=246)

**Comment by photopea** [comment] 2023-05-26 23:59
These are Dezgo models for image generation, not for inpainting.

**Comment by camoody1** [comment] 2023-05-27 00:10
I guess I didn't realize they used different APIs. I see that ,now, on their website.

It looks like both API calls cost the same. Are you specifically choosing to not offer the text-to-image option? If you're not entirely against it, perhaps you could use these same options (with the addition of the Model and Seed) to replace your existing Text-to-Image tool on the sidebar. These options offer a much more powerful tool than what we currently have access to. Leave the Inpainting (Magic Replacement) option under the Healing section as you currently have it setup and replace the current Text-to-Image tool with these new sweet options.

![bitmoji](https://sdk.bitmoji.com/render/panel/4589eaa6-daaa-4cd1-a4a1-70f23db16ba1-33290fb4-ad75-46e6-8062-305f1f5378d9-v1.png?transparent=1&palette=1&width=246)

**Comment by camoody1** [comment] 2023-05-27 23:20
Something to consider...

Since these text-to-image prompts cost you money and since an improved interface with more options would probably lead to more people using these tools, you might want to consider putting the more Advanced options behind your "Premium Account" paywall. Every other text-to-image provider puts their best options behind a paywall. There's no reason to expect different from you.🤷🏼‍♂️

**Comment by Pt-home** [comment] 2023-05-28 05:23
> I have added the "..." button into the Magic Replace. You can specify more options, if you are into these things :)

Wait, why not add transparency with a blend mode too? This will also expand the variability of the tool. And according to the internal implementation, this is very logical;) It works for me and it turns out very interesting, by the way;)

**Comment by camoody1** [comment] 2023-05-28 09:33
> > I have added the "..." button into the Magic Replace. You can specify more options, if you are into these things :)
> 
> Wait, why not add opacity with a blend mode too? This will also expand the variability of the tool. And according to the internal implementation, this is very logical;) It works for me and it turns out very interesting, by the way;)

Excuse me for not understanding, but could you explain what you're talking about in more detail? I would like to try whatever you're talking about since you seem to like it. 😁

**Comment by Pt-home** [comment] 2023-05-28 10:15
> Excuse me for not understanding, but could you explain what you're talking about in more detail? I would like to try whatever you're talking about since you seem to like it. 😁

Hello. In my comment there is "a little easter bunny" for Ivan ;)) and it's about the implementation of the tool itself.

And any user can try it with the help of a powerful and versatile Edit-Fade tool. By applying Magic Displacement, you can reduce the transparency and change the blending mode, which in essence, for example, will allow a double exposure in two actions instead of three ... And Ivan can generally make this possible in one, adding transparency of the replacement and changing the need mode, if someone like it.

**Comment by photopea** [comment] 2023-05-28 11:09
I dont think the Magic Replace, or the Content-Aware fill need an option for the Opacity and the Blending Mode. But sure, it would be easy to add.

**Comment by xyzzart** [comment] 2023-05-29 16:23
Hey! JUst found out that new feature in Photopea. Trying to play around with it but unfortunately for me it wont generate things for me. im selecting the area ,adding the prompt but nothing showing up except some tiny changes of the background( what am i doing wrong? thanks

**Comment by camoody1** [comment] 2023-05-29 18:16
> Hey! JUst found out that new feature in Photopea. Trying to play around with it but unfortunately it wont generate things for me. im selecting the area ,adding the prompt but nothing showing up except some tiny changes of the background( what am i doing wrong? thanks

@photopea I sometimes have a similar issue where I'll select an area to replace with a detailed prompt and when I submit the request, I get the message that it's processing but then... nothing happens. It doesn't happen every time. In fact, it seems to happen more often when I select an object to be removed. Sometimes just nothing changes. I wonder if the API might be returning some error message that you aren't processing?

**Comment by photopea** [comment] 2023-05-29 19:58
It happened to me several times, too. Dont know what the problem is, as I can not reproduce it :( (make it happen on purpose). I just press the button again and it works.

**Comment by xyzzart** [comment] 2023-05-29 21:32
one more strange thing i met is when i try to add additional selection area using magic replace - so as a result i, getting gliched texture.same with the remove option
![image](https://github.com/photopea/photopea/assets/87940617/db71e45d-271a-4d30-9d58-345d6b84d5b1)

**Comment by photopea** [comment] 2023-05-29 22:21
Could you tell us what should we do to see it happen ourselves?

Maybe turn your selection into a channel (or a quick mask) and share your PSD with us?

**Comment by xyzzart** [comment] 2023-05-29 22:52
it seems like it work ok now. ive made multiple selections (with shift key pressed),but it looks like the ai wont generate small objects. it work only when the  area is quite big...also im getting lots of text even when it mentioned in a negative promt...and one more thing ,im struggling with a long prompt,i think the prompt field is too small( anyways that new feature is pretty awsome to play around with 
![image](https://github.com/photopea/photopea/assets/87940617/aea58bfd-c893-44f9-aeed-4eb1fa24a3b0)

**Comment by xyzzart** [comment] 2023-05-30 11:26
hello there! here i trying to add some vivid changes to the canvas, but i cant. it generates the text everytime^ it would be greeat to add some weights/power to the prompt/ also ben trying to generate on a new  blank transparent layer,but it comes out with a black background. any ideas ?
![image](https://github.com/photopea/photopea/assets/87940617/cea07d95-951f-4025-9782-af7ae0fb9f6d)

**Comment by photopea** [comment] 2023-06-10 19:40
@gse123 Hey, could you change the title of your Youtube video: replace "Magic Remove" with "Magic Replace"?

**Comment by gse123** [comment] 2023-06-10 19:46
> @gse123 Hey, could you change the title of your Youtube video: replace "Magic Remove" with "Magic Replace"?

Done! :)

**Comment by photopea** [comment] 2023-06-10 20:37
Perfect, thanks! :)

**Comment by photopea** [comment] 2024-01-03 22:29
I will close it now, it seems like this feature works quite well. 

The last problem is making it economically reasonable. Currently, free users have to watch a video ad to use the Magic Replace, but the ad covers only about 30% of the cost of this feature. I wish we could find a less expensive provider than Dezgo.

**Closed by photopea** 2024-01-03 22:29 UTC
