### ISSUE TITLE
page not responding

### ISSUE THREAD

**Issue by MBfinedesigns** [photopea/photopea#5364] opened 2023-02-12 02:45 UTC
Every time that I 'm working on a project it lags each time, due to this problem it slows my process down drastically! Please fix this issue fast and correctly!! Thank You!

**Comment by camoody1** [comment] 2023-02-12 03:02
How large is the project you're working on? I've been working off and on with projects all day and haven't noticed any lag on my end. 🤷🏽‍♂️

Could you be having either internet issues or PC lag? Have you tried running Photopea in Incognito Mode to make sure no browser extensions are slowing you down?

FYI... I'm just another user trying to help, not the developer.

**Comment by Priscila2023** [comment] 2023-02-12 20:40
The same thing is happening to me. I've tried everything, uninstalled some programs, updated the drivers, cleared the memory, used it in an incognito browser tab and nothing works. I don't know what the problem is and I would like to solve it because I'm going to lose a challenge on the course I'm taking. I couldn't even complete the first exercise of the classes, I'm very upset.

**Comment by photopea** [comment] 2023-02-12 20:55
Hi, what should I do to see such a problem myself? How can I make Photopea page not responding? Or at least record a video of how you do it.

**Comment by Priscila2023** [comment] 2023-02-12 21:44
What kind of problem would cause Photopea to show "page not responding"? Because I'm doing simple beginner projects in Photoshop. My notebook is a Samsung Book E20, does Photopea have any minimum configuration requirements? I would like to have more information to be able to solve the problem.

**Comment by photopea** [comment] 2023-02-12 21:55
Can you make Photopea not responding on purpose? If yes, how do you do it?

**Comment by camoody1** [comment] 2023-02-12 22:05
I'm having the same issue, now, too. Sounds like a massive internet issue. Are we all in the United States having this issue?

I was able to open the starting page, opened a project from my Photopea storage drive, and then everything froze. Couldn't click on anything.

**Comment by Priscila2023** [comment] 2023-02-12 22:08
> Estou tendo o mesmo problema, agora também. Parece um grande problema de internet. Estamos todos nos Estados Unidos tendo esse problema?
> 
> Consegui abrir a página inicial, abri um projeto da minha unidade de armazenamento Photopea e tudo congelou. Não foi possível clicar em nada.

I'm in Brazil and some of my classmates who are taking the same course as me are having the same issue

**Comment by Priscila2023** [comment] 2023-02-12 22:15
> Can you make Photopea not responding on purpose? If yes, how do you do it?

Why would someone cause a bug on purpose if we are trying to study or work?

**Comment by camoody1** [comment] 2023-02-12 22:17
He's asking if you can easily reproduce the issue and then give him the steps you're taking to create the problem. Because he's not seeing the issue on his PC. It's just a troubleshooting question.

**Comment by Priscila2023** [comment] 2023-02-12 22:19
> Ele está perguntando se você pode reproduzir facilmente o problema e, em seguida, fornecer a ele as etapas que está executando para criar o problema. Porque ele não está vendo o problema em seu PC. É apenas uma questão de solução de problemas.

Oh, I understand, I'll try to record the screen.

**Comment by Priscila2023** [comment] 2023-02-12 23:04
> Can you make Photopea not responding on purpose? If yes, how do you do it?

https://drive.google.com/drive/folders/1hJ0bpU3Wh0FesZEB_ykk3JPPt-dqK-Cy?usp=share_link

**Comment by photopea** [comment] 2023-02-12 23:26
I see that Photopea is slow in your case. But e.g. your last image is 6000 x 4000 pixels (24 million pixels), which is quite a lot to redraw several times per second.

How old is your computer? Could you update your web browser and disable all your browser extensions? Also, if nothing helps, could you press More - Use WebGL (disable it)? Does it help?

**Comment by Priscila2023** [comment] 2023-02-13 00:08
> I see that Photopea is slow in your case. But e.g. your last image is 6000 x 4000 pixels (24 million pixels), which is quite a lot to redraw several times per second.
> 
> How old is your computer? Could you update your web browser and disable all your browser extensions? Also, if nothing helps, could you press More - Use WebGL (disable it)? Does it help?

I think I've had this notebook for about 2 years. I will follow your instructions and come back here to reply.

**Comment by Priscila2023** [comment] 2023-02-13 01:42
> WebGL

I've updated Google Chrome, disabled extensions, disabled WebGL, restarted the notebook and it's still very slow.

**Comment by camoody1** [comment] 2023-02-13 02:04
@photopea This kind of slowness would be at the local device level, correct? It wouldn't be due to any internet slowness or high traffic issues?

I only ask because I've seen reports that Russian hackers have been DDOS attacking a lot of NATO countries today. I assume that might be causing traffic and lag issues on some European server farms.

**Comment by MichalSZZ** [comment] 2023-02-13 06:21
Mentioned Samsung E20 in the one of the configuration that I saw, has only 4GB of RAM. It is not so much for the project on so big canvas (~6000x4000px).

About DDos attacks. If Photopea loaded to your device and page opened normally - it shouldn't have nothing with 'page not responding' info from the browser. 

Some time ago I had the same problem with my students with old macbooks air. And sometimes even I (with better performance), have this info working on big canvas with many layers and hard to computing filters.

**Comment by photopea** [comment] 2023-02-13 08:39
The only explanation that I have, is, that I think your CPU (Intel Processor 5205U) is pretty slow. Single-core performance is about 3x slower than on my laptop. But even with that CPU, it should not be as slow as shown on your video.

Could you open "about://gpu" in Chrome and show us a screenshot of what you have there?

**Comment by Priscila2023** [comment] 2023-02-14 18:19
> The only explanation that I have, is, that I think your CPU (Intel Processor 5205U) is pretty slow. Single-core performance is about 3x slower than on my laptop. But even with that CPU, it should not be as slow as shown on your video.
> 
> Could you open "about://gpu" in Chrome and show us a screenshot of what you have there?

https://drive.google.com/file/d/1-pmJZ0ta17VgKcbWO-PBx9CIW5uUm6x7/view?usp=share_link

**Comment by photopea** [comment] 2023-02-14 21:42
That looks fine to me. So is it still that slow? Did you try to restart your browser / computer?

Also, could you check the process management in Windows? Are there any processes that drain the CPU?

**Comment by Priscila2023** [comment] 2023-02-14 23:04
> Isso parece bom para mim. Então ainda é tão lento? Você tentou reiniciar seu navegador/computador?
> 
> Além disso, você poderia verificar o gerenciamento de processos no Windows? Existem processos que drenam a CPU?

CPU usage is below 70%, I've done all sorts of disk cleanup, I've restarted my computer, I've run antivirus. I did everything and nothing worked, I'm starting to think that I won't be able to manipulate any high resolution image because whenever I try to edit an image it crashes or slows down.

**Comment by photopea** [comment] 2023-02-15 07:22
If you do nothing with your computer, the CPU usage should be 0%. Could you share a screenshot of what is using your CPU?

**Comment by camoody1** [comment] 2023-02-15 10:52
> If you do nothing with your computer, the CPU usage should be 0%. Could you share a screenshot of what is using your CPU?

To be fair, your CPU will always be doing "something" in the background. My CPU usage is never actually zero.🤷🏽‍♂️

**Comment by photopea** [comment] 2023-05-03 22:49
I have to close it because of lack of details. I think the persons computer is not powerful enough for the kind of work they are doing. 

If you are watching a Youtube tutorial where a program runs smoothly, it could be because their computer is 10x more expensive than yours.

**Closed by photopea** 2023-05-03 22:49 UTC

**Comment by Priscila2023** [comment] 2023-05-04 03:54
No problem, the pirated Photoshop is working just fine.

**Comment by camoody1** [comment] 2023-05-04 04:47
@Priscila2023 You're so edgy and brave. If you were fine with pirating, why even try using Photopea in the first place? Bye

**Comment by Priscila2023** [comment] 2023-05-04 05:45
I was trying not to use pirating but the site didn't work at all so I had
to resort to another option.

Em qui., 4 de mai. de 2023 01:47, 97Buckeye ***@***.***>
escreveu:
