### ISSUE TITLE
Eraser tool doesnt work

### ISSUE THREAD

**Issue by AzibK** [photopea/photopea#1951] opened 2020-02-27 10:33 UTC
Eraser tool doesnt work when I use it. Fix it thanks

**Comment by photopea** [comment] 2020-02-27 11:53
Hi, I just tried and it works for me. Are you sure you selected the right layer, when erasing?

**Comment by AeonCaptain** [comment] 2020-02-28 02:47
Reload the page, or if you don't want to lose your work, save the file as a .psd and open again after reloading. Always works for me.

**Comment by photopea** [comment] 2020-02-28 08:22
@AeonCaptain if you wound any bugs, which make you reload the page, please, try to find a way to reproduce these bugs, and report them to us :)

**Comment by photopea** [comment] 2020-03-02 20:44
I have to close it because of lack of details.

**Closed by photopea** 2020-03-02 20:44 UTC
