### ISSUE TITLE
HULU ads popping up nonstop

### ISSUE THREAD

**Issue by viizzzzz** [photopea/photopea#5709] opened 2023-06-03 01:14 UTC
HULU ads are recently popping up on my screen disrupting the project I'm currently working on. I've never experienced this behavior in the program before. I believe it is a bug since it is repeating nonstop. 
![image](https://github.com/photopea/photopea/assets/135396538/b9172505-9888-4d3a-bb8c-a1aff0b661c8)

**Comment by viizzzzz** [comment] 2023-06-03 01:20
😭

**Comment by TheRadicalDreamer** [comment] 2023-06-03 03:27
try opening photopea in incognito mode, and see if the issue is repeated

**Comment by photopea** [comment] 2023-06-03 10:06
All ads in Photopea should always stay on the right side. They should never cover the editor.

Where exactly are these ads? Is this a screenshot of the whole screen, or the part of a screen? Could you share a screenshot of the whole screen?

I think you might have browser extensions, which insert ads into Photopea. Does it happen when you turn off all your extensions?

**Comment by viizzzzz** [comment] 2023-06-03 16:42
I'm using Firefox and I have no extension installed. It filled the whole screen. When I click on the X button, it pops right up rapidly.

**Comment by viizzzzz** [comment] 2023-06-03 16:43
> try opening photopea in incognito mode, and see if the issue is repeated

ill try

**Comment by photopea** [comment] 2023-06-03 18:58
Could you open the address "about:addons" in Firefox and show us a screenshot of what you see there?

**Comment by viizzzzz** [comment] 2023-06-03 19:27
> Could you open the address "about:addons" in Firefox and show us a screenshot of what you see there?

sure

**Comment by viizzzzz** [comment] 2023-06-03 19:29
![image](https://github.com/photopea/photopea/assets/135396538/7eef4f7b-9f82-4fc4-a868-d11d2a8bb4a1)


> Could you open the address "about:addons" in Firefox and show us a screenshot of what you see there?

![image](https://github.com/photopea/photopea/assets/135396538/8e347df4-e975-4131-ac65-f5a619e5e2c5)

**Comment by photopea** [comment] 2023-06-03 21:07
I will report it to our ad partners. Does the ad still appear?

**Comment by viizzzzz** [comment] 2023-06-03 21:46
I don't know if it appeared again because now I don't see it popping up nonstop

**Comment by viizzzzz** [comment] 2023-06-03 21:51
but it pops up most

**Comment by viizzzzz** [comment] 2023-06-04 01:40
nvm it keeps popping up nonstop

**Comment by viizzzzz** [comment] 2023-06-04 01:40
its really annoying

**Comment by camoody1** [comment] 2023-06-04 05:34
@viizzzzz Seems to only be happening to you. Interesting. If there were happening to many users of Photopea, we would be seeing numerous similar tickets here and on Reddit. I hope you don't have some weird virus.

**Comment by photopea** [comment] 2023-06-04 09:18
where are you located?

**Comment by photopea** [comment] 2023-06-05 07:50
It should be fixed, no fullscreen ads should appear anymore :)

**Closed by photopea** 2023-06-05 07:50 UTC

**Comment by viizzzzz** [comment] 2023-06-06 01:50
thanks
