### ISSUE TITLE
Ctrl ++ Not Zooming on Chrome

### ISSUE THREAD

**Issue by pranaman** [photopea/photopea#56] opened 2016-06-28 23:16 UTC
Hi, 
Using W7, Chrome, all updated.

Opened a psd, pressed Ctrl ++, and Ctrl/Shift ++, no zoom. Same for Ctrl --

If I click View, Zoom In, it works. 

Am I doing something wrong with the keyboard? Any chance to activate the keyboard keys for zooming?

**Comment by photopea** [comment] 2016-06-28 23:50
Hi, that is strange ... do you see any errors in the web console?

**Comment by tomasnosek** [comment] 2016-06-28 23:56
Do you use the "+" in numeric block or alfanumeric (numbers in a row above letters)? If alfa, it might be caused by other keyboard language? Only guessing

**Comment by pranaman** [comment] 2016-06-29 00:49
I did, thanks for suggesting to use the numeric block. I tried it and it 
works!

Awesome! Thank you!


On 6/28/2016 4:56 PM, Tomáš Nosek wrote:
>
> Do you use the "+" in numeric block or alfanumeric (numbers in a row 
> above letters)? If alfa, it might be caused by other keyboard 
> language? Only guessing
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/photopea/photopea/issues/56#issuecomment-229219098>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ABiYNcCBJ4WiCyYRz05qfVhqBSnN46vEks5qQbS7gaJpZM4JAoPT>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by tomasnosek** [comment] 2016-06-29 00:58
np mate :)

**Comment by photopea** [comment] 2016-06-29 09:19
I am glad that we have figured it out :) So I am closing it for now.

**Closed by photopea** 2016-06-29 09:19 UTC
