### ISSUE TITLE
My file dissapears when changing Hue and Saturation

### ISSUE THREAD

**Issue by DEVX1** [photopea/photopea#1367] opened 2019-04-30 10:16 UTC
My file disappears when I change the Hue and Saturation. When I change the saturation and hue using the different colors specifically.

**Comment by photopea** [comment] 2019-04-30 19:52
Hi, do you change Hue using Image - Adjustments, or through an Adjustment layer? How large is your file?

The problem is, no matter what I do, it always works for me. I need to be able to reproduce your problem myself, to be able to fix it. Could you tell me more details?

**Comment by DEVX1** [comment] 2019-05-02 07:56
I used this file:
![Image of Fish](https://i.ibb.co/TmBtW35/IMG-0375.jpg)

And I used the Image Adjustments category for the image editing.
![Image of Hue](https://i.ibb.co/nwh1KGw/1.png)

When I change the Hue and Saturation using specific colors and not just the master class, my image disappears after a certain period of time. My entire screen goes black, and then the image disappears.

Before:
![Image of Picture before black screen](https://i.ibb.co/rMzJW0C/4.png)

After like 15-30 seconds:
![Image of Black Screen](https://i.ibb.co/34y82CN/2.png)

I have no clue why this is happening...

**Comment by photopea** [comment] 2019-05-02 08:49
I tried it myself on your photo with Master and other ranges, but it always worked :/ 

Can you update your OS or your browser? Or try the Incognito mode?

**Comment by DEVX1** [comment] 2019-05-02 08:54
Sure

**Comment by DEVX1** [comment] 2019-05-02 08:56
I updated my browser and I just tried Incognito. Maybe it's my school wifi blocking it?

**Comment by DEVX1** [comment] 2019-05-02 08:56
Forgot to mention that this is like the coolest image editing website ever!!!

**Comment by photopea** [comment] 2019-05-02 09:16
Photopea runs completely in your computer, so the internet can not block it in any way.

Could you do it again, and when it disappears, can you look into the web console and send me a screenshot? Here is how to get to web console: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by DEVX1** [comment] 2019-05-02 09:19
![S](https://user-images.githubusercontent.com/38556505/57066331-33d16580-6ccc-11e9-861a-6f9194fb350e.PNG)

**Comment by photopea** [comment] 2019-05-02 12:34
Hi, I think it may be fixed now. Can you try it again?

**Comment by DEVX1** [comment] 2019-05-02 13:53
Sure

**Comment by photopea** [comment] 2019-05-03 10:23
I believe it should be fixed now.

**Closed by photopea** 2019-05-03 10:23 UTC

**Comment by DEVX1** [comment] 2019-05-07 08:01
It is
