### ISSUE TITLE
Selektive Farbkorrectur (selective color correction

### ISSUE THREAD

**Issue by Awleo** [photopea/photopea#7446] opened 2024-12-28 06:17 UTC
Your Operating System: Windows 11
Your Web Browser: Microsoft Edge
The problem happens in the Incognito Mode, too: Only used normal mode

**This must be done to see the problem**
1. Go to www.photopea.com
2. ![screenshot photopea](https://github.com/user-attachments/assets/c1812308-147b-4bcf-a056-4b47b9652b0b)

**Comment by photopea** [comment] 2024-12-28 22:55
This is how it looks in my case (there should be a slider under each parameter).

Please, do not use any browser extensions if you don't know what they do! We usually do not respond to to people who allow random browser extensions to randomly modify Photopea, like you are probably doing.

![image](https://github.com/user-attachments/assets/33647170-2588-4b6b-b859-a9bbea975024)

**Comment by photopea** [comment] 2024-12-29 15:54
I will close it, as it is probably caused by browser extensions.

**Closed by photopea** 2024-12-29 15:54 UTC
