### ISSUE TITLE
how to make photo pea less laggy

### ISSUE THREAD

**Issue by alissahateslag** [photopea/photopea#5975] opened 2023-08-27 05:22 UTC

**Comment by camoody1** [comment] 2023-08-27 05:26
It sounds like you need to take a break and go for a walk. Perhaps go play with a pet. Or maybe read a book about how to properly speak to people you're asking assistance from. Do all of that and then come back here and ask nicely for help.

Have a blessed Sunday!

**Comment by alissahateslag** [comment] 2023-08-27 05:30
sorry i was talking to myself

**Comment by photopea** [comment] 2023-08-27 11:19
The lag is usually caused by an old hardware.

People watch youtube videos of photo editing, and are surprised that it is laggy when they do it. But the youtuber might be using a new $2,000 desktop, while you do it on a 15 year old laptop, or on a phone.

Maybe record a video and show us what is happening.

**Comment by photopea** [comment] 2023-08-29 19:31
I will close it now, as the person did not respond.

**Closed by photopea** 2023-08-29 19:31 UTC
