### ISSUE TITLE
Quando abro um arquivo ele demora carregar e fica todo desformado

### ISSUE THREAD

**Issue by alexialeitess** [photopea/photopea#5934] opened 2023-08-09 15:45 UTC
nao consigo abrir um arquivo e editar pois a tela fica toda desformatada sem as opções padrao 
<img width="1440" alt="Captura de Tela 2023-08-09 às 12 44 57" src="https://github.com/photopea/photopea/assets/141853229/69a3c0a1-62bd-433a-94b2-10ff224a53ad">

**Comment by camoody1** [comment] 2023-08-09 15:55
Your problem might be caused by a browser extension. Try the steps listed here and let us know how it works for you...
https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment] 2023-08-09 23:04
Try this: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment] 2023-08-29 21:14
I have to close it, because the person did not respond.

**Closed by photopea** 2023-08-29 21:14 UTC
