### ISSUE TITLE
Workspace goes down when using after some inactive time

### ISSUE THREAD

**Issue by spiatrenka** [photopea/photopea#39] opened 2016-06-09 12:06 UTC
Main workspace area goes down when using (opening inner layer in my case) after some inactive time. Screenshot in attach.
![screenshot_photopea_edited](https://cloud.githubusercontent.com/assets/11042465/15929131/bc35089c-2e53-11e6-840f-4d9008187572.png)

**Comment by photopea** [comment] 2016-06-09 17:04
Hi. It definitely looks wrong, there is probably some bug. 

Did it happen multiple times? Can you send me your PSD or steps how to reproduce it? What browser do you use?

**Comment by spiatrenka** [comment] 2016-06-13 11:16
@photopea 
Yes, this problem has happen several times in Firefox 46 on linux (ubuntu 14.04). Unfortunately I can't share with you my PSD file, but I can provide information that it has approx. 150 Mb size and inner layers. In my case this problem appeared when I tried to open inner layer after some inactive time (photopea was open in background tab). I'll try to provide you with more detailed steps for reproducing this problem when I face it again.

**Comment by photopea** [comment] 2016-06-13 11:22
That is interesting. You can also remove some layers from your PSD, or fill some layers with a constant color, and send me that "censored" PSD to support@photopea.com .

**Comment by photopea** [comment] 2016-06-22 22:34
I have to close it because of lack of additional details :(

**Closed by photopea** 2016-06-22 22:34 UTC
