### ISSUE TITLE
Image Resizing issue 

### ISSUE THREAD

**Issue by msutt3055** [photopea/photopea#6087] opened 2023-10-09 07:49 UTC
Your Operating System: Windows 10 
Your Web Browser: Chrome 
The problem happens in the Incognito Mode, too: Yes 

The image that I am attempting to resize is not showing but says that it is there once a file is created .

**Comment by photopea** [comment] 2023-10-09 08:21
What should I do to see this problem myself? You opened an image in Photopea and you can not see it? If yes, the problem is in seeing the image, not in resizing.

**Comment by photopea** [comment] 2023-11-06 16:51
I have to close it, because the person did not respond :(

**Closed by photopea** 2023-11-06 16:51 UTC
