### ISSUE TITLE
Intrusive Advertisement

### ISSUE THREAD

**Issue by yraropmet** [photopea/photopea#4674] opened 2022-05-27 11:42 UTC
Randomly, an enormous Facebook and The North Face ad pops-up and covers the whole screen, I can't do anything but turning on my adblocker.

**Comment by photopea** [comment] 2022-05-27 13:53
Can you confirm that it happens when you disable all your browser extensions?

**Comment by photopea** [comment] 2022-05-27 13:53
I think your extensions might be inserting these ads into Photopea.

**Comment by yraropmet** [comment] 2022-05-27 18:00
I have no extension except an adblocker and I had disabled it.

**Comment by photopea** [comment] 2022-05-27 22:34
Are you sure there were no extensions at about://extensions, when the fullscreen ad appeared? Could you show us a screenshot of about://extensions ?

**Comment by Uncommonly** [comment] 2022-05-28 09:24
I can confirm the same bug!! The North Face (and not the only one...) just pops up and takes the whole screen and stays there foerever - you can't close it because there's no "X" or whatsoever... It happens all the time with random pop ads that takes the whole screen and doens't give you option to close them!

I have NO browser extensions AT ALL!
Using Mozilla

**Comment by photopea** [comment] 2022-05-28 10:29
I have reported it to our ad provider. Could you share a screenshot of such ad?

**Comment by photopea** [comment] 2022-05-28 13:33
Our ad provider could not reproduce such ad in any configuration.

Could someone please share a screenshot of the ad, and also a screenshot of the list of your extensions? We had many users saying they have no extensions, while they did have extensions.

Websites can not disable extensions, but extensions can do anything they want to any website.

**Comment by Uncommonly** [comment] 2022-05-28 22:07
Cleared my cookies/cache for the website and that ad didn't showed up again. If it does, I'll share screenshot.

Thanks for your quick response!

**Comment by photopea** [comment] 2022-05-29 06:28
Ok, I will close it for now. Feel free to keep reporting issues!

**Closed by photopea** 2022-05-29 06:28 UTC

**Comment by Uncommonly** [comment] 2022-06-07 23:58
Ad showed up again. There's still no way to hide/close it.


![tnf](https://user-images.githubusercontent.com/66388900/172502890-d7a9d7e0-6364-4f55-b75e-69326b998a51.png)

**Comment by photopea** [comment] 2022-06-08 06:45
Or advertising partners have explicitly blocked all ads from The North Face a week ago.

Could you check your computer for viruses? Are you using the standard Firefox from the internet? Could you show us a screenshot of "about:addons" in your Firefox?
