### ISSUE TITLE
Lagging after opening PSD files

### ISSUE THREAD

**Issue by Just-Another-Black-Sheep** [photopea/photopea#2542] opened 2020-10-19 12:43 UTC
When I upload PSD files the site becomes super slow and if I try to make a PSD visible, it takes some time to appear.
And when PSDs are present other options are also lagging (like the text tool or the selective color layer for example)

It also takes ages for GIFs to save but while I know that they usually do take some time, the ones I’ve been trying to save recently are taking double their time than usual. They are the same dimensions and sizes I've used before so I already know how long it takes for them to save but again, it's taking more time than usual.

I’ve already cleared out my cookies/cache but that didn’t help and my ad-blocker is disabled on Photopea.
And the browser I'm using is Chrome.

**Comment by photopea** [comment] 2020-10-19 13:52
Is your WebGL on? Check in More - Use WebGL.

How large are your PSD files? What processor and RAM memory do you have? Maybe your computer is not powerful enough to work with large files.

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-19 14:22
> Is your WebGL on? Check in More - Use WebGL.
> 
> How large are your PSD files? What processor and RAM memory do you have? Maybe your computer is not powerful enough to work with large files.

1. My WebGL is on.
2. The largest PSD folder I have is 4.15 MB, individual PSD files range from 225 KB to 3 MB.
3. My RAM memory is 4,00 GB (3,60 GB is usable) and my processor is “AMD E1-1500 APU with Radeon(tm) HD Graphics 1.48 GHz”
I’m not sure if the issue is with my computer because the things I’m trying to do are the same things I did in the past, I’m using the same PSD files and dimensions and until last week everything was running smoothly.

**Comment by photopea** [comment] 2020-10-19 16:26
Are you using the same browser as before? Are you sure you did not update it or switched to Beta version?

Is it slow for all files, no matter what you try? If not, can you find some steps how could I reproduce it on my computer?

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-20 10:25
> Are you using the same browser as before? Are you sure you did not update it or switched to Beta version?
> 
> Is it slow for all files, no matter what you try? If not, can you find some steps how could I reproduce it on my computer?

Yes, I'm using Chrome (been using it for over a year for Photopea probably) and I'm positive that I didn't update it (I’m not sure if it maybe had an automatic update – websites and overall internet stuff aren’t exactly in my field of knowledge) and I’m also positive that I’m not using the beta version (didn’t even know it existed until now).
It’s the same situation for every file I normally work with, those being .jpg and .png images, plus GIFs. It all works smoothly until I upload and make the PSD file visible, the second I delete it all becomes normal again.

**Comment by photopea** [comment] 2020-10-20 10:53
By "upload" and "delete", do you mean Opening and Closing a document in Photopea?

What do you mean by "all works smoothly unitl ..."? Do you mean Photopea works smoothly with no documents opened?

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-20 11:14
I meant uploading-deleting a PSD layer/folder in a document/project. (I'm not exactly sure what terms to use for certain things, my apologies)

I meant that I'm able to use Photopea without it lagging until I upload a PSD file on the project, after that the website becomes slow when I try to use its features/options on that project (using the text tool, adding adjustment layers, using free transform on layers…) and returns back to its normal speed when the PSD is deleted from the project/document.

**Comment by photopea** [comment] 2020-10-20 11:18
What operating system (name and version) and what browser (name and version) do you use?

Can you disable all browser extensions and try it again?

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-20 11:44
Operating system: Windows 7 Home Basic, 64-bit version
Browser: Google Chrome, “version 86.0.4240.75 (Official Build) (64-bit)”

I’ve disabled my browser extensions but unfortunately nothing’s changed. (I’ve even tried turning off and on my laptop to see if that would make a difference but it’s still lagging after opening PSD files)

**Comment by photopea** [comment] 2020-10-20 11:46
Thanks! Can you maybe record a short video of what exactly is happening?

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-20 11:58
Unfortunately I'm not able to do that, the closest thing I could use for recording would be my phone's camera but it has such low quality that I really doubt you would be able to see anything :/

Is there maybe anything else I could do?

**Comment by photopea** [comment] 2020-10-20 12:04
I still dont understand what you are saying, so I hoped I would see it in your video :(

"I meant that I'm able to use Photopea without it lagging until I upload a PSD file on the project"

How exactly do you use Photopea without opening a PSD file? Do you mean opening a JPG file?

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-20 12:24
Okay so, I usually use Photopea for image editing, I open a new project and basically add other images until I get a final product. (I'll add an example)
I don't use Photopea to make PSD files, I just apply them on the final product.
Hope that makes sense…

![Picture1](https://user-images.githubusercontent.com/73115403/96585406-daa22b00-12df-11eb-9a45-dc00aac50435.png)

**Comment by photopea** [comment] 2020-10-20 13:02
I think it could be slow because you have too many files (with too many layers) opened at the same time.

So everything works correctly (only slowly), or  does anything work incorrectly? e.g. a black brush paints with white or something?

**Comment by photopea** [comment] 2020-10-20 13:09
When everything works slowly, can you create a new document 500 x 500 pixels and paint into it? Does it work fast?

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-20 13:21
> I think it could be slow because you have too many files (with too many layers) opened at the same time.
> 
> So everything works correctly (only slowly), or does anything work incorrectly? e.g. a black brush paints with white or something?

I’ve worked with multiple open folders in the past and even had over 30 layers on a file but I was still able to use PSDs on the file without the website lagging.
I’ve also tried to first make the final product, save it, close everything, open the final product and add a PSD but the website would still start lagging after that.

And yes, everything works correctly, the website just becomes slow.

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-20 13:22
> When everything works slowly, can you create a new document 500 x 500 pixels and paint into it? Does it work fast?

Even if everything slows down, it just lags on the project where the PSD is placed, so if I create a new project and don’t duplicate the PSD into it, it will work at the normal speed.

I’ve created a new project and painted into it and had no issues with that. But after duplicating the PSD into it, the lagging started. I deleted the PSD layer and was able to paint at the normal speed again.

**Comment by photopea** [comment] 2020-10-20 13:26
And what do you mean by "duplicating a PSD into it"?

**Comment by photopea** [comment] 2020-10-20 13:27
Can you send me your PSD file to support@photopea.com and tell me what should I do to do what you did?

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-20 13:32
![1](https://user-images.githubusercontent.com/73115403/96593018-55237880-12e9-11eb-8507-1cefba0cccee.png)
![2](https://user-images.githubusercontent.com/73115403/96593053-6076a400-12e9-11eb-93e8-6c022098e977.png)

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-20 13:32
> Can you send me your PSD file to [support@photopea.com](mailto:support@photopea.com) and tell me what should I do to do what you did?

Sure but I'm a little bit busy currently, can send it in an hour if that's alright.

**Comment by photopea** [comment] 2020-10-20 15:14
Hi, do you know what Adjustment Layers are? I think you are copying Adjustment Layers, and it is slow because of processing so many adjustment layers.

The PSD that you sent me has 40 Adjustment Layers.

I recommend you to learn about layers and folders, and that you can unfold a folder and see layers inside it: www.Photopea.com/learn/layers

Also, learn about adjustment layers: https://helpx.adobe.com/photoshop/how-to/adjustment-layer.html

I think Photopea did not become slow, you just started to work with a different PSD file (with more adjustment layers).

**Comment by photopea** [comment] 2020-10-20 15:51
I opened your PSD in Adobe Photoshop and enabled all layers, it started to lag, too. So I think it is technically impossible to redraw so many adjustment layers (tens of millions of pixels) several times a second.

If you want, you can record your screen and I will tell you, if it is more laggy than Photoshop or not. But otherwise, I am afraid there is nothing I can do.

**Closed by photopea** 2020-10-20 15:51 UTC

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-20 16:30
Again, I've been using the same PSDs that I've sent you for the last 8-9 months and never had any issues with them regardless of how much adjustment layers they have.

I've also talked to a friend who uses Photopea in the same way as I and they said that they too were experiencing lagging issues when uploading PSDs to Photopea. So including me, that's already three people who have the same issue (if needed I could see if any other folks who use Photopea for the same purpose as me have this issue.)

But if truly nothing can be done about this I guess I’ll just hope that the issue will go away by itself, I mean it did appear suddenly on its own so maybe it will disappear the same way.

Thank you for taking your time to go over this issue with me, I really appreciate it :)

**Comment by photopea** [comment] 2020-10-20 16:47
Please, try to record the lagging on video.

I would like to see, if it is the same as I experience in Photopea, or it is much worse and can be improved.

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-20 17:27
Alright, I'll try to take it tomorrow.

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-22 11:06
> Please, try to record the lagging on video.
> 
> I would like to see, if it is the same as I experience in Photopea, or it is much worse and can be improved.

Not sure why but I can’t post the videos so I uploaded them to my drive, hope you can get them from there; https://drive.google.com/drive/folders/1lNRFY1xFUMRIhnZ9KK3mY1sLp2iY5b-g?usp=sharing

I took one with a single layer and one with several layers and in order to get a comparison the beginnings of the videos don’t have PSDs and I added them half way through.
Though I’m not sure if you’ll be able to make out anything because of the low quality :/

**Comment by photopea** [comment] 2020-10-22 11:43
Hi, Photopea runs extremely slowly on your computer. Have you tried to put your laptop on a charger? Does it run faster?

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-22 11:50
My laptop generally needs to be on a charger, otherwise the battery immediately dies (though so far that has never been an issue when using Photopea).

**Comment by photopea** [comment] 2020-10-22 11:57
Could you send me a screenshot of what you see when you open "chrome://gpu/" in your browser?

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-22 12:29
![1](https://user-images.githubusercontent.com/73115403/96871534-b2970100-1472-11eb-862e-94936fd184b5.png)
![2](https://user-images.githubusercontent.com/73115403/96871548-b6c31e80-1472-11eb-9308-680d0f7262ac.png)
![3](https://user-images.githubusercontent.com/73115403/96871557-b9be0f00-1472-11eb-9261-b9f75a792080.png)
![4](https://user-images.githubusercontent.com/73115403/96871595-c80c2b00-1472-11eb-900e-7ad6531fad50.png)
![5](https://user-images.githubusercontent.com/73115403/96871608-cf333900-1472-11eb-9c64-3a82f238d29b.png)
![6](https://user-images.githubusercontent.com/73115403/96871621-d5c1b080-1472-11eb-9955-1e98ccb980b6.png)
![7](https://user-images.githubusercontent.com/73115403/96871629-d9553780-1472-11eb-8283-4e76b72f29ed.png)
![8](https://user-images.githubusercontent.com/73115403/96871648-de19eb80-1472-11eb-80f3-256d6d9f7aac.png)
![9](https://user-images.githubusercontent.com/73115403/96871662-e1ad7280-1472-11eb-899e-33e220179e04.png)
![10](https://user-images.githubusercontent.com/73115403/96871667-e540f980-1472-11eb-8837-7b70ea02eb73.png)
![11](https://user-images.githubusercontent.com/73115403/96871685-e8d48080-1472-11eb-9f54-002393911fe1.png)
![12](https://user-images.githubusercontent.com/73115403/96871699-ed009e00-1472-11eb-8507-33839ec2f1cf.png)

**Comment by photopea** [comment] 2020-10-22 12:38
Thanks a lot! So it says that you have no GPU acceleration, and the WebGL is actually running on the CPU (which is probably even slower than if we did not use WebGL at all).

The third image from the bottom says "Please update your graphics driver via this link" - can you click it and try to update it?

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-22 13:02
Is there a way for me to try and fix the first issue? Though if I'm being honest I'm not exactly sure what that means in the first place since, again, computers aren't my field of knowledge.

I checked the link but I'm not sure which version I'm supposed to choose.

![Picture1](https://user-images.githubusercontent.com/73115403/96875464-8631b380-1477-11eb-8f54-b7258c67ea93.png)
![Picture2](https://user-images.githubusercontent.com/73115403/96875478-89c53a80-1477-11eb-9351-c5ca155cb218.png)

**Comment by photopea** [comment] 2020-10-22 13:05
I would try the "Catalyst Software Suite"

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-22 13:26
Installed it, what now?
![Picture1](https://user-images.githubusercontent.com/73115403/96878253-e8d87e80-147a-11eb-80a3-de92e456a647.png)

**Comment by photopea** [comment] 2020-10-22 13:34
Your screen says "Installer Welcome", so you have to install it by clicking "Next >".

Once it is installed, look at "chrome://gpu", if there is "Hardware accelerated" at the top.

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-22 13:50
![Picture1](https://user-images.githubusercontent.com/73115403/96881192-4b7f4980-147e-11eb-9899-ec0590be6389.png)

**Comment by photopea** [comment] 2020-10-22 14:02
That is very strange. Can you try Photopea in Firefox? Maybe Firefox will accept your current drivers.

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-22 14:13
I had to give the laptop to my younger sister so I'll give it a try either in a few hours or tomorrow.

**Comment by Just-Another-Black-Sheep** [comment] 2020-10-23 10:10
> That is very strange. Can you try Photopea in Firefox? Maybe Firefox will accept your current drivers.

I've tried applying PSDs through Firefox and it's definitely less lagging then Chrome, I can definitely see it still being slow but compared to Chrome it's barely noticeable so I suppose I'll be using Firefox for applying PSDs from now on.

**Comment by photopea** [comment] 2020-10-23 10:18
I really don't know why Chrome stopped supporting your graphics card with the new release of Chrome 86. I will ask some google developers.

**Comment by photopea** [comment] 2020-10-23 15:44
So Chrome has disabled the support for your driver: https://chromium.googlesource.com/chromium/src/gpu/+/88041afb0a5c66c505dfde5512900881f4900ed9

You should try to download the new drivers here: https://www.amd.com/en/support/previous-drivers/apu/amd-series-processors/amd-a6-series-apu-for-laptops/a6-7310-radeon-r4-graphics .
