### ISSUE TITLE
Smart FIlter/Add Noise Doesn't Show When Exporting 

### ISSUE THREAD

**Issue by jaystatio** [photopea/photopea#3313] opened 2021-05-28 02:20 UTC
I've added noise to the picture, but when I export it into a file, the picture completely removes all the added noise. I've tried all  Formats (PNG, JPG, etc). Please help.

**Comment by photopea** [comment] 2021-05-28 06:38
Hi, I can not reproduce such behaviour. Can you send me a JPG or a PNG that you got out of Photopea, and a screenshot of how it looks like in Photopea?

**Comment by photopea** [comment] 2021-05-31 08:38
I have to close it because of lack of details.

**Closed by photopea** 2021-05-31 08:38 UTC
