### ISSUE TITLE
.ai file does not open

### ISSUE THREAD

**Issue by santosnahiara** [photopea/photopea#3624] opened 2021-07-29 21:13 UTC
I open an .ai file, the loading sign appears but then it says error. the file is 108 mb, and my computer is old, could that be the reason?

**Comment by photopea** [comment] 2021-07-29 23:22
It is hard to tell. Could you send me your .AI file to support@photopea.com ? Or do you have a smaller AI file, which can not be opened? Maybe the problem is the same in both files.

**Comment by photopea** [comment] 2021-08-02 13:22
I could not download the file from your link, that you sent. I will close it here, we can fix it over the email.

**Closed by photopea** 2021-08-02 13:22 UTC

**Comment by santosnahiara** [comment] 2021-08-02 13:53
Hi! Gmail won't let me attach it because it's bigger than 25 mb, maybe a
wetransfer?

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by photopea** [comment] 2021-08-03 10:13
Sure, send it to me any way you want :)

Just make sure, that if you open your link in Incognito window, a file can be downloaded.
