### ISSUE TITLE
issue with colour after opening on Photopea

### ISSUE THREAD

**Issue by SQ00000** [photopea/photopea#6343] opened 2024-01-23 01:55 UTC
Your Operating System: ?
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Upload the psd. file
3. psd. file opens in another colour

My original file looks like this:
<img width="946" alt="Screenshot 2024-01-23 at 9 45 29 AM" src="https://github.com/photopea/photopea/assets/157438496/d6faf88e-f0a7-42e0-9aac-98369b157408">

But when Photopea opens it, the colour is all wrong:
<img width="982" alt="Screenshot 2024-01-23 at 9 45 23 AM" src="https://github.com/photopea/photopea/assets/157438496/5a850456-ebe0-4f26-9691-1825e294a9e6">

I have previously use this file on Photopea before and the colour was okay, however today when i use it, the colour is off. I tried different laptop and browsers, and even re-saved my psd. file but nothing is working. Please help.

**Comment by camoody1** [comment] 2024-01-23 05:35
Are you possibly using the wrong Mode under Image? There's RGB and CMYK options.

**Comment by SQ00000** [comment] 2024-01-23 05:40
Both are in RGB mode.

**Comment by camoody1** [comment] 2024-01-23 05:42
Can you share a link to your project so we can see how it looks on our machines? You can share a project by clicking File -> Share -> PSD, then copying the link that pops up and pasting it here.

**Comment by SQ00000** [comment] 2024-01-23 05:51
Here you go: www.photopea.com/#iaZSmqItx

Kun Swee Qi

Senior Social Media Designer

T (65) 6460 9550 | M (65) 9786 4887

A 201 Henderson Road, Apex @ Henderson, #06-13/14 S159545
  <https://dailyvanity.com/> <http://avenueone.sg/>

**Comment by camoody1** [comment] 2024-01-23 06:06
@photopea Confirmed that this project appears different in Photopea vs Photoshop on my PC. Interesting

![image](https://github.com/photopea/photopea/assets/73725653/3106812a-82a4-4584-bbd5-3ca709606ba3)

**Comment by camoody1** [comment] 2024-01-23 06:20
@SQ00000 Try this for me...
1. Highlight all of your layers in the layers panels at the same time by clicking the top layer once then CTRL-Left-click the bottom layer.
2. Right-click on one of the layers and select "Duplicate into..."
3. From the popup box, choose "New" in the Destination drop box.

Now, switch to the new tab and see if the new image looks like the correct color. If it does, save that project, close it, and then reopen it to see if the colors stay correct.

**Comment by SQ00000** [comment] 2024-01-23 06:32
That works! But any idea why this is happening? It will be troublesome for
me to do this for all my project 😭

Kun Swee Qi

Senior Social Media Designer

T (65) 6460 9550 | M (65) 9786 4887

A 201 Henderson Road, Apex @ Henderson, #06-13/14 S159545
  <https://dailyvanity.com/> <http://avenueone.sg/>

**Comment by camoody1** [comment] 2024-01-23 06:34
No, sorry, I have no idea why it's happening. We'll have to let the Photopea developers look into it more. I'm just another user, like you, who saw your problem and wanted to see if I could help. This workaround will at least get you working again until the developer can figure out the problem.

**Comment by SQ00000** [comment] 2024-01-23 06:37
Oh I see, I thought you were one of their staff haha. Anw, thanks alot for
your suggestion, it's really helpful! Meanwhile, hope the developer can
figure out the problem.

Kun Swee Qi

Senior Social Media Designer

T (65) 6460 9550 | M (65) 9786 4887

A 201 Henderson Road, Apex @ Henderson, #06-13/14 S159545
  <https://dailyvanity.com/> <http://avenueone.sg/>

**Comment by camoody1** [comment] 2024-01-23 06:39
He won't be awake for a few more hours, but I'm sure he'll look into it as soon as he gets a chance.

Have a great day!

**Comment by SQ00000** [comment] 2024-01-23 06:39
Thanks, you too! :)

Kun Swee Qi

Senior Social Media Designer

T (65) 6460 9550 | M (65) 9786 4887

A 201 Henderson Road, Apex @ Henderson, #06-13/14 S159545
  <https://dailyvanity.com/> <http://avenueone.sg/>

**Comment by photopea** [comment] 2024-01-23 08:27
Sorry guys, it is fixed now.

Your PSD doesn't use the sRGB color space, and we modified our color space processor yesterday.

**Closed by photopea** 2024-01-23 08:27 UTC
