### ISSUE TITLE
Artboards - bug after using Ctrl+Alt+Shift+E on file from Photoshop

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#2890] opened 2021-02-17 22:43 UTC
It only happens in file with artboards that was made in Photoshop.

1. Open file with artboards maked in Photoshop (I have file from PS 2021)
2. Select the first layer in artboard group
3. Make Ctrl+Shift+Alt+E 
4. select any layer or group in that artboard and click RMB on layer name and make Smart object

All artboards disappear and on layers pallete there is only that layer or group (not as smart object)

**Comment by photopea** [comment] 2021-02-25 15:30
I am not able to reproduce it now. Can you still reproduce it?

**Comment by photopea** [comment] 2021-02-25 19:32
I will close it, as I think it is fixed, but feel free to let me know if it is not.

**Closed by photopea** 2021-02-25 19:32 UTC
