### ISSUE TITLE
PhotoPea Crashing

### ISSUE THREAD

**Issue by unknowntiny** [photopea/photopea#6926] opened 2024-06-30 05:55 UTC
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment] 2024-06-30 11:08
What should I do to see Photopea crash?

**Comment by Mezzatturr** [comment] 2024-07-01 07:23
Photopea crashing happens to be as well, however it’s not an issue with the site, it’s an issue with your RAM. I draw using photopea ALL THE TIME and i can confirm that the only reason it crashes is because that it tracks every action you do and it builds up over time putting more and more strain on your phone, tablet, whatever you use to draw.

Although the animated ads that refresh every 15 seconds don’t help, it’s a necessary evil to keep the awesome site going and this is what I do to fix it, but the unfortunate news is that if you are doing a complicated project with layers, this just wont work:

If you want to make crash back-ups (because progress is lost at times) save it as a PSD for the meantime. Then, at increments, export it as a PNG and put it back into photopea. This resets the RAM usage back to zero. I hope it helps.

**Comment by photopea** [comment] 2024-07-01 08:13
Interesting. What if we restricted the history to only e.g. five steps back? It should help with RAM, as the old states would not be saved in history.

If Photopea crashes, it is enough just to reopen it and you should see your old work.

**Comment by Mezzatturr** [comment] 2024-07-01 10:36
Yeah. Luckily Photopea’s autosaving seems to save most of the work however sometimes it will send me back a few steps. For some reason when your RAM starts to get particularly low, the site just starts to fail to function. Autosaving doesn’t work, hell one time it got so bad that I couldn’t even download a backup file and I got a literal popup saying “Not enough RAM” when i tried to save it as a PSD.

**Comment by photopea** [comment] 2024-07-01 11:15
How much RAM do you have? And what image resolution do you usually use?

**Comment by photopea** [comment] 2024-07-23 15:16
I have to close it because of lack of details :(

**Closed by photopea** 2024-07-23 15:16 UTC
