### ISSUE TITLE
0byte file

### ISSUE THREAD

**Issue by sjb-ai** [photopea/photopea#5422] opened 2023-03-04 08:27 UTC
I recently saved a file, My computer turned black. I was just about done with my project. I tried opening it, just to see its Zero bytes. This is a PSD file and I had constantly saved, Im trying to recover this file. I had spent about the entire day working on it so Any help would be amazing

**Comment by photopea** [comment] 2023-03-04 08:43
Why did your computer "go black"? A website should not be able to turn off your computer. Could you update your OS or your web browser?

**Comment by sjb-ai** [comment] 2023-03-04 16:04
They are both updated, Im not sure why this happened. I just need to recover this file

**Comment by sjb-ai** [comment] 2023-03-04 16:30
And the computer didn't reset

I was saving and the screen turned black for like a few seconds. When it turned back on, nothing was showing on photopea and the saved file was 0bytes

**Comment by photopea** [comment] 2023-03-04 21:12
It looks like a bug with the file system API. Your web browser crashed, because there was not enough RAM memory for the kind of work that you do. And Chrome deleted a file in order to write a new file (which never happened because of the crash). We have been discussing with the Chrome team to fix it, but they did not do it yet.

When you work with such large documents (and there is a probability of a crash), use File - Save as PSD to save it as a new copy (instead of rewriting the old file).

**Comment by camoody1** [comment] 2023-03-04 21:23
> It looks like a bug with the file system API. Your web browser crashed, because there was not enough RAM memory for the kind of work that you do. And Chrome deleted a file in order to write a new file (which never happened because of the crash). We have been discussing with the Chrome team to fix it, but they did not do it yet.
> 
Wooooow. This sucks.

**Comment by sjb-ai** [comment] 2023-03-04 22:15
Thank you for the advice, Im hoping the chrome is able to fix it soon

**Comment by photopea** [comment] 2023-03-06 11:46
So I think it is not a bug in Google Chrome.

When you tell Photopea to save a file, a sign "Saving" should appear at the top. You can close Photopea after the saving is done (the sign "Saving" disappears). If you closed Photopea before that, you will end up with a 0 Byte file.

Closing Photopea before the saving is done is the only way to produce a 0 Byte file. Let us know if you can make Photopea produce a 0-Byte file in any other way.

**Comment by photopea** [comment] 2023-05-03 22:36
I have to close it because of lack of details.

**Closed by photopea** 2023-05-03 22:36 UTC

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 06:47
i use(d) vector pea and my files says 0 bytes can u help dt.ai

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 08:31
it got stuck on saving

**Comment by photopea** [comment] 2025-12-09 08:55
Did you try to use Vectorpea without any browser extensions?

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 10:08
idk

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 11:10
cheome

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 11:11
os

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 11:11
id

**Comment by photopea** [comment] 2025-12-09 13:27
Can you produce a 0 Byte file again? Does it happen every time you export a file?

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 16:04
i cannt load it

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 16:04
i was saving it froze

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 16:07
i save ai

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 16:08
can you

**Comment by photopea** [comment] 2025-12-09 16:26
I am not asking you to open a 0 byte file. I am asking you to create a 0 byte file with Photopea, can you do it?

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 16:48
yes

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 16:51
start over/from sracth

**Comment by photopea** [comment] 2025-12-09 17:07
Could you record a short video where you create a 0-byte file, so that I can see how you do it?

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 17:50
i cant create a 0 b fil/idk start over you saying i have chrome os and i cant access vido or store

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 17:50
yeah

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 17:50
do ya/you have email

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 17:56
i send/share

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 19:54
hello

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 19:57
ill try

**Comment by photopea** [comment] 2025-12-09 21:56
I do bout understand how I can help you, sorry :(

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 22:30
i trying to restore my vec\torepea file 0 bytes

**Comment by photopea** [comment] 2025-12-09 22:38
That is not possible. If your file has no data (zero bytes), it can not be restored.

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 23:05
vwctorpea froze on me and o save

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 23:11
i need help

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 23:12
help someone else google look into it

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 23:14
can google get it back my vectorpea

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 23:19
file what to do ppl bypass 0 bytes and fix

**Comment by javarousfrazier539-ux** [comment] 2025-12-09 23:32
hello

**Comment by javarousfrazier539-ux** [comment] 2025-12-10 00:03
hello

**Comment by photopea** [comment] 2025-12-10 00:46
Do you have a friend or somebody who can speak English?

**Comment by javarousfrazier539-ux** [comment] 2025-12-10 20:17
i can speak english and i want tto report that my vectorpea file got 0 bytre i was saving and froze i close it

**Comment by photopea** [comment] 2025-12-10 20:49
Vectorpea should never freeze or create 0 byte files. If you say that it does, you need to show us a proof, e.g. a video where it happens.

**Comment by javarousfrazier539-ux** [comment] 2025-12-10 21:44
<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/5cbab35e-ec96-4573-978e-2a57b67ce5f2" /> here it says not support

**Comment by javarousfrazier539-ux** [comment] 2025-12-10 21:46
i tried to add file

**Comment by photopea** [comment] 2025-12-10 21:53
Are you sending us a video?

**Comment by javarousfrazier539-ux** [comment] 2025-12-11 08:28
i cant download or video my file got cropted and my vectorpea work at hold is there a way y'all can get file history and fix it

**Comment by photopea** [comment] 2025-12-11 10:32
I already said that if your file has 0 Bytes, it has no content. We do not have any backups of the work of our users. The user must save the work to their device and it should never have 0 Bytes.

**Comment by javarousfrazier539-ux** [comment] 2025-12-12 01:20
the wat it did ti got 0 bytes and frozei tried and i what to know if you can et saved recent recovery or unsaved doc

**Comment by javarousfrazier539-ux** [comment] 2025-12-12 01:21
thar o\n you

**Comment by javarousfrazier539-ux** [comment] 2025-12-12 01:21
or im going to escalate

**Comment by javarousfrazier539-ux** [comment] 2025-12-12 01:28
legally
