### ISSUE TITLE
Transform settings and delete stop working

### ISSUE THREAD

**Issue by AffinityXOfficial** [photopea/photopea#7003] opened 2024-07-27 01:58 UTC
Operating System: PC laptop
Your Web Browser: Photopea.com
The problem happens in the Incognito Mode, too: no

**This must be done to see the problem**
1. Go to www.photopea.com
2. start editing and doing anything
3. maybe open blending options etc
4. scaling, rotating and deleting from the keyboard doesnt work

**Comment by photopea** [comment] 2024-07-27 05:56
What is "scaling, rotating and deleting from the keyboard"? How exactly do you do that?

Does everything work fine in the Incognito mode? If yes, the problems are caused by your browser extensions.

**Comment by AffinityXOfficial** [comment] 2024-07-27 22:49
like scaling with transformation tools and rotating, deleting by pressing delete on the keyboard doesnt work as well. Ill turn off my extensions then.

**Comment by photopea** [comment] 2024-07-28 06:41
Did it help to turn off all your extensions? Without extensions, it should work just as in the Incognito mode, and you said it works in the Incognito mode, right?

**Comment by photopea** [comment] 2024-10-09 08:23
I have to close it, because nobody is responding :(

**Closed by photopea** 2024-10-09 08:23 UTC
