### ISSUE TITLE
Drag and Drop doesn't work

### ISSUE THREAD

**Issue by michalbaruch94** [photopea/photopea#2102] opened 2020-05-01 19:11 UTC
for some reason I just can't drag and drop images into the workspace...
I have tried two different browsers and it didn't help...
please help :(

**Comment by photopea** [comment] 2020-05-01 21:57
Hi, 90 percent of problems with Photopea are caused by browser extensions, which modify the behaviour of websites. Could you disable your browser extensions and try it again?

**Comment by michalbaruch94** [comment] 2020-05-01 22:57
Hi, unfortunately it didn't help... is there anything else i can try?

**Comment by photopea** [comment] 2020-05-02 08:52
What operating system and a browser are you using? Is there a blue rectangle, when you drag a file on top of Photopea? Could you record a short video of how you do it?

**Comment by michalbaruch94** [comment] 2020-05-02 10:37
I'm using windows 10, and i tried chrome and explorer browser both...
i'm trying to drag the picture in here and for some reason this doesn't work either... 
Could you give me an email adress and i'll send it?

**Comment by photopea** [comment] 2020-05-02 16:41
Many websites allow dragging files into them. Can you drag an image e.g. into https://imgur.com/ ?

You should never use Internet Explorer, as there is zero chance to view modern websites correctly in it. Try reset the settings of Chrome. Maybe some antivirus or other "security software" prevents you from giving your files to websites.

**Comment by photopea** [comment] 2020-05-05 08:55
I will close it because of lack of details.

**Closed by photopea** 2020-05-05 08:55 UTC
