### ISSUE TITLE
UI stops responding to clicks

### ISSUE THREAD

**Issue by ioma8** [photopea/photopea#1787] opened 2019-11-07 08:48 UTC
Since the last version (object selection tool added) the UI frequently stops responding to mouse clicks - brush does nothing, clicking on "New layer" button does nothing etc. JS console is free of errors.

PS: I am Czech based, Javascript developer if you wanna help I might join the project with some support.

**Comment by photopea** [comment] 2019-11-07 09:02
Hi, could you describe any steps to reproduce it? Are you sure it is not because you are doing something differently?

**Comment by ioma8** [comment] 2019-11-07 09:09
Hi, it happens in Chrome browser. No I am not doing anything differently. It just freezes for several minutes, then resumes to work again. Happens repeatedly also after PC restarted. Maybe it has something to do with the Chrome or WebGL? Happened to me on multiple images including the in-site examples.

**Comment by photopea** [comment] 2019-11-07 09:14
It is hard to say, as it never happened to me :( I opened the demo "pea.psd" and played with it for 2 minutes, it works well.

Can you disable WebGL in More - Use WebGL? does it help?

**Comment by photopea** [comment] 2019-11-11 12:29
I have to close it because of lack of details. I was not able to reproduce it.

**Closed by photopea** 2019-11-11 12:29 UTC
