### ISSUE TITLE
Curves Adjustments Not Working

### ISSUE THREAD

**Issue by CxryzNFTs** [photopea/photopea#5439] opened 2023-03-12 06:05 UTC
Hello! When I try to adjust the white balance using "Sample from Image" and clicking White box in Curves Adjustments Layer, nothing happens. What seems to be the issue here?

**Comment by camoody1** [comment] 2023-03-12 06:22
I have this problem, too. It's a weird thing. You need to close your Curves window, reopen your Layers window, click OFF the Curves layer mask (click the layer you're adjusting), then REOPEN the Curves window, and that generally works for me. I don't know why, but I have to play around with it every time.

**Comment by photopea** [comment] 2023-03-12 09:07
It should be fixed now. This color sampler (which is bound to the adjustment) should ignore the mask that is selected.

**Closed by photopea** 2023-03-12 09:07 UTC

**Comment by camoody1** [comment] 2023-03-12 13:21
Confirmed! This tool is now working on the first try. Nice fix. I probably should have brought it up when I first noticed it. Thank you.
