### ISSUE TITLE
[bug] Transform selection won't accept confirm

### ISSUE THREAD

**Issue by philcady** [photopea/photopea#5118] opened 2022-11-17 19:37 UTC
When attempting to transform a selection, unable to confirm this transformation.  Canceling it works just fine, but confirmation just logs the button press in History and does not apply the transformation (in my case, rotations).

Attempted in Chrome Version 107.0.5304.110 (Official Build) (x86_64) and Firefox 107.0 (64-bit) with similar results.

Using MacOS Monterey 12.6

**Comment by meakemi** [comment] 2022-11-17 19:46
same problem here

**Comment by zns-commits** [comment] 2022-11-17 21:11
same problem here

I'm using Chrome Version 107.0.5304.107 Official Build) (64 bits)

Windows 10 20H2 (build 19042.1348)

I cant confirm or use the check mark button
also in the case of rotations only
![image](https://user-images.githubusercontent.com/79872012/202560119-90201633-92d9-4d93-a9d4-c0349ddeac57.png)

**Comment by myfonj** [comment] 2022-11-17 23:45
Same here, on various Firefoxes and Chromes on various machines.

Str:  new project, draw a dot with paintbrush, unlock layer, rectangle select around dot, `Edit > Transform > Scale`, change some dimension, apply (with check-mark button or enter keyboard key).

Outcome:

    Uncaught TypeError: can't access property 0, this.NH is null [pp.js:7126:42]

in the console, history item "free transform" appears. After cancelling it is not possible to return to history state prior that (unsuccessful) transform

    Uncaught TypeError: can't access property "jo", j is null [pp.js:8744:4]

---

Interestingly few time the scale worked for me, I think after trying to scale whole layer first, but cannot reproduce it now.

**Comment by petalplucker** [comment] 2022-11-18 11:04
Same here. Also, Photopea hangs after that. No command will register - it just keeps adding onto your History as "Free Transform". E.g. I tried going to an earlier stage in History, but it instead adds a new action of "Free Transform" at the bottom of History.

**Comment by photopea** [comment] 2022-11-18 13:13
sorry guys, it is fixed now.

**Closed by photopea** 2022-11-18 13:13 UTC

**Comment by philcady** [comment] 2022-11-18 14:48
Excellent, thanks for your prompt attention to this!  Works great now, cheers.
