### ISSUE TITLE
Won't let me save my .PSD file

### ISSUE THREAD

**Issue by kimfal74** [photopea/photopea#1328] opened 2019-04-04 11:04 UTC
I can't save my .psd file. I started from scratch and now I can't save it? I get this message:
Squirrelpreneur-Logo.psdFailed - System busy
blob:https://www.photopea.com/0b125ece-0971-4b8e-a929-f6053c4c47ff

**Comment by photopea** [comment] 2019-04-04 11:14
Hi, are you using Photopea at ww.Photopea.com ?

Where did you see that message? Can you start another PSD file from scratch and save it again? i.e. does it happen every time?

**Comment by kimfal74** [comment] 2019-04-04 12:12
Hi,
I am using https://www.photopea.com

I see it in my chrome download manager. I have only before used an already created .psd file from photoshop and saved it, that worked.

This is the first time I have created a .psd file from scratch inside photopea.com. Creating a new one from scratch will take time so I won't be able to do it today!

**Comment by kimfal74** [comment] 2019-04-04 12:16
However, I created a new .psd file and made one layer and tried to save it, I got the same message :(

**Comment by photopea** [comment] 2019-04-04 12:16
It sounds to me like the problem is outside Photopea. Do you have free space in your computer? Or any restrictions against saving PSD files?

**Comment by kimfal74** [comment] 2019-04-04 12:58
No, no restrictions and yes I have space on my computer.

**Comment by photopea** [comment] 2019-04-04 13:02
Can you open an existing PSD from your computer and save it as PSD from Photopea? Is it still saved?

**Comment by kimfal74** [comment] 2019-04-04 14:01
I opened up a .psd file and tried to save it again but it didn't save. I just got the same message as the one I got before.

**Comment by photopea** [comment] 2019-04-04 14:08
Can you go to any random website and e.g. right-click any image and press Save Image As ? I think your browser can not save any files at all.

**Comment by photopea** [comment] 2019-04-04 14:35
That is strange. Can you update your web browser? Are you using any Beta version of your browser? Can you try another web browser? What is your operating system.

**Comment by kimfal74** [comment] 2019-04-04 15:39
my operating system is windows 10 home. My browser is up to date. I am going to try something

**Comment by kimfal74** [comment] 2019-04-05 08:16
I figured out what was wrong, it wont save when I use the Chrome browser but when I tried in Firefox it saved with no problem????

**Comment by photopea** [comment] 2019-04-05 08:22
Hi, I found a similar problem here: https://www.reddit.com/r/techsupport/comments/7xfpty/random_download_appeared_while_browsing_web_and/  There could be a virus in your computer.

Could you try to log out of Chrome and log in again?

**Comment by photopea** [comment] 2019-04-08 07:57
I have to close it because of lack of details :(

**Closed by photopea** 2019-04-08 07:57 UTC
