### ISSUE TITLE
Transforming Text Pink Box

### ISSUE THREAD

**Issue by AidanIsNotLikingPhotopea** [photopea/photopea#2567] opened 2020-10-29 23:05 UTC
I stumbled onto a weird bug, which may actually not be one, but I thought I'd bring it up. When I try to transform a text box, it started randomly sizing a pink box onto the screen instead of resizing the text. I have no idea what caused it, but it started happening randomly.

**Comment by photopea** [comment] 2020-10-29 23:07
Hi, what do you mean by "transforming a text box"? Do you mean using a Free Transform on a Text layer?

I can not reproduce such behaviour. Could you tell us more, or provide a screenshot?

**Comment by photopea** [comment] 2020-11-08 16:29
I have to close it because of lack of details :(

**Closed by photopea** 2020-11-08 16:29 UTC
