### ISSUE TITLE
Adjustment layers reset when reopening projects

### ISSUE THREAD

**Issue by a-username-4** [photopea/photopea#3662] opened 2021-08-15 23:50 UTC
Every time I reopen a previously saved project that uses a hue-saturation adjustment layer, the layer has reset back to its default settings. 
For reference, this is what it looks like before the layer:
<img width="1284" alt="Screen Shot 2021-08-15 at 6 46 56 PM" src="https://user-images.githubusercontent.com/88991477/129496349-b5aa31cf-b0c4-4693-b89b-40f85327e6e7.png">
This is what it looks like after the layer:
<img width="1435" alt="Screen Shot 2021-08-15 at 6 47 23 PM" src="https://user-images.githubusercontent.com/88991477/129496360-d068ffc7-0bf0-45d6-a5d0-8b33ba3e08e7.png">
And this is what it looks like when I open it up again:
<img width="1436" alt="Screen Shot 2021-08-15 at 6 47 52 PM" src="https://user-images.githubusercontent.com/88991477/129496365-05c08d9d-188f-4a8d-92f5-8a709dbba586.png">

**Comment by photopea** [comment] 2021-08-15 23:58
I can not reproduce it. Can you describe steps, which can be used to reproduce it?

I think you have too many PSDs and you are opening the wrong one (with an old version of the adjustment layer).

Does it happen in a browser with all browser extensions disabled?

**Comment by photopea** [comment] 2021-08-29 16:27
I have to close it because of lack of details.

**Closed by photopea** 2021-08-29 16:27 UTC
