### ISSUE TITLE
Artboards - Duplicating artboards to new project, don't move assets to the corresponding place

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#3547] opened 2021-07-13 01:01 UTC
[Cartas Especiales Cultura Chupística.zip](https://github.com/photopea/photopea/files/6805184/Cartas.Especiales.Cultura.Chupistica.zip)

When duplicating to a new project all the folders inside Tipo F artboard, i get the assets in different places.
![image](https://user-images.githubusercontent.com/11801254/125374088-43d93b00-e354-11eb-9402-fc70693241f9.png)
to
![image](https://user-images.githubusercontent.com/11801254/125374053-2e641100-e354-11eb-8b57-9b7ec2acd2bf.png)

**Comment by photopea** [comment] 2021-08-04 18:32
I am not able to reproduce the bug :( I guess it has been fixed by other modifications.

**Closed by photopea** 2021-08-04 18:32 UTC

**Comment by avagp** [comment] 2021-08-04 19:46
Yes probably. I cannot repro neither.  :)

**Comment by avagp** [comment] 2021-08-04 19:54
how to repro:

1. enter https://www.photopea.com/#i6BsxycvJ
2. select all the folders inside Tipo F, but not Tipo F folder
3. Duplicate into a new project.
4. See where Etiqueta 3 folder is with transformation controls on.

**Comment by photopea** [comment] 2021-08-04 20:38
I am soooo sorry :( I have been fixing this issue many times, but never fixed it properly.

I think now it should be fixed properly. Thanks for your patience with me!

**Comment by avagp** [comment] 2021-08-04 21:44
Thanks to you Ivan!!

You are really great as an entrepreneur and incredible at support.

Thank you for letting me help you on this project, which I like very
very much.

Cheers!
