### ISSUE TITLE
Bug: If you pick a color in the Color Picker, the Color Picker window won't close.

### ISSUE THREAD

**Issue by aZealot** [photopea/photopea#3964] opened 2021-11-10 18:32 UTC
Browser: Firefox. Bug does not occur in Safari or Google Chrome.

Cause: Open the Color Picker window, pick a color, and click OK.

Symptoms: Color Picker won't close when you click X.

**Comment by photopea** [comment] 2021-11-10 18:46
I can not reproduce it in Firefox on Windows. In my case, the color picker always closes :(

Maybe try these steps and let me know if it helped: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by nothingshiru** [comment] 2021-11-10 19:57
I have encountered this bug several times too. But I cannot reproduce it.

**Comment by aZealot** [comment] 2021-11-11 03:52
The problem fixed itself even though I didn't do anything so I guess it's fine?

**Comment by photopea** [comment] 2021-11-17 16:09
I will close it now, but I would be really glad if you find a way to make it happen.

**Closed by photopea** 2021-11-17 16:09 UTC
