### ISSUE TITLE
When I go to transform; warp;and change to wave, it turns my image black. please help!

### ISSUE THREAD

**Issue by jcthreads** [photopea/photopea#6809] opened 2024-05-29 02:07 UTC
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment] 2024-05-29 09:00
I can not reproduce it :( Did you try it in the Incognito mode, i.e. without any of your extensions modifying the code of Photopea?

**Comment by photopea** [comment] 2024-06-08 09:06
I have to close it now, because the person did not reply.

**Closed by photopea** 2024-06-08 09:06 UTC
