### ISSUE TITLE
Photopea Closing Even After I Press Cancel 

### ISSUE THREAD

**Issue by funing36** [photopea/photopea#6348] opened 2024-01-23 23:33 UTC
Your Operating System: Chrome OS
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: N/A

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open/Create a file
3. try to close the file without saving
4. Press cancel and it has a chance to close despite.

I work on stuff and sometimes, Ctrl+W kicks in and it tries to exit. Most of the time, it's no big deal, but sometimes, it closed when I said no. IDK why this happens, but it can cause a slight inconvenience and possibly losing some work.

**Comment by photopea** [comment] 2024-01-24 09:25
I can not reproduce it :( Whenever a browser asks me "Leave site?" and I press "Cancel", I stay at Photopea :(

You did not mention the version of your Chrome browser. Is it updated?

**Comment by funing36** [comment] 2024-01-25 13:49
Yah, around Chrome 120. Might just be my computer. ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by photopea** [comment] 2024-01-25 14:43
Could you record and share a short video of it happening?

**Comment by photopea** [comment] 2024-01-30 13:40
I have to close it because of lack of details :(

**Closed by photopea** 2024-01-30 13:40 UTC
