### ISSUE TITLE
clone tool problem

### ISSUE THREAD

**Issue by rezaafz** [photopea/photopea#1585] opened 2019-07-26 19:39 UTC
Hello
sometimes after a little working Clone tool doesn't work at all!
i have to save the image , open it again and then continue the work! that's very annoying ...!

**Comment by rezaafz** [comment] 2019-07-26 19:47
Here's a recorded video of what really happens :
https://drive.google.com/open?id=1s2-OaDErlKp7q650Fa5IhZn5P8dt8yfo

**Comment by photopea** [comment] 2019-07-30 12:39
Hi, I was playing around for several minutes, but I could not make it happen :( Could you find any specific instructions how to reproduce it?

**Comment by photopea** [comment] 2019-07-31 18:53
I have to close it because of lack of details :(

**Closed by photopea** 2019-07-31 18:53 UTC
