### ISSUE TITLE
Photopea crashing contantly since 6/2/24

### ISSUE THREAD

**Issue by J-A-Mckeown** [photopea/photopea#6398] opened 2024-02-08 07:04 UTC
Your Operating System: MAC OS Sonoma
Your Web Browser: Using the MAC PKG file but also happens inside edge.
The problem happens in the Incognito Mode, too: Still hang whilst using InPrivate browsing.

**This must be done to see the problem**
Issue is hard to replicate, seemed to happen when renaming layers but also happens after moving objects or using the shape tool in particular, seems to hang for no apparent reason. Has recently developed as it has been really good for the past 6 months and is now crashing/hanging every 5 - 10 minutes, have tried having no other files open but it's intermittent and hard to pin point.

**Comment by J-A-Mckeown** [comment] 2024-02-11 10:37
I've got over 15GB of free RAM, (M2 Macbook pro). was there a recent update in the last week or so because it is a very recent issue and even when trying to open files i'll get the hung error.

**Comment by photopea** [comment] 2024-02-11 11:35
What is a "MAC PKG file"? Where did you get it?

**Comment by J-A-Mckeown** [comment] 2024-02-11 11:36
Another update, It appears linked to MS edge, has tried changing the security settings as suggested but still no good. seems to work okay in safari but only used it for a short while.

**Comment by J-A-Mckeown** [comment] 2024-02-11 11:40
> What is a "MAC PKG file"? Where did you get it?

Sorry, it's not a PKG file, it's an app download from chrome that makes an icon for photopea from launchpad,  see screenshot below, just opens a single app within a single browser window
<img width="931" alt="Screenshot 2024-02-11 at 10 38 33 pm" src="https://github.com/photopea/photopea/assets/100405129/68a37c95-6d74-44ff-8d77-16854372f9a9">

**Comment by photopea** [comment] 2024-02-11 12:01
Are there any specific steps which lead to Photopea crashing in 100% of cases?

**Comment by photopea** [comment] 2024-03-04 19:20
I have to close it because of lack of details. The majority of crashes is caused by not enough RAM (e.g. when you want to edit a 500 MB PSD with 2 GB of RAM on your phone).

**Closed by photopea** 2024-03-04 19:20 UTC
