### ISSUE TITLE
Fullscreen Mode in Firefox Breaks Layer Drag Sorting

### ISSUE THREAD

**Issue by seapulse** [photopea/photopea#1818] opened 2019-11-22 07:51 UTC
Sometime layer dragging comes back but I can't quite pin down how. Here is a video:
[https://imgur.com/a/9Ssd5uD](https://imgur.com/a/9Ssd5uD)

I can still move layers around via Ctrl [ & ]. However, I cannot move layers into folders that way.

Thank you,

**Comment by photopea** [comment] 2019-11-22 09:04
Hi, what version of Firefox are you using? Can you update it?

When I try Photopea in Firefox, I can drag-and-drop layers in a regular mode, in a fullscreen mode, and even after escaping the fulscreen mode (i.e. always).

**Comment by seapulse** [comment] 2019-11-22 09:25
> 
> 
> Hi, what version of Firefox are you using? Can you update it?
> 
> When I try Photopea in Firefox, I can drag-and-drop layers in a regular mode, in a fullscreen mode, and even after escaping the fulscreen mode (i.e. always).

v70.0.1 which seems to be the latest. I'm trying to replicate it consistently. It seems like a it's a timing thing, like if I move to fast after moving a layer or something like that. I can't quite pin down the replication. I've noticed that switching tabs in the browser can sometimes resolve it as well.

**Comment by photopea** [comment] 2019-11-22 09:30
This is so strange. What OS are you using? I can not reproduce such behaviour in FF under Windows 7 :/

**Comment by photopea** [comment] 2019-12-12 17:44
I have to close it because of lack of details :(

**Closed by photopea** 2019-12-12 17:44 UTC
