### ISSUE TITLE
PSD not properly opening

### ISSUE THREAD

**Issue by jaelynlariena2** [photopea/photopea#250] opened 2017-08-20 00:05 UTC
Anytime I open a PSD file it opens but it comes a blank. I can't duplicate into another file or edit any of the other layers inside the file. And when I open up a photo file it doesn't work either. But when I just open a photo without opening a PSD file its perfectly fine. So I think the bug is inside the PSD. So please fix soon :)

**Comment by photopea** [comment] 2017-08-20 00:18
Hi, can you please send us your PSD file to support@photopea.com ? :)

**Comment by rdorrans5287** [comment] 2017-08-20 01:30
This is happening to me, too, but it's not just for one PSD. Any PSD I open opens with the image of whatever was in a different tab.

**Comment by rdorrans5287** [comment] 2017-08-20 01:31
![screenshot 2017-08-19 at 6 30 31 pm](https://user-images.githubusercontent.com/31171880/29491302-8b9db1d2-850c-11e7-9ee7-334a159e5ed8.png)

**Comment by PaintedGypsyCowgirl** [comment] 2017-08-20 06:15
I'm having the same issue as others. I open an image, go to open a PSD in another tab and it will not let me duplicate it over to the actual image. Cannot click on the layers, either. The PSD doesn't show the actual thing, just the image from the previous tab.

**Comment by photopea** [comment] 2017-08-20 08:39
Guys, I am very sorry. I updated Photoea yesterday, and introduced a new bug (the one you have). It should be fixed now.

@rdorrans5287  Layer thumbnails are displayed incorrectly. Can you tell me, what number do you see here: http://devicepixelratio.com/ ?

**Comment by rdorrans5287** [comment] 2017-08-20 21:46
I see the number 1.
Also, as far as I can tell, the issue is fixed.

**Comment by photopea** [comment] 2017-08-20 21:48
@rdorrans5287  ok thank you :)

**Closed by photopea** 2017-08-20 21:48 UTC
