### ISSUE TITLE
Save as PSD fails

### ISSUE THREAD

**Issue by techignites** [photopea/photopea#126] opened 2017-01-23 00:54 UTC
When I try to save my work as a PSD file I receive the error Failed - No File

I am able to publish the file and then save the jpg but I am not able to save as a PSD or save for Web.

**Comment by photopea** [comment] 2017-01-23 11:20
Hello, what browser do you use?  Can you save as PSD the initial file "pea.psd", that appears at the beginning?  Can you please send us your PSD to support@photopea.com ?

**Comment by techignites** [comment] 2017-01-23 19:47
I am using the newest version of chrome

**Comment by techignites** [comment] 2017-01-23 19:53
[image: File]
kids flyer 1.psd
<https://drive.google.com/open?id=0B2rkzS3jgYOXWHoxNFQxd3hHclE>
Final version
[image: JPEG image]
TechIgnitesSummer2017-2.jpg
<https://drive.google.com/open?id=0B2rkzS3jgYOXSEt5SmN4azdBV2s>

**Comment by photopea** [comment] 2017-01-26 13:48
Hi, I have updated the Photopea, but I am not sure if this update can influence your problem.

I tried to edit your PSD in the latest version and everything seems to work fine. Can you please try to edit it again? If it does not work, can you describe exact steps, how to reproduce that situation? Is there anything special you did?
![kids flyer 1 kopie](https://cloud.githubusercontent.com/assets/15955558/22333382/3c4e52e4-e3d6-11e6-9085-eaab747093fe.png)

**Comment by techignites** [comment] 2017-01-31 00:45
I will give it a go thank you.

**Comment by photopea** [comment] 2017-03-04 10:02
I have to close it because of lack of details :( Feel free to reopen it.

**Closed by photopea** 2017-03-04 10:02 UTC
