### ISSUE TITLE
Error in photoshop file: wrong signature

### ISSUE THREAD

**Issue by AlesBlaha** [photopea/photopea#1243] opened 2019-02-22 16:13 UTC
Hi there,
I'm not able to open PSD file in Photopea, which I recently created (created from the scratch in Photopea, W10Pro 64bit, Chrome 72.0.3626.119). I'm getting "wrong signature" message followed by "loading" message, but file is never opened.  When trying in other editor (GIMP), I get "File is corrupted" error. File can be found here: https://drive.google.com/open?id=1kU8GamY8r1LEyws18ysjhn1Vdrs-JFFO 
Is there any chance it could be restored somehow?

**Comment by photopea** [comment] 2019-02-28 01:29
Hi, your file really seems to be corrupted :/ Could you try to create the same file (or a part of it) again and see, if the file is corrupted again?

If you could describe a way how to produce any corrupted file, it would be really helpful! :)

**Comment by photopea** [comment] 2019-03-04 22:58
I have to close it because of lack of information.

**Comment by joshmorel** [comment] 2019-03-15 15:44
@photopea Save issue happened to me from file saved as PSD 9 days ago. If I upload the file would it provide any clue? I can open it in a PDF viewer but not Photopea or GIMP. 

I have no idea how to reproduce issue however.

**Comment by photopea** [comment] 2019-03-16 08:32
Hi, is it a PDF or PSD file? I really need someone to try to create such file from scratch, and find the step, which makes the file corrupted. I am ready to pay you, if you can do that.

**Comment by joshmorel** [comment] 2019-03-16 15:23
It is definitely a PSD file. The [File Header Section described here](https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_46269) is also exactly the same as a different valid file. 

Would providing the file help at all? I wish I could figure out a way to reproduce but it would be a bit of a stab in the dark.

**Comment by joshmorel** [comment] 2019-03-16 15:29
I take that back. I figured it out. It has something to do with duplicating a layer, maybe because it is was within a folder. Just trying to figure out what aspect of the layer duplication caused the issue.

**Comment by joshmorel** [comment] 2019-03-16 15:58
I was able to narrow it down to just duplicating layer of text. When the layer name uses the text entered and a copy is made the file becomes corrupt. When I renamed the text layer name to something shorter and made a copy it was okay. 

Here is an example of the file becoming corrupted:

![Photopea-duplicate-text-signature-wrong](https://user-images.githubusercontent.com/10546720/54477880-9c2ebb00-47e2-11e9-8964-04e3127c9f02.gif)

**Comment by photopea** [comment] 2019-03-16 16:25
Josh, I am absolutely confident to announce, that you are the best person in the world.

Layers in PSD files can have length of up to 256 characters. Text layers get their name by their text content (until you manually change that), and it is cropped to 256 characters.

But when you copy the layer, current code adds " copy" to the end of the layer name, and in this case it becomes 261 characters long, which makes the file corrupted.

**Comment by joshmorel** [comment] 2019-03-16 16:39
> Josh, I am absolutely confident to announce, that you are the best person in the world.

I'm going to have to find a way to fit that into my CV :laughing:

**Comment by photopea** [comment] 2019-03-16 20:56
Ok I fixed it now :)

**Closed by photopea** 2019-03-16 20:56 UTC
