### ISSUE TITLE
Bug when it saves or edit smart objects

### ISSUE THREAD

**Issue by amethyst01** [photopea/photopea#4235] opened 2022-01-14 20:03 UTC
When I save things or edit smart objects the most part of the time the message that appears stays there(mostly like three messages at the same time) and it blocks the view .
![Captura de tela 2022-01-14 170219](https://user-images.githubusercontent.com/38044329/149577810-8ee46af6-399e-4890-9e77-d4d0674d1100.png)

**Comment by photopea** [comment] 2022-01-14 22:00
I can not make it happen :( In my case, the message always goes away.

Can you tell me, what should I do after opening www.Photopea.com , to see this maessage, which will stay? Are you using smart filters on smart objects?

**Comment by amethyst01** [comment] 2022-01-15 23:06
I do save the project a lot of times and in some of this times it happens and in some it doesn't. I tried to see if it was just with smart objects but it isn't. And no, i'm not using filters/smart filters.

**Comment by photopea** [comment] 2022-01-15 23:10
Maybe you are low on RAM memory. What is the size of your document in pixels (or in other units + DPI) ?

**Comment by amyjewitt** [comment] 2022-01-16 01:28
Hiya! I am also having this problem!

**Comment by photopea** [comment] 2022-01-16 10:26
Can you tell me, what should I do after opening www.Photopea.com , to see this maessage?

**Comment by popbee** [comment] 2022-01-17 00:29
@amyjewitt @amethyst01 Ivan is looking for ways to reproduce this.  Is it because a save is currently ongoing and you are triggering another one on top? Do you have multiple documents saving simultaneously?

**Comment by amyjewitt** [comment] 2022-01-17 01:04
@popbee @photopea It seems that this occurs when I have multiple documents open, however, I am not saving them all at the same time, as you mentioned. I have noticed it happens when I am saving the Smart Object (it is open as a new file) and then click to the original document to see that the Smart Object has been placed/updated. It may be difficult to reproduce this issue because it is not consistent, I have noticed that it only happens sometimes when I am saving, it not every time.

Next time I am working in Photopea I can screen-record and see if I can catch the glitch to share with you.

**Comment by photopea** [comment] 2022-01-17 01:18
@amyjewitt Can you open Photopea and find exact steps, which cause this problem every time? Then, you can describe these steps to us.

**Comment by amethyst01** [comment] 2022-01-17 15:18
I found out a thing that maybe it could the problem or not, that Google Chrome consume a lot of ram memory and Mozila Firefox consume a lot of ram memory and disk(sometimes it was 100%), so I downloaded a program to decrease it, but I didn't tested using Photopea with it yet, but for what it shows in Task Manager it's lower.

**Comment by popbee** [comment] 2022-01-17 18:20
@amethust01 I'm curious, what is the program you downloaded?  Within Google Chrome, there is a task manager with more precise memory usage (per tab). If you are using PhotoPea with Google Chrome you can judge the amount of RAM in there. You can add more columns like `GPU memory`.

![image](https://user-images.githubusercontent.com/1083830/149820710-8a134966-965e-4ced-96c8-47920daefe41.png)

**Comment by amethyst01** [comment] 2022-01-18 19:22
![Captura de tela 2022-01-18 162217](https://user-images.githubusercontent.com/38044329/150004470-c677ebd5-80ab-442f-b247-3ede9239a81f.png)

It's this one.

**Comment by amethyst01** [comment] 2022-01-18 19:24
And the task manager:
![Captura de tela 2022-01-18 162337](https://user-images.githubusercontent.com/38044329/150004771-5b4b498a-1814-4595-b295-780492185c71.png)

**Comment by photopea** [comment] 2022-01-20 22:29
I did not do anything. How much RAM in total do you have?

**Comment by amethyst01** [comment] 2022-01-23 17:42
16GB
![Captura de tela 2022-01-23 144144](https://user-images.githubusercontent.com/38044329/150690874-8a79b48b-0983-4363-9ee4-76cb652364ef.png)
.

**Comment by photopea** [comment] 2022-01-23 18:28
That should be enough. So are you able to reproduce the bug (make it happen on purpose)?

**Comment by photopea** [comment] 2022-02-07 00:30
I have to close it because of lack of details.

**Closed by photopea** 2022-02-07 00:30 UTC
