### ISSUE TITLE
Can't use filter "surface blur"

### ISSUE THREAD

**Issue by lissaispunk** [photopea/photopea#4349] opened 2022-02-21 05:04 UTC
Hi team, whenever I click on filter "surface blur" a black screen appears. I have to refresh or turn photopea back on, but as soon as I try to "surface blur", it shots down again. Already tried it on an incognito window :(

**Comment by photopea** [comment] 2022-02-21 09:01
I can not reproduce such behaviour :(

Hi, did it ever work in the past? What operating system and a web browser do you use?

**Comment by ProgrammingLife** [comment] 2022-03-05 18:29
@lissaispunk Maybe you should update your browser? Try to use fresh Chrome browser.

**Comment by photopea** [comment] 2022-03-05 20:50
I have to close it because of lack of details. Nobody else reported such problem.

**Closed by photopea** 2022-03-05 20:50 UTC
