### ISSUE TITLE
The typed in text does not show

### ISSUE THREAD

**Issue by NestorSampedro** [photopea/photopea#7086] opened 2024-08-23 16:22 UTC
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment] 2024-08-23 16:45
Did you try it in the Incognito mode? This problem is usually caused by your browser extensions.

**Comment by photopea** [comment] 2024-09-07 23:34
I have to close it because of lack of details :(

**Closed by photopea** 2024-09-07 23:34 UTC
