### ISSUE TITLE
Free Transform not working

### ISSUE THREAD

**Issue by c6tlovrs** [photopea/photopea#6797] opened 2024-05-27 23:57 UTC
Your Operating System: Chromebook?
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Don't have access to Incognito Mode on my computer, so idk

**This must be done to see the problem**
1. Go to www.photopea.com

Um, I'm not sure what the above is for, but I am having issues with free transform where it works for a moment when I open or make a file, but then it stops working after I make edits. Most notably, it stops working when I change the blending layer of the photo. I have tried most things, from restarting my computer to changing my browser, but none of these solutions seem to solve the issue. I am not sure if it's a bad update or just my computer, but it is very frustrating as I have to save and then reopen my file to be able to use free transform. I hope you can fix this. If so, thank you!!!

**Comment by photopea** [comment] 2024-05-28 06:24
Could you tell me steps what you do, so that I can see the problem? What file should I open, where should I click next?

Did you read our manual? https://www.photopea.com/learn/free-transform

**Comment by photopea** [comment] 2024-05-29 20:43
I have to close it because of lack of details :(

**Closed by photopea** 2024-05-29 20:43 UTC

**Comment by c6tlovrs** [comment] 2024-05-29 22:13
Sorry for not responding. I just kind of accepted it and have worked my way
around it. Thank you for helping me tho! 😭

**Comment by photopea** [comment] 2024-05-29 22:53
I am pretty sure it is caused by one of your browser extensions. Can you disable your extensions?
