### ISSUE TITLE
Copy&Pasted Images larger than canvas size not working correctly

### ISSUE THREAD

**Issue by ScorpioRage** [photopea/photopea#2174] opened 2020-05-28 21:02 UTC
When copying and pasting something that is larger than the canvas size, the true image dimensions are shown, but if the picture is dragged about, only white space is shown for everything that was not in the initial view.

**Comment by photopea** [comment] 2020-05-28 21:11
Hi, could you tell us more? Where "the true image dimensions are shown"? What do you mean by white space? Could you show a screenshot or a video?

**Comment by ScorpioRage** [comment] 2020-05-28 21:21
Here is a video of the problem. I tried on two separate computers, both running Chrome.
________________________________

**Comment by photopea** [comment] 2020-05-28 21:24
I can not see any video. Please, reply at the github website, not with an email.

**Comment by ScorpioRage** [comment] 2020-05-28 22:01
No problem
[2020-05-28 14-17-35.zip](https://github.com/photopea/photopea/files/4698490/2020-05-28.14-17-35.zip)

**Comment by photopea** [comment] 2020-05-28 22:21
This is very strange. I have never seen such thing.

Can you try to save the image into your computer, and then, open it from your computer? Does it work then?

**Comment by ScorpioRage** [comment] 2020-05-28 22:29
[2020-05-28 15-24-33.zip](https://github.com/photopea/photopea/files/4698617/2020-05-28.15-24-33.zip)
Yeah that seems to work, though it brings the image in scaled to the canvas instead of whatever its dimensions were before. This work around should be fine for most applications, but I can think of a few where I'd want the original scale saved.

**Comment by photopea** [comment] 2020-05-28 22:58
Hi, I just tried to do the same thing as you did in the first video.

I make an empty document in Photopea, 1920x1080, I go to https://unsplash.com/photos/8Iyo3jwntMk  and copy-paste the image into Photopea.

The pasted image is 1858 x 2831 pixels, so its right side deos not touch the right side of the document: https://i.imgur.com/GQKrYah.jpg

Can you disable all browser extensions and try it again? I think your browser extensions can manipulate images in the clipboard.

**Comment by ScorpioRage** [comment] 2020-05-28 23:09
[2020-05-28 16-06-04.zip](https://github.com/photopea/photopea/files/4698735/2020-05-28.16-06-04.zip)
Did in incognito, which should disable all the extensions. Same problem.

**Comment by photopea** [comment] 2020-05-28 23:24
Can you tell me, what web browser and version are you using?

Can you try to paste your image into www.Imgur.com instead? What do you get?

**Comment by ScorpioRage** [comment] 2020-05-28 23:30
Google Chrome
Version 83.0.4103.61 (Official Build) (64-bit)
Uploading to Imgur seems fine
[2020-05-28 16-28-13.zip](https://github.com/photopea/photopea/files/4698794/2020-05-28.16-28-13.zip)

**Comment by photopea** [comment] 2020-05-28 23:39
I have the same Chrome 83 on Windows 10, but it works well in my case :(

What if you paste it into Photopea when no document is opened?

**Comment by ScorpioRage** [comment] 2020-05-28 23:42
Works fine, but the use case is that I was copy and pasting various images to make a photo mashup, which I've done a lot before and never had problems with Photopea, so this is a new problem.

**Comment by photopea** [comment] 2020-05-28 23:52
I can not reproduce your problem. Nobody reported it in the past either :(

Can you close the browser completely and open it again and see if it still happens?

If yes, right after you paste the image into a document, can you save that document as a PSD and send it to support@photopea.com ?

**Comment by hxim** [comment] 2020-05-29 06:12
@photopea I just tried and I confirm this bug. It does not work for me when I create empty layer before pasting the image as seen in video. Maybe you can not reproduce because you did not do that? When I paste into existing non-empty layer it will create new layer on its own and works correctly.

**Comment by photopea** [comment] 2020-05-29 08:37
@hxim You are absolutely right. I saw that empty layer, but I did not think it could be the problem. But it was.

It is fixed now :) thanks to both of you for your help!

**Closed by photopea** 2020-05-29 08:37 UTC

**Comment by backbonegyrus** [comment] 2023-10-26 11:28
It appears that the issue has returned. I tested it on Google Chrome, Microsoft Edge, and Firefox (without extensions) on Windows 10 22H2, 
It works normal when I Import same image via URL.

**Comment by backbonegyrus** [comment] 2023-10-26 13:16
Yes, it’s fixed now. Thank you! @photopea
