### ISSUE TITLE
The screen disappears when I switch tabs

### ISSUE THREAD

**Issue by eannaaaa** [photopea/photopea#6866] opened 2024-06-16 09:16 UTC
![Cuplikan layar 2024-06-16 161619](https://github.com/photopea/photopea/assets/149501974/0796eb44-d670-4793-9fb6-47e5850db440)
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by photopea** [comment] 2024-06-16 11:20
It could be caused by your browser extensions. How many of your browser extensions are allowed to modify Photopea? Does it happen if you stop your extensions from modifying Photopea?

**Comment by guid5d** [comment] 2024-06-21 14:42
> It could be caused by your browser extensions. How many of your browser extensions are allowed to modify Photopea? Does it happen if you stop your extensions from modifying Photopea?

I don't have browser extensions. However, this happens to me as well. It appears when I click fullscreen and disappears when I hover my mouse elsewhere.

**Comment by photopea** [comment] 2024-06-21 23:26
Could you share screenshots of what exactly is happening in your case? Nothing should change when you go fullscreen.

**Comment by 1gabrielbe** [comment] 2024-06-25 03:47
The screen usually works just fine, but after I used it after a while, the screen would hide the layers whenever I clicked on it, or off of it. It seems to be a debugging issue, where the html coding has a cs page that pops up, and blocks the codex, which may just be a line in the connections between the actual layers, and the screens, or windows of the actual open image. That may be the issue.

**Comment by photopea** [comment] 2024-06-25 15:46
I do not understand what you are saying. If you have a problem with Photopea, please, describe, what should I do to see that problem.

**Comment by 1gabrielbe** [comment] 2024-06-25 18:55
Okay. Thank you.


Thank you,
Gabriel Bradley"May your days be filled with plenty."
 

    On Tuesday, June 25, 2024 at 11:46:27 AM EDT, Photopea ***@***.***> wrote:  
 
 


I do not understand what you are saying. If you have a problem with Photopea, please, describe, what should I do to see that problem.

**Comment by photopea** [comment] 2024-06-25 23:10
I will close it now, because the original person did not reply.

**Closed by photopea** 2024-06-25 23:10 UTC

**Comment by 1gabrielbe** [comment] 2024-06-25 23:33
Okay. Thank you. 


Thank you,
Gabriel Bradley"May your days be filled with plenty."
 

    On Tuesday, June 25, 2024 at 07:10:41 PM EDT, Photopea ***@***.***> wrote:  
 
 


I will close it now, because the original person did not reply.
