### ISSUE TITLE
what is this bug?

### ISSUE THREAD

**Issue by NUXMagahet** [photopea/photopea#5924] opened 2023-08-05 14:01 UTC
https://cdn.discordapp.com/attachments/1133672581300506695/1137384588591767552/Screenshot_2023-08-05-19-48-10.png
https://cdn.discordapp.com/attachments/1133672581300506695/1137384588881170512/Screenshot_2023-08-05-19-49-51.png

**Comment by bluep55** [comment] 2023-08-05 15:13
Top right corner of your first image it says "Ad blocking detected".
Ad blockers and extensions can interfere with how Photopea works.
Disable all Ad blockers and all Extensions and see if your problem still exists.

**Comment by photopea** [comment] 2023-08-05 15:14
It is hard to tell. Were you ever able to use Photopea properly?

**Comment by NUXMagahet** [comment] 2023-08-06 12:00
> Top right corner of your first image it says "Ad blocking detected". Ad blockers and extensions can interfere with how Photopea works. Disable all Ad blockers and all Extensions and see if your problem still exists.

It's still the same even without an ad blocker
https://cdn.discordapp.com/attachments/1133672581300506695/1137716444394688532/Screenshot_2023-08-06-17-57-11.png

**Comment by NUXMagahet** [comment] 2023-08-06 12:01
> It is hard to tell. Were you ever able to use Photopea properly?

I'm able to use Photopea properly only on my pc, that happens only on my phone and tablet.

**Comment by camoody1** [comment] 2023-08-06 14:34
You've posted several pictures, yet, I honestly still have no idea what the actual "bug" is that you're reporting. What do you think should be happening that isn't?

**Comment by photopea** [comment] 2023-08-06 19:10
What phone and what tablet do you use? What web browser do you use? Did you try to open more than one image? Does it happen for every files that you open?

I am pretty sure the problem is on your side and there is nothing we can do about it. But I still want to help you find you problem and fix it.

**Comment by NUXMagahet** [comment] 2023-08-07 12:15
> What phone and what tablet do you use? What web browser do you use? Did you try to open more than one image? Does it happen for every files that you open?
> 
> I am pretty sure the problem is on your side and there is nothing we can do about it. But I still want to help you find you problem and fix it.

I use Redmi 7A (Android Q) and Galaxy Tab A6 (Android Lollipop), my browser is Opera on my tablet and Chrome on my phone. The gradient tool works well when I open an image, the bug happens only when I create a new project.

**Comment by photopea** [comment] 2023-08-07 13:46
How large is your new project? Width and height in pixels?

**Comment by NUXMagahet** [comment] 2023-08-08 11:52
720x720

**Comment by photopea** [comment] 2023-08-08 20:41
Could you maybe record a short video of you opening www.Photopea.com and what happens next?

**Comment by photopea** [comment] 2023-08-29 19:29
I have to close it, because the person did not respond.

**Closed by photopea** 2023-08-29 19:29 UTC
