### ISSUE TITLE
White rectangle appears at top of program--"Image Analysis" and blocks any saving of the tool

### ISSUE THREAD

**Issue by vryan111** [photopea/photopea#4793] opened 2022-07-03 18:44 UTC
I can no longer click  the checkpoint to save what I've done.

**Comment by photopea** [comment] 2022-07-04 07:43
Could you describe how can I reproduce such behaviour myself?

**Comment by photopea** [comment] 2022-07-31 23:27
I have to close it because of lack of details.

**Closed by photopea** 2022-07-31 23:27 UTC
