### ISSUE TITLE
When in Warp Mode, Template Zooms Out

### ISSUE THREAD

**Issue by Stratmode** [photopea/photopea#6466] opened 2024-02-25 20:45 UTC
Your Operating System: Windows 10
Your Web Browser: Brave, Chrome
The problem happens in the Incognito Mode, too: So far, no.

**This must be done to see the problem**
1. Go to www.photopea.com/Open app
2. Open PSD file with design
3. Use "Warp" feature
4. Template automatically zooms way out where I can't see the design, anymore.

Sometimes, this happens. Sometimes, it doesn't. When it does happen, I have to wait a while before using it again. But I just came back from a 2 hr movie and it's still doing this.

**Comment by photopea** [comment] 2024-02-25 21:51
Does it happen in the Incognito mode? It could be caused by your extensions.

**Comment by Stratmode** [comment] 2024-02-25 22:55
I noticed that it didn't happen in Icognito, at first, but I'm now on break from designing because it happened again (this time in Icognito).

**Comment by photopea** [comment] 2024-02-25 23:52
Could you find exact steps, which always lead to the problem?

**Comment by Stratmode** [comment] 2024-02-26 02:28
I noticed that there doesn't seem to be exact steps. It's only when I select the "Warp" tool. All the other tools work fine. It's a 50/50 chance that the warp tool will cause the image to automatically zoom out (I'm not hitting any shortcuts. Sometimes, I'm just sitting idly after selecting the tool to see if it will mysteriously zoom out, first). Sometimes, I'm able to warp the image with no problems. Other times,  the random zoom out happens.

**Comment by photopea** [comment] 2024-03-04 18:46
I am closing it, because the person did not respond. Also, what is "Use "Warp" feature"? Do I need to click somewhere? Do you press Edit - Transform - Warp, and it zooms out immediately, without you even touching your computer?

**Closed by photopea** 2024-03-04 18:46 UTC
