### ISSUE TITLE
Gybe Asmz - issues with zooming and scrolling

### ISSUE THREAD

**Issue by gybeasmz** [photopea/photopea#742] opened 2018-06-07 11:36 UTC
This is a very frequent issue, but somehow random. Horizontal scrolling (CTRL + scrolling wheel) does not work most of the time.  Works but only in like 30% of cases. In the other 70% it just starts zooming in. 

Zooming in/out using scrolling wheel also works very sporadicaly. Sometimes it does nothing, something it works like a charm and sometimes I even have to use the PS shortcut (ALT + scrolling wheel) to make it work.

**Comment by photopea** [comment] 2018-06-07 12:44
Could you please find the exact case, when the scrolling / zooming does not work? It works always for me.

I need to reproduce it to be able to fix it.

**Comment by gybeasmz** [comment] 2018-06-07 13:03
Well it usualy takes like 5 seconds to completely broke the zooming/scrolling system. I don´t know what specifics I could give you. This issue renders Photopea unusable because when I´m zoomed in, there is no way I can zoom horizontaly. There is no slider at the bottom whatsoever. I just tried to open 3 new projects, and withing 10 seconds all of them went bananas and in the end only zooming in/out works. I´m not able to scroll horizontaly or verticaly. I have to try really hard to make it work. Just basicaly pushing randomly alt and ctrl and scrolling my mouse and clicking on layers. After a while, horizontal scrolling might start to work, but then again gets broken.

**Comment by photopea** [comment] 2018-06-07 13:15
Again, it never happened to me. Photopea works the same for everybody. Please, tell me, what should I open, what should I press, where should I click, to break it.

**Comment by photopea** [comment] 2018-06-22 16:50
I have to close it because of lack of details.

**Closed by photopea** 2018-06-22 16:50 UTC
