### ISSUE TITLE
Color picker error

### ISSUE THREAD

**Issue by Emircan56** [photopea/photopea#2624] opened 2020-11-21 11:16 UTC
When I open the color picker tab the ok and close button doesn't work. Also, when I double click the application gets zoom and we expect a mobile application to be published.

**Comment by photopea** [comment] 2020-11-21 11:27
Hi, I can not reproduce such behaviour. Can you tell me more, what should I do to reproduce it?

**Comment by photopea** [comment] 2020-12-03 13:07
I have to close it because of lack of details.

**Closed by photopea** 2020-12-03 13:07 UTC
