### ISSUE TITLE
Stitch together images doesn't work wont allow the simple copy paste process, says 'Clipboard Error: Read Permission Denied'

### ISSUE THREAD

**Issue by h1110** [photopea/photopea#3633] opened 2021-08-05 17:50 UTC
Stitch together images doesn't work wont allow the simple copy paste process, says 'Clipboard Error: Read Permission Denied'

**Comment by photopea** [comment] 2021-08-05 20:42
So the problem is with copy-pasting, right? How do you copy-paste? What should I do in Photopea to see such error? Did you give Photopea permissions to access the clipboard? Click the lock icon in your browser and give the permissions.

**Comment by photopea** [comment] 2021-08-10 19:11
I have to close it because of lack of details :(

**Closed by photopea** 2021-08-10 19:11 UTC
