### ISSUE TITLE
saveToOE doesn't seem to use the quality parameter (jpg or webp)

### ISSUE THREAD

**Issue by ilanreuben** [photopea/photopea#6120] opened 2023-10-21 21:04 UTC
Mac OS 10.14
Chrome 116.0.5845.187
Happens in incognito mode & normal mode

1. Go to www.photopea.com
2. Open a file
3. Send PP the command "app.activeDocument.sendToOE('jpg:0.05')"
4. Resulting file size (in my case) was 182,885
5. Repeat the command with 'jpg:0.99'
6. Same file size: 182,885
7. In each case, jpg was a valid & compete file
8. Quality parameter DOES work properly when entered in "export" dialog.

**Comment by photopea** [comment] 2023-10-25 15:57
BTW. it is "saveToOE", not "sendToOE".

I am not able to reproduce it with "saveToOE :(  When I increase the quality parameter, the file gets bigger.

Could you maybe share your PSD with us, for which it happens?

**Comment by ilanreuben** [comment] 2023-10-25 20:16
Oops! Yes, of course, saveToOE.

It happens no matter what file is open in Photopea.

I'm sure it must be something I'm doing wrong, since no one else has reported it. I'll spend a little more time on it and see if I can figure out what's happening.

Thanks.

**Comment by ilanreuben** [comment] 2023-10-25 21:08
OK, some new info:

If the original file is a JPG or PSD, then the quality param has no effect (no matter whether it's "webp:<quality>" or "jpg:<quality>")

If it is any other file type (I've tried PNG, WEBP, and TIFF), then the quality parameter DOES work correctly.

Let me know if you are still not able to reproduce this.

Thanks!

**Comment by photopea** [comment] 2023-10-25 23:39
Oh no, you are right. It happened only to files which are not in the sRGB color space. It should be fixed now :)

**Closed by photopea** 2023-10-25 23:39 UTC

**Comment by ilanreuben** [comment] 2023-10-26 16:36
It is fixed! Wonderful, thank you!
