### ISSUE TITLE
Clone Tool

### ISSUE THREAD

**Issue by Adryanaaaaaaaaaa** [photopea/photopea#2591] opened 2020-11-08 14:06 UTC
the Clone Tool has become too large for the part to be copied. A few days ago it was normal, now it is impossible to use. If I copy a small part, it becomes huge in the moment I paste. Sorry for my English, I'm Italian.

**Comment by photopea** [comment] 2020-11-08 14:23
Hi, I can not reproduce shuch behaviour. Could you show us a screenshot of what you mean? And how do you make it happen?

**Comment by photopea** [comment] 2020-11-10 10:59
I have to close it because of lack of details.

**Closed by photopea** 2020-11-10 10:59 UTC
