### ISSUE TITLE
My commands register more than one time????

### ISSUE THREAD

**Issue by FireTiger898** [photopea/photopea#5652] opened 2023-05-19 20:38 UTC
For some reason whenever I used a command it would do it many many many times. For example, if I create many layers and press CMD-Z one time, it would literally undo almost all of them. I don't know if I enabled something? But I really need a fix, because as a designer it's really annoying when I make one mistake and have to manually fix it. Thanks!

**Comment by FireTiger898** [comment] 2023-05-19 20:51
UPDATE: I seem to have found the fix? I was working on the web browser version of photopea, and that issue still persists until now, but for some reason, when I downloaded photopea, the issue no longer persists? Something like that, but it wouls still be easier to work on the web version, so a fix would still be GREATLY appreciated thanks again!

**Comment by FireTiger898** [comment] 2023-05-19 21:06
UPDATE 2: For some reason now the downloaded version is also doing the EXACT SAME THING. It's not a keyboard problem, since it's not like that on other software's, and it's just so weird. Please fix this!

**Comment by photopea** [comment] 2023-05-19 21:09
What should I do to see it happen myself? Could you try this first? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by FireTiger898** [comment] 2023-05-19 21:25
I saw that, and I tried every step! None of them would work!

**Comment by FireTiger898** [comment] 2023-05-19 21:25
I could show you a video maybe?

**Comment by FireTiger898** [comment] 2023-05-19 21:34
[New Recording - 5_19_2023, 5_30_37 PM.webm](https://github.com/photopea/photopea/assets/134103110/4405ba0c-c8bd-4f37-957e-5be6c0371cdf)

**Comment by FireTiger898** [comment] 2023-05-19 21:36
Please view without sound, some disturbing noises in the background lmao. So in the video you can see that using the default key board that is on the screen, the error persists. And it's getting kind of annoying --no offence.

**Comment by photopea** [comment] 2023-05-20 06:16
I just tried the same thing (On-Screen Keyboard in Windows 10, Photopea.com in Google Chrome), but it does not happen :(

Could you record the same video in the Incognito mode as a proof that you have all browser extensions disabled?

Also, what web browser and what operating system do you use?

**Comment by FireTiger898** [comment] 2023-05-20 13:21
I use Google chrome and Windows 10. It happens even if I don't use the on screen keyboard, I just do it because I can't record my keyboard only pressing CMD Z one time. But sure, I'll record on inccognito.

**Comment by FireTiger898** [comment] 2023-05-20 13:23
[New Recording - 5_20_2023, 9_21_50 AM.webm](https://github.com/photopea/photopea/assets/134103110/bfaa7926-9546-41b2-9d05-341226c8a679)

**Comment by FireTiger898** [comment] 2023-05-20 13:24
A thought just occurred to me. It might be a bug on my computer? But it probably isn't because I was even using the on screen keyboard, so there is no particular reason why it might fail?

**Comment by bluep55** [comment] 2023-05-20 14:42
In Photoshop, Control+Z is Undo/Redo
In Photopea, Control+Z is just Undo
A long press or continual pressing of this combination in Photopea will keep undoing.
That doesn't happen in Photoshop.

![Shortcuts](https://github.com/photopea/photopea/assets/118609932/fe405672-b692-4b09-a954-e0b8caa687b5)

**Comment by FireTiger898** [comment] 2023-05-20 20:17
No, the on screen keyboard only presses CMD Z one time, and then it's over, it's not getting held down.

**Comment by camoody1** [comment] 2023-05-20 20:36
@FireTiger898 Try this for me...

Create a new text layer and type the letter Z as just a piece of text. I want to see if the Z shows up a bunch of times or if it only types once.

**Comment by photopea** [comment] 2023-05-20 23:58
That is a great idea! Make a text layer in Photopea and press "Z" on a virtual keyboard. How many times it is typed?

**Comment by FireTiger898** [comment] 2023-05-21 18:58
Alright!

**Comment by FireTiger898** [comment] 2023-05-21 19:01
Ight, it only types one time, so it's probably a command issue??

[New Recording - 5_21_2023, 2_59_20 PM.webm](https://github.com/photopea/photopea/assets/134103110/913528b7-6579-4f23-968d-376b279ed94d)

**Comment by photopea** [comment] 2023-05-21 19:38
So pressing Ctrl+Z gets you to the beginning of editing every time, or only sometimes?

**Comment by Pt-home** [comment] 2023-05-22 05:30
Can you do that?
Open Photopea and DO NOT OPEN any document yet.
Press Ctrl+Z
You see alert.
If you have sticky keys, then it will float down
If there is no sticking, it will float up

**Comment by FireTiger898** [comment] 2023-05-22 19:34
@photopea only sometimes like, it registers many times, but not like, infinite times or anything
@Pt-home Sure, I'll try.

**Comment by FireTiger898** [comment] 2023-05-22 19:36
@Pt-home it floats up....

**Comment by Pt-home** [comment] 2023-05-23 11:50
> it floats up....
Maybe I'm wrong, but the problem starts after opening the document. Do you have something in Local Storage, did you install anything there? Or upload?

**Comment by photopea** [comment] 2023-05-23 13:59
What if you open a Notepad on windows, or MS Word, and try typing, and use Ctrl+Z? Does it skip just one step every time?

Also, can you open this: http://jsfiddle.net/p45f44zb/14/ , click into the white area and press shortcuts? It should tell you what keys are pressed at each moment.

**Comment by FireTiger898** [comment] 2023-05-23 19:35
Everything else is fine, like I said before, and it's just Photopea, but I'll try the link as well

**Comment by photopea** [comment] 2024-01-03 22:25
I will close it now. Some other user was using Photopea on a virtual machine, and a similar problem was caused by settings of their virtual machine.

**Closed by photopea** 2024-01-03 22:25 UTC
