### ISSUE TITLE
Ad blocking detection not working correctly

### ISSUE THREAD

**Issue by idavidmarshali** [photopea/photopea#5066] opened 2022-10-22 20:23 UTC
I use AdblockPlus Chrome extension to block adds on the web, bot i have disabled it on my favorite websites including photopea.com. When im using photopea it does show me ads but the site still gives me the notification that im using an ad blocker. please look into this.
![image](https://user-images.githubusercontent.com/34894450/197360947-f3ebb6b1-1cb7-497f-9baf-f68fefbae13c.png)

**Comment by vendoNZ** [comment] 2022-10-22 21:10
I received this reply from Photopea for the same issue yesterday:
"Your adblock is probably lying to you. It is still enabled and is blocking ads. Otherwise, we would not be able to detect it. Disable the extension completely instead of asking it to not block ads and hoping it will not. Or switch to a different adblock."

Try going to Chrome's Extensions: chrome://extensions/ then toggle the bottom right switch to disable, this seemed to work for me

**Comment by photopea** [comment] 2022-10-22 21:24
A website can not know what browser extensions you are using, if any at all.

Did you try to disable your extension completely? If a website runs differently with your extension than without it, your extension is still "doing something to a website". Does it make sense?

**Comment by idavidmarshali** [comment] 2022-10-23 11:34
might i add im using Edge, and by default edge has some ad/tracking blocking.
so i disabled the extension from edges extension setting and disabled edges own ad blocking but the website still showed that im using an adblocker. i don't know how photopea detects ad blocking (and i don't know much about web dev) but after looking at the console i found a warning that said "Tracking Prevention blocked a Ping request to google-analytics.com" which i thought might be the problem. so i disabled tracking prevention on photopea and although the warning was not there anymore, the site still said Ad blocking detected.
also i don't know how many different types of ads photopea shows but from my perspective it is showing me advertisements.

**Comment by photopea** [comment] 2022-10-23 11:57
We detect ad blocking simply when we can not connect to the server of our ad provider. When we detect ad blocking, Photopea shows pictures of my ads, which I made in the past, like Dino Hunt 2. I do not get any money when you click and play these games.

I just opened Photopea.com in the latest Edge and ads are shown correctly ("Ad blocking detected" is not there). I never changed any settings in my Edge since installing it.

**Comment by photopea** [comment] 2022-10-23 11:59
Please, do not block ads in Photopea. I literally depend on them. There would be no Photopea without people watching ads.

**Comment by photopea** [comment] 2022-10-23 12:01
I wish that at least 0.1% of our users paid for Photopea (1 in 1000), but we are still far from that :(

**Comment by idavidmarshali** [comment] 2022-10-23 12:14
thats what im trying to do, im trying to fix my ad blocking issue cause i want to support photopea atleast by ads. cause im in iran i don't have anyway to pay for premium. anyway i think i found a way to make it work, cause now instead of saying ad blocking detected it says Change consent.

**Comment by xan2622** [comment] 2022-10-23 13:01
A lot of people have reported issues with ads, with their adblocker or asked Ivan to remove the "empty sidebar" on the right.

But ads in Photopea are not necessary blocked by the AdBlocker but because the user (the first time he/she went to the Photopea website) refused the Cookies. THAT also makes ads not to show (even if there is no activated adblocker).

**Comment by xan2622** [comment] 2022-10-23 13:02
A lot of people have reported issues with ads, with their adblocker or asked Ivan to remove the "empty sidebar" on the right.

But ads in Photopea are not necessary blocked (or hidden) by the AdBlocker but sometimes because the user (the first time he/she went to the Photopea website) refused the Cookies. THAT also makes ads not to show (even if there is no activated adblocker).

**Comment by popbee** [comment] 2022-10-28 12:45
I did some tests with Google Chrome and the extension AdBlock on Windows 11.

The factor that affected this (for me) seems related www.PhotoPea.com's *Service Worker*.  If I delete the Service Worker the Ads show up after a page refresh. (But then refreshing the page again goes back to seeing no ads).

I do not know why. I suspect that the service worker keeps some state that it shouldn't and we can't recover unless we remove it.

Maybe @photopea has an idea?

Steps to reproduce:
1- Use Google Chrome with AdBlock installed and fully enabled.
2- open photopea, ads will be blocked - this is "normal".
2- Disable AdBlock only for the photopea site in mode "Always".
3- Refresh the page. Ads will still be considered blocked. In Network tab, you can see the google syndicate .js has a weird error.
4- Remove the Service Worker (by clicking in the little lock left of the URL, select Cookies, expand www.photopea.com, select Service Worker and click Remove & Done.
5- Refresh the page. Ads will show.
6- Refresh the page. Ads will not show. (go to step 4)

I believe this is a typical use case for a lot of users. @photopea you rely on the money, this is your income. I think it's in your interest to "invest" some debugging time to workaround this type of problem. All sites that I know work fine in this use case, just yours that fails. Yes the extension probably does something but given the stakes, I would try if I was you.

After step 6, even after removing the extension completely and refreshing the page, it still fails. You have to remove the Service Worker for it to "recover". (step 4)

**Comment by photopea** [comment] 2022-10-28 13:02
are you talking about this Chrome extension? https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom

1) I go to about://extension and enable the AdBlock. I open www.Photopea.com, I see "ad blocking detected"
2) I go to about://extensions and disable the AdBlock. I reload www.Photopea.com (which I did not close), ads are shown correctly.

I have a strong suspicion, that when you tell your AdBlock to "allow ads" on some website, it actually replaces the ads on a website with their own ads. So when you click these ads, AdBlock is making money (and not the author of a website). There is no way for the average user to tell, ads look like ads.

**Comment by vendonz** [comment] 2022-10-28 18:18
An alternative might be to create your own ad network, to display ads as the fallback when adblock is detected, instead of the games you display now. You don't need to get too complicated with CCP or CPI just a fixed monthly fee which would determine priority and frequency, e.g. $100 a month, $1,000, a month, $10,000 a month etc. and let the advertiser choose their tier and track clickthroughs for effectiveness. You could add clicks and impressions stats if it proves viable. The only thing I would suggest would be requirement is IP to country so advertisers can select their countries to target. Since you have so many users and impressions, and your audience is quite targeted you are very attractive to advertisers, and I am sure would be way cheaper than Google ads or FB ads. You would appeal to font designers, SAAS businesses, app devs etc. If you could target country I would be interested in advertising my SAAS, at say a $100 a month tier to try it out. So I would deisgn and upload the ad, you would review and accept it, then I would be charged the full amount upfront and the ads would start showing. The more stats you could provide advertisers the more you would attract so they know what they are getting and can estimate the conversion rates. But initially I don't think you need to do that since you wouldn't have the data anyway, just test the waters to gauge interest.

**Comment by photopea** [comment] 2022-10-28 21:42
We already have it here: https://www.photopea.com/ads/  . It would take millions in money to create a sufficiently sophisticated ad system. Until then, "our own ads" will make 10x less money than standard ads, as advertisers can not target ads precisely, or compete with each other.

**Comment by vendonz** [comment] 2022-10-30 19:30
thanks Ivan, I didn't see a link anywhere on www.photopea.com before I commented. I also googled it with searches like site:https://www.photopea.com/ ads and "photopea ads" but just came up with reddit pages nothing from your website.  Even if I google photopea "www.photopea.com/ads" google hasn't got that page in its index. So maybe put a link to it somewhere like in About.

The google ads I have seen are not well targeted (to me at least) mostly casino and other garbage, although there are a few from my country. That's why the conversion rate is so bad (.1%). Plus some of the ads are terrible, like just say click to download.

I guess there's also that you don't serve data currently which is nice to keep costs down whereas your own ads incur bandwidth, although you could use a cdn.

$3000  (with minimum 30 days) to serve ads for a month is out of my league and would be for 99.9% of advertisers. 

I'm not convinced it would cost millions to develop. You could hire someone to do it.

![image](https://user-images.githubusercontent.com/116385416/198897876-55e4b113-827f-4d1b-a903-2a813fd67965.png)

**Comment by photopea** [comment] 2022-10-30 20:00
We offer around 300 ad clicks for $100, $0.33 per impression, that is multiple times less than you would pay on a regular ad network.

If you could develop an ad network, I would be glad to switch to using it!

**Comment by vendonz** [comment] 2022-10-30 20:21
$0.33 per impression - yeah that's per click which is fine, not great but similar I guess if you average it out its what you pay on Google ads. Since you are flat rate and not PPC, and every ad would have a different conversion rate, you are really charging per impression, so that works out to be about $0.0003 per impression or $1 per 3,000 impressions. A good well designed and targeted ad should be able to get more than 3 clicks.

Let me think about it, I have made a very basic ads option on my website but I get only a tiny fraction of the views you get. But like you I am struggling to get people to pay to use my app by subscription, and I don't qualify for Google ads.

**Comment by photopea** [comment] 2022-10-30 20:52
I can put an iframe of your website into Photopea for a fixed price per month. And you can monetize it as you wish, even make 10x more money than you pay me, what do you think?

**Comment by vendonz** [comment] 2022-10-30 21:38
interesting, OK let me think about it

**Comment by photopea** [comment] 2022-11-06 14:18
I will close it, since our ad blocking detection works correctly.

**Closed by photopea** 2022-11-06 14:18 UTC
