### ISSUE TITLE
Opening a small box when I use the text tool

### ISSUE THREAD

**Issue by nivedhasugumar** [photopea/photopea#2204] opened 2020-06-09 08:13 UTC
Hello
        I don't know is this only for me. Today, when I started using the text tool in Photopea, a small black colored box with 0% transparency on the top left corner. I can't click below it. It was really frustrating. Kindly solve it, because Photopea plays a very important role in my career.

Thank you,
Santhosh.
![Capture](https://user-images.githubusercontent.com/22032548/84123160-1508db00-aa57-11ea-80fb-ed82e45b4c2d.JPG)

**Comment by photopea** [comment] 2020-06-09 08:17
Hi, this is really strange. Can you update your web browser and disable all browser extensions?
What version of the browser are you using?

**Comment by nivedhasugumar** [comment] 2020-06-10 05:56
Thank you, it worked.

**Comment by nivedhasugumar** [comment] 2020-06-10 05:57
By the way, I am using Google Chrome version 83.0.4103.97 (Official Build) (64-bit)

**Comment by photopea** [comment] 2020-06-10 07:47
So it was fixed by updating your browser?

**Closed by photopea** 2020-06-10 07:47 UTC

**Comment by nivedhasugumar** [comment] 2020-06-10 07:58
And by disabling the Chrome extensions

**Comment by photopea** [comment] 2020-06-10 08:00
You can enable back some extensions, if you need them. There was probably just one of them, which caused problems.

Disabling all extensions is the fastest way to tell, if the problem is because of extensions, or not.
