### ISSUE TITLE
erases progress

### ISSUE THREAD

**Issue by goofyaaah123** [photopea/photopea#6834] opened 2024-06-08 13:59 UTC
freezes and says low memory refresh or close page and when i refresh it erases the majority of my progress

**Comment by goofyaaah123** [comment] 2024-06-08 18:58
it has happened about 10 times since i reported the bug

**Comment by photopea** [comment] 2024-06-08 22:14
What should i do to see the error? If you are editing a 300 MB PSD with 2 GB of RAM, that is simply not enough.

**Comment by goofyaaah123** [comment] 2024-06-09 13:03
i dont know what that means

**Comment by goofyaaah123** [comment] 2024-06-09 13:48
it usually happens if i leave the tab up for a while and right before it happens photopea is unrepsonsive i can only move things but i cant edit them or move layers over eachother

**Comment by photopea** [comment] 2024-06-09 16:23
I need some steps to reproduce this behaviour. 90% of problems with Photopea are caused by browser extensions, so I recommend disabling all browser extensions which have permissions to modify Photopea.

**Comment by photopea** [comment] 2024-06-26 11:53
I have to close it because of lack of details.

**Closed by photopea** 2024-06-26 11:53 UTC
