### ISSUE TITLE
Firefox only : "Alt" key behaving  + Adjustment layer blocking layers

### ISSUE THREAD

**Issue by jeancallisti** [photopea/photopea#1830] opened 2019-12-03 12:28 UTC
First of all I'd like to say what a FANTASTIC piece of software Photopea is. 
It saved my life so many times when I needed a _full-fetched_ Photoshop (not just a "good" graphical editor) but didn't have Photoshop.

I'm having the following issues and it seems to me that they havn't been reported yet.

### Issue #1 : 
- Very often the software is behaving as if the Alt key is pressed. 
- I have to press Alt myself two times to force-unhold it
- Some operations make this state behavjour more prone to happen : After using the selection tool for example
- Could it be when there is a lag between a mouse action and the result? (e.g. using "magic wand" to select a large area of the image). It means you wouldn't notice it on a fast computer but it would happen all the time on a computer where Javascript takes ages to execute an action.

### Issue #2 :
- Add an adjustment layer to a layer (any adjustment layer, e.g. Curves)
- Make the adjustment layer's Properties panel appear and change the settings (e.g boost the contrast by fiddling with the curve)
- In the layers "stack", try to drag and drop any layer to move it above or below any other layer
**Expected** : The layers can be moved up and down normally
**Observed** : The layers seem to be locked in position. Everything else in the software seems to work properly. You can even delete some layers and create layers. 

Again I believe that this might be the software's GUI locking itself in some inconsistent state because of a lag in processing the adjustment layer's filter.

**Comment by photopea** [comment] 2019-12-03 12:45
Hi, thank you very much!

Issue 1: I [reported it to Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1568130) four months ago, but it seems like nobody cares. I would recommend you to switch to better browsers, like Google Chrome.

Issue 2: I could not reproduce it in firefox :( all layers can be dragged freely. Could you maybe record a short video of what happens? It is not happening in Chrome, right?

**Comment by photopea** [comment] 2019-12-12 11:03
I will close it because of lack of details.

**Closed by photopea** 2019-12-12 11:03 UTC
