### ISSUE TITLE
What Happened To My Pen Tool & Shapes?!

### ISSUE THREAD

**Issue by TheMouseAvenger** [photopea/photopea#5222] opened 2023-01-01 13:31 UTC
I'll write down the basic gist of my dilemma, & add captions to my attached pictures shortly (I woke up at 3:00 A.M., & I need to catch up on my sleep).  Here's the pictures in question:

https://i.ibb.co/sFv8YNp/Where-Did-The-Nose-Go.png
https://i.ibb.co/yVdT0vm/Regular-Shapes-Tool-Works.png
https://i.ibb.co/c3zZSPJ/Layer-On.png
https://i.ibb.co/0Djhmfq/Layer-Off.png
https://i.ibb.co/1JfN0xb/Drawing-Shape-With-Pen-Tool-Turns-Out-Translucent.png
https://i.ibb.co/87BBJn5/Drawing-Shape-Is-Still-Translucent-On-White-BG.png

**Comment by TheMouseAvenger** [comment] 2023-01-01 21:18
So, can anyone please help me ASAP? :-) I'd really like to get this picture finished. :-(

**Comment by camoody1** [comment] 2023-01-01 21:30
Could you please share your Project and post the link to it here so we can see exactly what you're dealing with?

**Comment by photopea** [comment] 2023-01-02 00:27
Please, tell us, if any of this happens in a web browser with all browser extensions disabled (e.g. in the Incognito mode).

Such bugs could be caused by your browser extensions.

**Comment by TheMouseAvenger** [comment] 2023-01-02 03:53
> Could you please share your Project and post the link to it here so we can see exactly what you're dealing with?

Sure! :-) I'll put it on my Google Drive.

(does so)

And here it is!

https://drive.google.com/file/d/14CNzNgQzR-1ad24xG8DAoFc7V_DK3Hj2/view?usp=share_link

If you have any more questions, feel free to ask me!

**Comment by TheMouseAvenger** [comment] 2023-01-02 03:54
> Please, tell us, if any of this happens in a web browser with all browser extensions disabled (e.g. in the Incognito mode).
> 
> Such bugs could be caused by your browser extensions.

Oh, I'm using Microsoft Edge, & I only use one extension for this (in comparison to my Google Chrome browser with several extensions!)--that being AdBlock.  Does that help?

**Comment by camoody1** [comment] 2023-01-02 05:04
> > Could you please share your Project and post the link to it here so we can see exactly what you're dealing with?
> 
> Sure! :-) I'll put it on my Google Drive.
> 
> (does so)
> 
> And here it is!
> 
> https://drive.google.com/file/d/14CNzNgQzR-1ad24xG8DAoFc7V_DK3Hj2/view?usp=share_link
> 
> If you have any more questions, feel free to ask me!

I'll be honest with you, you have SO many layers with duplicate shapes and rasterized images, some stacked on top of each other, some slightly off kilter, some hidden behind a background layer... it's truly not at all clear what you're trying to achieve here. So, it's very hard to tell exactly what it is you think isn't working. I feel like if you cleaned out about half these layers, things would make a lot more sense.

Having said that, I'm not one of the developers. I'm just a user who tries to answer some questions on the Photopea subreddit and I found my way here the other day for my own help. Perhaps we should move this discussion over there. Unless the developer has some better insight into what your asking for.

**Comment by photopea** [comment] 2023-01-02 09:42
I think you have sent us a different file. Here: https://i.ibb.co/c3zZSPJ/Layer-On.png , there is "Layer 16 Copy" below "Layer 15", but in your PSD, there is "Layer 14" below "Layer 15".

Regarding the "nose going away", You have a layer "Layer 15", which is fully opaque (blue) and covers everything below it: https://i.imgur.com/IJbfdku.png . So only three top layers of your document can be seen in the result.

I could not see any incorrect behaviour. Please, tell me, what exactly should I do after opening your PSD to see any "wrong behaviour".

**Comment by TheMouseAvenger** [comment] 2023-01-04 04:09
> I think you have sent us a different file. Here: https://i.ibb.co/c3zZSPJ/Layer-On.png , there is "Layer 16 Copy" below "Layer 15", but in your PSD, there is "Layer 14" below "Layer 15".
> 
> Regarding the "nose going away", You have a layer "Layer 15", which is fully opaque (blue) and covers everything below it: https://i.imgur.com/IJbfdku.png . So only three top layers of your document can be seen in the result.
> 
> I could not see any incorrect behaviour. Please, tell me, what exactly should I do after opening your PSD to see any "wrong behaviour".

Oh, I must have accidentally deleted "Layer 16 Copy" after I made the picture.

As for the "Layer 15", I put that in there so I could make it easier to symmetrize the sides of the teddy bear's head.  Just ignore that one. :-)

Here's a version of the PSD without any duplicate or unnecessary layers:
https://drive.google.com/file/d/1fsz1LqpyOmrV9AO1xEZo4Gr7Vvz7go4I/view?usp=share_link

As for what you should do after opening the PSD, try drawing a colored-in shape with the pen tool on either a new layer, or any of the layers that already have something on them (you'll have a far-likelier chance of repeating the problem if you do the latter, in which case you might need to try checking every layer in order to pinpoint exactly where the problem originated).  If the drawn shape has a translucent fill, but has opacity set to 100, that means that something is wrong with either one of the layers or something that I haven't noticed yet.

Hope this all helps! :-) And, of course, feel free to let me know if you have any more questions or anything of the like.

**Comment by camoody1** [comment] 2023-01-04 05:08
When I draw a new filled shape as the top layer in the stack, I have absolutely no problem at all. But when I start drawing shapes on layers in the middle of the stack, the shape appears to be "empty" because it's being covered up by a layer above it in the stack. For just the bear's head, you have four separate layers with the same drawing. I don't understand why your layers set that way, but I'm convinced that is the main contributing factor to your issue. You've got so many layers in your stack with bits and pieces of drawings, you really need to be careful where you're adding the new shape in your layer stack. If you're not careful of what's above it in your layer stack, that shape could appear either empty. As for the translucent shape, click on that shape layer in the stack and check both your Opacity and Fill percentages. The only way I got my shapes to look translucent like your example is if I turned my Fill for the layer down to around 40%.

**Comment by photopea** [comment] 2023-01-04 06:15
You are telling me to "draw something to see the problem". I draw something, but I dont see any problem. You must tell me what problem should I see, attach screenshots of what exactly you dont like, or what you expect to be different.

So far, I think you simply dont understand how layers work. If you have a layer B, and you make a layer A below it, the content of A will be covered by a layer B.

I will close it now, as I think it is not a bug in Photopea, but we can keep discussing it.

**Closed by photopea** 2023-01-04 06:15 UTC

**Comment by TheMouseAvenger** [comment] 2023-01-05 01:05
> 

OK, I'll give it a look-see.

**Comment by TheMouseAvenger** [comment] 2023-01-07 02:25
It worked! ^_^ Thanks, guys! :-)
