### ISSUE TITLE
Zoom Glitch

### ISSUE THREAD

**Issue by itsJavaCoder** [photopea/photopea#3036] opened 2021-03-18 12:52 UTC
When I opened photopea, it started zooming out and when I tried to zoom in it wouldn't stop zooming in. I just updated chrome so Is this the problem?

**Comment by photopea** [comment] 2021-03-18 12:54
Hi, I need to reproduce the problem to be able to fix it.

How exactly do you zoom in? Do you mean using the Zoom tool and clicking with a mouse on a document?

**Comment by itsJavaCoder** [comment] 2021-03-18 17:46
I tried use CTRL+- and the zoom tool but I think its because its just lagging. I slowly zooms out and slowly zooms in.

**Comment by photopea** [comment] 2021-03-18 19:46
Can you update your web browser? Or is it updated?

**Comment by JSmartDigital** [comment] 2021-03-23 00:49
I have the same issue, I noticed that the transition that has been implemented on zooming in and out lags quite a lot on my device. 

https://www.loom.com/share/63d807fabc4643bb98d5c833f828b18e

I think removing the transition on zoom would speed it up. 

https://www.whatsmybrowser.org/b/CJ8G5

**Comment by JSmartDigital** [comment] 2021-03-23 14:36
Hi @photopea 
Incognito does the same ting as well: https://i.imgur.com/FfnW4fz.gif

**Comment by photopea** [comment] 2021-03-23 14:52
That is so strange. I also have Chrome 89 and this never happens.

Is your chrome a stable release, or some beta release? Have you configured any flags or other advanced settings? Is your WebGL on? Check in More - Use WebGL. Also, can you try it in some other borwser? Does it work the same in them?

**Comment by JSmartDigital** [comment] 2021-03-23 18:50
@photopea

My Chrome should be stable, I update as notified. I have never visited the Flags section or any other advanced settings, I'm pretty sure, but WebGL is disabled. Tell me if it should be enabled... https://i.imgur.com/BgY2OX0.png

**Comment by photopea** [comment] 2021-03-23 19:19
Your screenshot is for "WebGL Draft extensions", not for WebGL itself. Photopea does not require any WebGL extensions, the basic WebGL is enough.

Just curious, is your Photopea opened in a browser for several days? It worked like in your video five days ago, but I fixed it five days ago. So if you did not reload Photopea since then, please, try to reload it.

**Comment by dentistformyeye** [comment] 2021-03-23 19:39
> I have never visited the Flags section or any other advanced settings, I'm pretty sure, but WebGL is disabled. Tell me if it should be enabled... https://i.imgur.com/BgY2OX0.png

WebGL draft extensions are unstable versions of WebGL extensions, so that flag doesn't control the WebGL setting itself. There is no way to turn off WebGL for the entire Chrome browser unless you use an extension, but Photopea allows you to disable WebGL for Photopea's website only.
If there is a checkmark here next to the More > Use WebGL setting in Photopea, then you know WebGL is definitely enabled.
![image](https://user-images.githubusercontent.com/51429646/112206713-a0b9b580-8bec-11eb-9b51-767ccd93bae8.png)

WebGL isn't strictly necessary, but you should keep it enabled to make Photopea work more smoothly. However, for me, turning off WebGL doesn't make zooming as slow as it was in your GIF, so I think there's some other problem causing Photopea to be slow for you. Maybe your computer's CPU, GPU, or RAM is under high pressure.

**Comment by JSmartDigital** [comment] 2021-03-23 19:59
Turning off WebGL fixed the issue for sure, I didn't realize it was in the Photopea menu.
My resources are generally under control, I see other signs across my machine as I work if they aren't https://i.imgur.com/ASNUuv8.png

**Comment by photopea** [comment] 2021-03-23 20:26
The Zoom animation should finish in 0.3 seconds, no matter if WebGL is On or Off.

Unless you use Photopea from a week ago. Are you keeping Photopea.com opened in a browser for the whole week? If yes, could you close and reopen it again, to use the latest version?

**Comment by JSmartDigital** [comment] 2021-03-23 20:38
@photopea thanks, it definitely causes the issue, what else is going on I'm not sure.. https://www.loom.com/share/171a63b161034b5eb402bd1cdfa09e0b

I have cleared the data for Photopea and have closed it many times over the past week, done a hard refresh, and did so intentionally time and restarted Chrome. So it's not the same version loading from when you had it there.

**Comment by photopea** [comment] 2021-03-23 21:01
@JSmartDigital The Zoom is still slow in your case with WebGL off. It should be much faster.

What is the resolution of your photos? is it faster when you open photos 500x500 pixels?

Could you try it in some other browser? E.g. MS Edge?

**Comment by JSmartDigital** [comment] 2021-03-24 02:40
@photopea MS Edge behaves the same. The image I was trying was about 2400 x 3200. I tried a 512x512 and it did the same. I closed everything on my computer except this github tab and Photopea, and it did speed up a little, but still the same behaviour with WebGL on or off. 
https://www.loom.com/share/918f9324f8144e9ea894634c4e55e1c4

**Comment by photopea** [comment] 2021-03-24 09:10
@JSmartDigital I am soooooo sorry. There really was a bug on my side, and I fixed it. Now, the zoom animation should always take 0.12 seconds (even in your case, both with and without WebGL).

**Comment by JSmartDigital** [comment] 2021-03-24 14:00
@photopea that's fantastic news, I'm glad I could help you track it down and solve it, no worries at all! You have a great product, and I just confirmed it works very well now, regardless of WebGL being selected or not.

**Comment by photopea** [comment] 2021-03-24 14:19
BTW. Photopea is still extremely laggy with WebGL enabled in your case. Your experience could be so much better if WebGL worked faster.

Can you open about://gpu in your browser? Is everything Hardware Accelerated? If not, could you update your GPU drivers? You probably have Intel HD graphics, so just install the latest drivers from their website.

**Comment by JSmartDigital** [comment] 2021-03-24 14:34
@photopea It did speed up actually. But what you say is true, however: https://i.imgur.com/Qh8lNgg.png

I'll check out updating the drivers, but actually the machine is quite old as far as computers go, I run a new SSD for the hard drive but the graphics card is original.

**Comment by photopea** [comment] 2021-04-04 10:17
The issue with the zoom should be fixed now.

**Closed by photopea** 2021-04-04 10:17 UTC
