### ISSUE TITLE
Transform causes crash

### ISSUE THREAD

**Issue by doggard** [photopea/photopea#145] opened 2017-03-16 19:07 UTC
Hello, I've just started using photopea and it's really great!
My issue it this - after performing a free transform, the PSD becomes unresponsive. The UI seems to work okay, but no commands are being executed. Can't edit, zoom, select, etc... 

EDIT  : I merged all non-essential layers AND turned of webgl, and it seems to work now.
hp chromebook 13 g1 m3

**Comment by photopea** [comment] 2017-03-16 22:16
Hi, can you describe some steps how to reproduce it? Maybe share your file (or some similar file)?

Free Transform does not use WebGL. WebGL is used just for blending the layers. That is very strange.

**Comment by doggard** [comment] 2017-03-17 00:46
I've attached the file I was working with. I pasted a bitmap (some lovely shutters) into a new layer and transformed them to suit the image. After the transformation was complete I clicked the check, and then everything in the image viewport stopped responding.
I've attempted to reproduce the issue while recording a video, but frustratingly it seems to be working fine now (which is good I suppose!) .
[houseIdeas2.zip](https://github.com/photopea/photopea/files/849368/houseIdeas2.zip)

**Comment by photopea** [comment] 2017-03-23 19:34
I tried to do the same, it also seems to be working :(  can you try to do it again the same way from the beginning (with WebGL on) to see if it happens again?

**Comment by photopea** [comment] 2017-03-27 10:47
I have to close it because of the lack of details :(

**Closed by photopea** 2017-03-27 10:47 UTC

**Comment by doggard** [comment] 2017-03-27 13:45
Yes, Sorry I did not have the time to provide details. Thank you for looking into the issue.

**Comment by photopea** [comment] 2017-03-27 14:54
Can you try to reproduce it? make it happen again?

**Comment by doggard** [comment] 2017-03-27 16:02
Okay, I've been working with the same file again for a few minutes. WebGL is enabled. I pasted an image to a new layer, and applied a layer mask. I then inverted the layer mask, and then tried to undo (alt-ctrl-z). Alt-ctrl-z does not work on a chromebook as it is a system toggle for something else and I never remember this. After pressing alt-ctrl-z the psd becomes unresponsive.

**Comment by photopea** [comment] 2017-03-27 21:02
What do you mean by invertng the mask? How do you do it? I just noticed, that Invert and other adjustments do not work on masks :(

**Comment by doggard** [comment] 2017-03-28 12:50
I was attempting to invert the mask colour by using ctrl+i
