### ISSUE TITLE
[Feature request] handle webdav based storage

### ISSUE THREAD

**Issue by setop** [photopea/photopea#4966] opened 2022-09-03 07:39 UTC
Like Photopea supports various third-party storage (google drive, one drive, drop box), it would be able to store files on [webdav](https://en.wikipedia.org/wiki/WebDAV)-compatible storage provider, like nextcloud or owncloud to name a few.

The benefit is you can choose a storage provider that is not a centralized service by a big corp. So you can gain sovereignty on your data. There are tons of nextcloud/owncloud providers. Some companies are hosting their own for their employees/partners.

related : #1804, #760.

**Comment by photopea** [comment] 2022-09-07 09:13
So how should it work? You click on "WebDAV" on the left side (right under the Dropbox), you enter some credentials, and you see your storage? 

As I understand, WebDAV is a protocol, while Nextcloud and Ownlcould are PHP libraries, which implement the protocol. Are you aware of any free storage provider, who uses WebDAV, so that I can use it for testing?

**Comment by setop** [comment] 2022-09-09 18:18
> You click on "WebDAV" on the left side (right under the Dropbox), you enter some credentials, and you see your storage?

Yes, exactly what I had in mind !

> Are you aware of any free storage provider, who uses WebDAV, so that I can use it for testing?

Yes. A [bunch of providers](https://www.chatons.org/en) are providing [nextcloud service](https://stats.chatons.org/software-nextcloud.xhtml) for free or small fee. I'm part of them and [I can provide](https://stats.chatons.org/kaihuri-cloud.xhtml) you with one or two owncloud accounts for free for your tests.

**Comment by photopea** [comment] 2022-09-22 18:28
We have a problem - it seems like most of the WebDAV servers do not support CORS headers. So it is not possible to connect to them form a web application running at another domain. Are you aware of this problem? Why dont the Nextcloud / Owncloud simply enable CORS by defautl? Non-web application already ignore CORS headers, so it does not compromise the security.

**Comment by photopea** [comment] 2022-10-14 09:17
I will close it now, as most of WebDAV servers do not support CORS.

**Closed by photopea** 2022-10-14 09:17 UTC

**Comment by setop** [comment] 2022-10-14 11:21
I found [webdav-manager.js](https://github.com/kd2org/webdav-manager.js) which propose webdav client in the browser.

**Comment by photopea** [comment] 2022-10-14 12:48
A webdav manager is not a problem. The problem is with CORS, see https://github.com/kd2org/webdav-manager.js#cors 

You need to set this on your WebDAV server. Does your webdav server have these headers?
