### ISSUE TITLE
Ads pop-up windows not opening or taking long before opening

### ISSUE THREAD

**Issue by AnthonyZDavis** [photopea/photopea#6844] opened 2024-06-10 16:46 UTC
Your Operating System: Windows 11
Your Web Browser: Google Chrome / Mozilla Firefox
The problem happens in the Incognito Mode, too: Yes

1. Go to [www.photopea.com](http://www.photopea.com/)
2. Open any image
3. Select the **Magic Replace** tool
4. Choose any area of the image
5. Input the prompt
6. After selecting **Replace**, you'll be prompted with the choice of switching to Premium or watching 2 free ads
7. Press **Ok** to watch the ads
8. The ad pop-up window either won't open, or it'll take a long time before actually opening

**Comment by camoody1** [comment] 2024-06-10 19:50
Issues like this are often caused by ad blocker extensions you have running in your browser. Try using this tool in In Cognito mode. If it works there, you'll need to disable all of your browser extensions and then re-enable them one at a time to figure out which one is causing you problems in Photopea.

**Comment by photopea** [comment] 2024-06-11 08:20
Are you sure it happens to you in the Incognito mode? In what country are you located? Could your internet provider be blocking ads?

**Comment by photopea** [comment] 2024-06-26 11:52
I have to close it because of lack of details.

**Closed by photopea** 2024-06-26 11:52 UTC
