### ISSUE TITLE
Ads causing lag and stuttering 

### ISSUE THREAD

**Issue by lMPERlUM** [photopea/photopea#6121] opened 2023-10-23 00:30 UTC
Your Operating System: Windows 10
Your Web Browser: Chrome 
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Open image, blank template, etc.
3. Pan and zoom around, type, use sliders, move images, etc. 
4. When new ads are loaded on the right a 2-3 second stutter is noticeable. New ads are loaded every 5-10 seconds meaning there is intermittent stuttering every so often to the point of unusability. 

In the below video observe how I use the sliders and how smooth they are until an ad is reloaded. The stutters are consistent with the ads reloading.  I found the source of the problem by trying an ad blocker and it remedied the issue. I refrain from using adblocker and have no problem with ads while I work, but this problem became prominent recently (as in 1-2 months ago). I removed all my extensions. Issue is both in browser and app. 

https://www.youtube.com/watch?v=xFVm8BaLKn0

**Comment by photopea** [comment] 2023-10-23 02:11
Thanks a lot! I will discuss it with my ad provider and we will try to improve the overall experience.

**Comment by DuckyMacfly** [comment] 2023-10-23 05:21
yeah, I don't mind the ads but it's recently really slowing down the performance. I'd be using the lasso tool and a stutter happens which makes my mouse skip and I end up having to re-lasso everything.

**Comment by photopea** [comment] 2023-10-24 16:14
@lMPERlUM btw could you tell us, what CPU exactly does your computer have? I do see that ads use the CPU a lot, but I can not reproduce a behaviour from your video (the ad totally freezing the editor for half a second). I tried it even on my old Macbook Air from 2015.

**Comment by lMPERlUM** [comment] 2023-10-24 18:42
@photopea Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz   1.19 GHz 8GB RAM, it is a 2021 Lenovo Ideapad 15IIL05

**Comment by photopea** [comment] 2023-10-24 20:49
BTW I am looking at your video. There should be a "Change Consent" button under our ads (it is missing). Do you use Photopea with browser extensions? Could you show us what you see after clicking this button?
![image (7)](https://github.com/photopea/photopea/assets/15955558/d370f10e-ffbc-4916-9828-8aebe6ef8fe6)

**Comment by lMPERlUM** [comment] 2023-10-24 21:59
@photopea No modifiers other than dark mode and some zoom app extension (which i dont need anymore). It is probably a contributor because now removing dark mode noticeably improved performance by a little bit. But there is still the same stuttering and lag with some of the tools and its not as smooth as with an ad blocker and still laggier than previously (I could compare the performances).

**Comment by jordi-gb** [comment] 2023-10-27 05:31
yes, the ads are slowing down and freezing the installed web-app, really annoying...

**Comment by photopea** [comment] 2023-11-06 15:24
We have removed the video ad, which could be slowing down Photopea on some old computers.

It seems like replacing one ad with another always freezes Photopea for half a second. It should be optimized by Google, we will get in touch with them.

@IMPERIUM does it really bother you that much, when Photopea freezes for half a second each 20 seconds? Have you thought about getting a Premium account? The number of users paying for Photopea is less than 0.1%. I think the only way to encourage people to pay for Photopea is to make the free version more hard or more uncomfortable to use, or to remove the free version completely.

**Comment by kloworks** [comment] 2023-11-07 22:19
> @lMPERlUM does it really bother you that much, when Photopea freezes for half a second each 20 seconds? Have you thought about getting a Premium account? The number of users paying for Photopea is less than 0.1%. I think the only way to encourage people to pay for Photopea is to make the free version more hard or more uncomfortable to use, or to remove the free version completely.

my personal opinion, to remove the free version ,make a desktop version.
purchase it one time with one year maintenance, with the option if they want subscription.

users moved away from adobe to affinity or other app because of the subscription. I don't use affinity with one reason they don't support RTL . 
also photopea the brush pressure I notice not great and I think most of the web app have this issue.
+ I cant use sync with 3Dcoat. since its not .exe

so yeah maybe think about moving forward to desktop app. see other examples like affinity, clipstudio, krita etc...

**Comment by photopea** [comment] 2024-01-09 15:02
@IMPERIUM : could you test your computer with PeaMark? In Photopea, press More - PeaMark. What score do you get?

I was testing this right now, and on my pretty average laptop, the "stuttering" is like 0.05 seconds, definitely not as long as in your video.

**Comment by photopea** [comment] 2024-03-04 19:44
I will close it for now.

I am aware, that our ads might slow down your computer, especially if it is more than 8 years old. We would like more people to get a Premium account, to reach at least 0.1% of paying users.

**Closed by photopea** 2024-03-04 19:44 UTC

**Comment by photopea** [comment] 2024-05-27 11:41
Each ad should have the "X" at the top right corner. Click it and then, click "Stop seeing this ad". The ad should never be displayed again.

**Comment by ppamorim** [comment] 2024-06-26 13:40
@photopea It's freezing on my MBP M1P, this is very odd. I choose to display ads to help the software but it's very difficult to use it if it's freezing. I use Safari with no extensions.

**Comment by photopea** [comment] 2024-06-26 21:48
Could you please record a short video of what is happening, as a proof?

**Comment by Kyderra** [comment] 2026-03-31 21:43
> Could you please record a short video of what is happening, as a proof?

video: https://streamable.com/gnfd4j

I'm bumping this post to mention that I have been having this issue as well.  Something is causing micro stutters and are making the Desktop app unusable for me. If it's the adds I don't know, but it seems the most logical.
The Video shows Issue on Chrome, Via Chrome desktop App (no addblocker extension), and then in Firefox where there don't seem to be problems. (adds are non video in my example). Enabling Addblocker in firefox also seems to increases overall fps.

Cleared Cash on chrome but noticed that on accepting cookies it loads in / allowed 161 website data. 
<img width="586" height="741" alt="Image" src="https://github.com/user-attachments/assets/1774c583-acb3-459e-9dbe-483d88d8ac76" />, not sure if that's intentional.

**Comment by photopea** [comment] 2026-03-31 23:08
Yes, it is definitely caused by ads in your case. But if I remove ads, I will lose almost the whole income :( do you have any idea how can I monetize it without ads?

**Comment by Kyderra** [comment] 2026-04-03 13:12
> Yes, it is definitely caused by ads in your case. But if I remove ads, I will lose almost the whole income :( do you have any idea how can I monetize it without ads?

I don't think it's bad to have adds, but in this case they seem to swap out pretty aggressively and some load in 1 minute long 720 video's.  Perhaps it's worth looking into some limits of what an add is allowed to do?

As for alternatives, 
While I don't think it's fully comparable, Perhaps it's worth looking at how Blender does it. (https://fund.blender.org/)
perhaps there's an option to get larger support funding, where you have gold sponsers and shows that a brand is making the software possible more directly.  
Of course those don't just appear and Blender has a long history, but making companies aware of the option, who knows what might come of it.

**Comment by photopea** [comment] 2026-04-03 16:03
Would you be willing to contribute to Photopea regularly, just like people contribute to Blender? I am not sure if there are enoug people to donate to Photopea regularly.

**Comment by Kyderra** [comment] 2026-04-04 22:23
> Would you be willing to contribute to Photopea regularly, just like people contribute to Blender? I am not sure if there are enoug people to donate to Photopea regularly.

I feel like I am a bit of an outlier, I understand that 99% of people want features or they won't subscribe but I support blender with $5 a month without expecting features.

if you want my honest feedback based on something that happened.
I have been subbed before a while back and wanted to again recently but decided not to due to how the price was presented.
Originally seeing a $5,- made me want to subscribe, or at least donate, but then was instantly met with a "Actually, it's $8,-, unless you buy it for a year.", that's almost twice as much.

Whits followed with seeing the year price being $50,-.  and with that price point my brain went: "I can subscribe to Photoshop for that" 
I am aware that the price is fair, but I want to give my personal  blunt example of what did make me click it away.

Considering it's just for the adds I wanna get rid of, I think a $5,- a month is a nice sweet spot. and perhaps other features can be part of a $8,- bundle. But again, I can be a outlier. 
I do think there's appeal to be shown as a Top donator on the front page.

**Comment by photopea** [comment] 2026-04-04 22:56
You can pay $15 for 90 days of Photopea Premium.  Adobe Photoshop costs $50 for a month, not for a year.
