### ISSUE TITLE
Text isn't working with Text tool

### ISSUE THREAD

**Issue by Yochevedb1** [photopea/photopea#2109] opened 2020-05-04 21:26 UTC
I can't get the text tool to work. Black text on white background, top layer. Nothing showing up no matter how small or large I make the text.

**Comment by photopea** [comment] 2020-05-04 21:33
Hi, can you disable all your browser extensions?

**Comment by photopea** [comment] 2020-05-05 08:54
I will close it, I think the problem was caused by extensions.

**Closed by photopea** 2020-05-05 08:54 UTC
