### ISSUE TITLE
al usar funcion abrir y colocar se bugea

### ISSUE THREAD

**Issue by danielssaa** [photopea/photopea#6337] opened 2024-01-18 19:30 UTC
Your Operating System:Windows 10 pro Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz   2.60 GHz
Your Web Browser:Microsoft Edge, Chrome 
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....

**Comment by danielssaa** [comment] 2024-01-18 19:31
[Photopea _ Online Photo Editor 2024-01-18 13-25-43.zip](https://github.com/photopea/photopea/files/13980913/Photopea._.Online.Photo.Editor.2024-01-18.13-25-43.zip)
adjunto prueba , luego creo un nuevo proyecto y no aparece el area de trabajo ni las imagenes

**Comment by photopea** [comment] 2024-01-18 22:25
When you create a document, you should see a white canvas (white rectangle). If yo do not see it, there is no point in doing anything after that.

Your DPI is quite high. The document has 83 million pixels. How much RAM memory do you have? Did you try it in the Incognito mode?

**Comment by photopea** [comment] 2024-01-18 23:40
Maybe the problem is caused by your browser extensions. Try to disable all of them and see if it helps. Maybe restart your computer, if there are other programs using your RAM.

**Comment by danielssaa** [comment] 2024-01-19 02:09
ya desactive las extensiones , reinicie el equipo, probe en modo incognito , y la ram al estar dentro no sobrepasa el 60%
[Photopea - Fotopea _ Editor de fotos en línea 2024-01-18 19-58-30.zip](https://github.com/photopea/photopea/files/13983435/Photopea.-.Fotopea._.Editor.de.fotos.en.linea.2024-01-18.19-58-30.zip)
![Captura de pantalla (46)](https://github.com/photopea/photopea/assets/157059010/c94b67fc-28ee-4e5f-a699-4f0019f8a66d)

**Comment by photopea** [comment] 2024-01-19 09:11
Could you open www.Photopea.com in the incognito mode, open any JPG file in Photopea, and show me a screenshot?

**Comment by photopea** [comment] 2024-01-30 13:41
I have to close it because of lack of details :(

**Closed by photopea** 2024-01-30 13:41 UTC
