### ISSUE TITLE
Blur Tool Malfunction

### ISSUE THREAD

**Issue by Colleenmp** [photopea/photopea#1878] opened 2020-01-02 05:06 UTC
The past week or so the blur tool has turned into and eraser.
Not sure if it's just my device (Chromebook) or if others are experiencing that also.

![Screenshot 2020-01-01 at 9 04 11 PM](https://user-images.githubusercontent.com/13514883/71652439-7a071a80-2cda-11ea-81b6-079104bd98a9.png)

**Comment by photopea** [comment] 2020-01-02 16:21
Hi, I can not reproduce it :( When I use a Blur tool, it always blurs the image.

So in your case, every time, for every image, the Blur tool always erases pixels? Or is it only for some images?

**Comment by photopea** [comment] 2020-01-06 10:55
I have to close it because of lack of details.

**Closed by photopea** 2020-01-06 10:55 UTC
