### ISSUE TITLE
Right-click to rename layers to avoid glitch

### ISSUE THREAD

**Issue by TheCelticChemist** [photopea/photopea#3727] opened 2021-09-13 05:56 UTC
I am unsure why, but there are times when it is near impossible to rename a layer. I'll double click repeatedly but it simply won't allow me to edit the name. And then seemingly magically, it will allow me to. I would appreciate being able to right-click a layer and select rename so it allows me to directly edit the name that way. Thank you.

**Comment by photopea** [comment] 2021-09-13 10:12
How can I reproduce this inability to rename the layer? Whenever I double-click it, I can rename it.

Do you know, that you should double-click the layer name (the text itself), and not the thumbnail, etc?

**Comment by TheCelticChemist** [comment] 2021-09-13 13:26
Unfortunately, I don't know what's creating the issue to know how to recreate what's triggering it. I do know to click directly on the text though. But when it doesn't work, which it very often doesn't, I just click all over the text in random bursts (that is, double, triple, and quadruple clicks) until finally it randomly works or I get so fed up with it that I give up. This has been an ongoing issue, basically every time I use Photopea. I can tell you I'm using the downloaded chrome web app, if that helps at all. I don't know how to recreate the issue, but I believe that adding the option to rename when we right-click a layer would almost certainly fix it as I am able to right-click and make selections consistently on any layer. This would be just like a file on a desktop where you have the option to click on the name to directly edit the file name or you can right-click and select "Rename." It's honestly very disheartening to have gotten caught up so frequently on one of the most basic functionalities of the Photopea service, so implementing this feature to prevent this issue going forward would be greatly appreciated.

**Comment by photopea** [comment] 2021-09-13 13:56
Have you tried these steps? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

It feels wrong to add a feature which almost nobody needs, just because you are using some broken browser extension or something.

**Comment by photopea** [comment] 2021-09-16 21:02
Are there any news? Or could you maybe record a video of the glitch, so that I can reproduce it somehow?

**Comment by photopea** [comment] 2021-09-19 10:17
I have to close it because of lack of details :(

**Closed by photopea** 2021-09-19 10:17 UTC
