### ISSUE TITLE
Vector Curves Rendering issues

### ISSUE THREAD

**Issue by Axis4s** [photopea/photopea#6590] opened 2024-03-27 00:27 UTC
Your Operating System: Windows 11
Your Web Browser: Firefox
The problem happens in the Incognito Mode, too: idk, i don't think that makes a difference

**This must be done to see the problem**
Just create a curved vector line
![image](https://github.com/photopea/photopea/assets/97393974/34e1420e-f105-44ea-ba52-694c5084768b)

1. Go to www.photopea.com
2. Create a curved vector or convert a text to vector

**Comment by photopea** [comment] 2024-03-27 10:30
I am confused. What exactly is the problem?

the preview in Photopea is always done using pixels. If you zoom in far enough, you will always see large pixels, even when looking at vector layers.

**Comment by Axis4s** [comment] 2024-03-27 10:53
> I am confused. What exactly is the problem?
> 
> the preview in Photopea is always done using pixels. If you zoom in far enough, you will always see large pixels, even when looking at vector layers.

Yes i know, that's how vectors are displayed on screens, they are rasterized into pixels
but there is something wrong about how it is rendering on Firefox, some of the lines that are meant to be curved basically have their curves removed?
![image](https://github.com/photopea/photopea/assets/97393974/1fe0754e-d8dd-4702-a021-6f235b7f532a)
As you can see they are curved but Photopea on firefox isn't rendering them properly.

**MICROSOFT EDGE**
![image](https://github.com/photopea/photopea/assets/97393974/50a45435-fb7a-42da-962c-d81a885e4450)

**FIREFOX DEVELOPER EDITION**
![image](https://github.com/photopea/photopea/assets/97393974/615dada6-105a-46fc-83d9-916cd62a1d25)

**Comment by photopea** [comment] 2024-03-27 12:34
Maybe it is  a bug in Firefox? Is it a stable release of Firefox or some Beta version? Do you use any browser extensions?

**Comment by Axis4s** [comment] 2024-03-27 12:42
> Maybe it is a bug in Firefox? Is it a stable release of Firefox or some Beta version? Do you use any browser extensions?

i have to do tests on a Stable Version of Firefox, i will do them soon because rn im with my hands a little full, i use these addons.
![image](https://github.com/photopea/photopea/assets/97393974/70db8407-6154-4a34-9f57-40b9dc6ead00)

**Comment by Axis4s** [comment] 2024-03-27 15:06
> Maybe it is a bug in Firefox? Is it a stable release of Firefox or some Beta version? Do you use any browser extensions?

![image](https://github.com/photopea/photopea/assets/97393974/af3a3abe-b250-4c4f-b360-7fd63065e34c)
Loaded the PSD on the latest stable Firefox with No addons, I Don't think add-ons make a difference since the issue still persist

**Comment by photopea** [comment] 2024-03-27 16:57
Could you put your PSD into a ZIP and share it here? I will try to open it in Firefox myself.

**Comment by Axis4s** [comment] 2024-03-27 17:05
> Could you put your PSD into a ZIP and share it here? I will try to open it in Firefox myself.
[CD1.zip](https://github.com/photopea/photopea/files/14776715/CD1.zip)

**Comment by Axis4s** [comment] 2024-03-27 18:57
> It looks fine when I open it in Photopea in firefox :( I use Firefox 124.0.1, and you?

![image](https://github.com/photopea/photopea/assets/97393974/95805b4f-a25d-4285-a797-bb75f76b00c7)
that's the version i installed, weird
yeah this hella weird because that's not supposed to happen, on edge and prolly other chromium browsers it look just fine

**Comment by photopea** [comment] 2024-03-27 19:16
Could you try just the single layer?
[CD1.zip](https://github.com/photopea/photopea/files/14780168/CD1.zip)

**Comment by Axis4s** [comment] 2024-03-28 00:56
> Could you try just the single layer? [CD1.zip](https://github.com/photopea/photopea/files/14780168/CD1.zip)

![image](https://github.com/photopea/photopea/assets/97393974/53fd1d3a-51c2-44a7-beba-df90b4db2f2e)
sorry for the late response but here.

**Comment by photopea** [comment] 2024-03-28 08:06
This is what I see in my Firefox :(  Could you reset your Firefox to factory settings?
![image (2)](https://github.com/photopea/photopea/assets/15955558/574c89d3-3e6c-41b0-9d6c-b2b45db93d91)

**Comment by photopea** [comment] 2024-05-29 20:55
I have to close it because of lack of details :( Seems like a bug in Firefox, probably the GPU-related stuff, as vector graphics is usually rendered on a GPU.

Also, it could be caused by the browser extensions, as the author never confirmed turning them off.

**Closed by photopea** 2024-05-29 20:55 UTC
