### ISSUE TITLE
big problem with Photopea

### ISSUE THREAD

**Issue by adi3355** [photopea/photopea#2856] opened 2021-02-11 14:27 UTC
hey! 
first, sorry if u cant to understand me...
i have a problem with  Photopea - and i understood that i need to report here, right?
if is true, please tell me!
adi

**Comment by photopea** [comment] 2021-02-11 15:01
Hi, sure, what is the problem?

**Comment by adi3355** [comment] 2021-02-11 19:20
Okay, so I'm really glad I found your software- it really helped me because
paying for Photoshop as a computer software is not really in my price range
.. but recently I found out that you have the option to export the projects
as PSD files- but when I do it then all my Google Starts to jump, and opens
a new tab and then it closes (quickly) - and it's something like 10 minutes
does it .. I tried with a few different files and even downloaded your
plugin (I thought from there it would work) but unfortunately the glitch
repeats itself over and over again .. to my delight I saw the problem
report button and that's how I got to you.
Is there anything to do with it?
Thank you very much for answering at all, and I would love to have support
with the problem.
adi

‫בתאריך יום ה׳, 11 בפבר׳ 2021 ב-17:02 מאת ‪Photopea‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by photopea** [comment] 2021-02-12 16:24
Hi, What is "all your Google"? Are you talking about a Chrome web browser?

Try to update your web browser. If it does not help, try to disable all browser extensions at chrome://extensions . Let me know if it helped.

**Comment by PyxelatedStudios** [comment] 2021-02-12 17:10
Hi @adi3355,

I might know what happens.

Earlier I used photoshop but I couldn't pay longer so I now use Photopea and I don't have photoshop or gimp installed on my computer. When I click save psd under the file menu, I see the file downloaded with aplication icon(note: I am using Microsoft Edge). When I click it browser opens and for less than second new tab opens and closes, and same file is again downloaded(psd file).

**Comment by photopea** [comment] 2021-02-12 18:48
@PyxelatedStudios I need to reproduce such behaviour, to be able to fix it. Can you tell me, which device and which browser should I try, and what version, to see such behaviour? In my case, saving works fine.

**Comment by adi3355** [comment] 2021-02-13 17:47
@PyxelatedStudios  Basically what you described is more or less what happened- I use Chrome browser (Google) and I really hope they solve the problem.
@photopea  What can be done? I tried from two computers and I have the same problem ..
If I try to do this in Microsoft Edge is there a chance it will work?

**Comment by dentistformyeye** [comment] 2021-02-13 18:38
The browser can't display PSD files, so attempting to open a PSD in a browser will only download it again. You could probably change the setting that decides the default app for opening PSDs.
When things download in Chromium browsers (and I think also in Firefox), the tabs automatically close themselves after the download starts. I've found this quite annoying because it's sometimes impossible to see/copy the download URL, so I'd like for browsers to add a toggle to keep the tabs open, but the automatic closing behavior is considered "normal". There's nothing Photopea can do about it.

**Comment by PyxelatedStudios** [comment] 2021-02-13 19:08
@dentistformyeye Yeah that's right

**Comment by photopea** [comment] 2021-02-13 22:31
I think this is not related to Photopea. You should discuss it with the creators of your operating system, if you want something to happen when you double-click a PSD file in your computer.

**Closed by photopea** 2021-02-13 22:31 UTC
