### ISSUE TITLE
I cant resize an image

### ISSUE THREAD

**Issue by 2k1pped** [photopea/photopea#6601] opened 2024-03-30 04:20 UTC
Your Operating System:
Your Web Browser:
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. import an image
3. i cant resize it
idk if its just me but its not working and this is the only site i have. im to broke for anything else

**Comment by photopea** [comment] 2024-03-30 08:10
To resize a layer, press Edit - Free Transform. Is this what you are doing?

**Comment by Scoop2389** [comment] 2024-03-31 14:11
Hello, I have the same issue as this user. I am going to Edit - Free Transform. It seems to a similar issue as described here: #5567, as the workaround they discovered also seems to work to fix this issue. (CTRL + Click on the layer mini preview in the layers tab and then CTRL + ALT + T _Originally posted by @oMerkurio in https://github.com/photopea/photopea/issues/5567#issuecomment-1528454998_)

**Comment by Scoop2389** [comment] 2024-04-01 14:37
Now I am very confused, as when I went to get the video for the issue, I could not reproduce it either 🤔

**Comment by photopea** [comment] 2024-05-29 20:47
I will close it then.

**Closed by photopea** 2024-05-29 20:47 UTC
