### ISSUE TITLE
Action panel: some actions are not working

### ISSUE THREAD

**Issue by Aly-Moataz-Shorosh** [photopea/photopea#4850] opened 2022-07-23 01:43 UTC
As: creating a text, open an image, save,

there also no automate batch in photopea,

thanks a lot for you effort for this wonderful tool <3

**Comment by quantuminformation** [comment] 2022-07-23 10:54
i am unable to export psd or save jpg in FF atm, lost some work too

**Comment by quantuminformation** [comment] 2022-07-23 10:54
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/216566/180602118-730c7c62-b369-4fe2-a0fd-f180c3df3f97.png">

**Comment by photopea** [comment] 2022-07-23 21:54
Could you tell me how can I reproduce it?

I opened Photopea.com in Firefox, crated an empty document, and saved it as a PSD, it worked.

**Comment by photopea** [comment] 2022-07-31 23:18
I have to close it because the person stopped responding.

**Closed by photopea** 2022-07-31 23:18 UTC

**Comment by quantuminformation** [comment] 2022-08-02 11:40
i used another file and issue was gone, sorry for delay
