### ISSUE TITLE
psd file bugged?

### ISSUE THREAD

**Issue by ThatOneCurryGuy** [photopea/photopea#7111] opened 2024-08-28 03:00 UTC
i use photopea on chrome, and for some reason the psd file i downloaded to save is corrupted, saying "wrong signature". i made sure that the save popup disappeared before closing, and there shouldn't have been any bugs.

is there any way to recover some of the data or fix this issue in general?

**Comment by photopea** [comment] 2024-08-28 08:10
Can you produce an unopenable PSD file in Photopea again, as a proof? To make sure it was not caused by your hard drive error, etc.

**Comment by photopea** [comment] 2024-09-07 23:31
I have to close it because of lack of details :(

**Closed by photopea** 2024-09-07 23:31 UTC
