### ISSUE TITLE
when i zoom in and draw it will not draw

### ISSUE THREAD

**Issue by HalfdanOMG** [photopea/photopea#1297] opened 2019-03-19 12:31 UTC

**Comment by photopea** [comment] 2019-03-19 12:40
Hi, I can not reproduce it :( could you please clarify? Maybe show us your PSD and tell us, at which spot and which layer are you drawing.

**Comment by photopea** [comment] 2019-03-20 15:30
I have to close it because of lack of details :(

**Closed by photopea** 2019-03-20 15:30 UTC
