### ISSUE TITLE
bug with project

### ISSUE THREAD

**Issue by unknownyyyy137** [photopea/photopea#5776] opened 2023-06-24 19:49 UTC
so i left a project alone for about 10 minutes, and once i came back to the bar on which i had my project, the background wasn't there. **please fix that bug**

**Comment by camoody1** [comment] 2023-06-25 00:07
Can you reproduce this occurrence? If we can't consistently reproduce the problem, it becomes extremely difficult to fix.

**Comment by photopea** [comment] 2023-06-25 06:43
What should we do to see such a problem? It could be also caused by your browser being too old, see https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment] 2023-08-29 22:51
I have to close it because the person did not respond.

**Closed by photopea** 2023-08-29 22:51 UTC
