### ISSUE TITLE
Photopea stuck on "saving" banner and on-computer files are "empty"

### ISSUE THREAD

**Issue by 5hoursandcounting** [photopea/photopea#5941] opened 2023-08-11 23:43 UTC
Photopea has been stuck with a "saving" banner for over an hour, now. Every now and then, the saving banner alternates with a message that reads ""Not enough RAM (need 20--)" (it disappeared before I could note the number.)

I subscribed to Photopea pro midway through the process in the hopes of improving functionality and getting the full file to save. I was able to access an earlier version through Peadrive in a new window, but cannot save that to my computer either. Anything I save to my computer (JPG or PSD) appears as a 0 KB file.

I am afraid to close the window and loose what has become about 5 hours worth of work (and counting).
I need this file saved as a JPG so that I can have it enlarged and printed as part of an art project with a closely approaching install deadline. I have been troubleshooting for hours and I am burning out. I really need help.

What can I do?
Can I somehow create more RAM? If so, How? (I'll need this in baby steps, I can't make head or tails from my research on this)
Is there any way to get the "saving" process unstuck and start over?

More details:

I am working on Chrome, on a Macbook Pro. Chome does need an update, but I am afraid to close my tab and loose my work.

I am working on a large file (69015 x 3300 pixels) The project began as a twenty-layer stitch, but I have been merging the layers in an attempt to simplify the file and reduce lagging. I got it down to three layers before it stopped responding. 

I appreciate anyone's help.

**Comment by 5hoursandcounting** [comment] 2023-08-12 00:23
Edit: I finally caught the message again, it reads: "Not enough RAM (need 2048)"

**Comment by photopea** [comment] 2023-08-12 05:54
So, how much RAM memory do you have? It must be written on a label of your computer, when you bought it.

"Anything I save to my computer (JPG or PSD) appears as a 0 KB file." - we definitely must solve this first. Could you disable all your browser extensions and try to save files again?

You never mentioned, how many of your extensions are allowed to modify Photopea. When Photopea is modified by one or more of your extensions, it is really hard to know the cause of your problems.

**Comment by camoody1** [comment] 2023-08-12 08:15
< I am working on a large file (69015 x 3300 pixels)

I would guess this is his problem. Not browser extensions.

**Comment by bluep55** [comment] 2023-08-12 15:26
This shows you how to check how much RAM your Mac has.
It may help you.
 https://www.macinstruct.com/tutorials/see-how-much-ram-is-installed-in-your-mac/

**Comment by 5hoursandcounting** [comment] 2023-08-13 14:17
Thanks Blue55" It looks like my RAM is 8 GB (2133 MHz LPDDR3). 
I am not sure what unit the "2048" in photopea's banner was, as it didn't say, and wether 8GB would accommodate it. I presume not.

In any case, it seems like the consensus here is that my file is just too big. 

It sounds like the only way our of this is to shrink the file.
I want something that can still be printed with decent resolution on an approximately 25 foot long banner, but which Photopea will be able to export. 

Does any one have any advice on how to size that? 
What are photopea's upper limits of file export? 
At what size does resolution break down? (I've been trained to always print at 300 dpi, but I am not quite sure how that might translate to canvas/file size in this case)

**Comment by camoody1** [comment] 2023-08-13 14:31
Since you're making a 25 foot long banner, I'm assuming you're meaning for it to be viewed at a distance. Perhaps up high? For something large being viewed at a distance, I would imagine 100PPI would look just fine. 300PPI is great for magazine print and photos - even medium sized posters - that have a lot of detail and will be viewed up close. But 300PPI at 25 feet is just enormous and probably unnecessary. Maybe try 150PPI to see if that works before dropping all the way down to 100PPI.

**Comment by photopea** [comment] 2023-08-13 14:55
If you will look at it from 3 meters of more, I think the DPI of 30 is ok.

**Comment by 5hoursandcounting** [comment] 2023-08-13 15:04
Unfortunatley, it is part of an art piece that, while long, will be viewed at eye-level from quite close. It mostly consists of black and white text, so the resolution will be the difference between legible and illegible text....

**Comment by photopea** [comment] 2023-08-13 15:17
If you make only vector graphics, and you export a PDF, the DPI is not important, you can use any value.

**Comment by photopea** [comment] 2023-08-29 21:13
I have to close it as the person did not respond.

**Closed by photopea** 2023-08-29 21:13 UTC

**Comment by LinuXP15** [comment] 2025-10-08 06:07
when photopea starts to malfunctions I try sharing the project so I can reopen it in a new window and save there, which usually works, although sometimes the option to share is disabled, maybe for an already shared project, but saving doesnt update the content in the link, i heard someone was exporting layers as a last resort too, but today waking the pc after it went to sleep has somehow brought my project back to life, both as working elements and saveable

**Comment by photopea** [comment] 2025-10-08 09:19
You should save your work to your device using File - Save as PSD. If you use File - Share, it will take 50x more time, because it uploads your file to our cloud.

**Comment by LinuXP15** [comment] 2025-10-08 09:21
i know, i do it when Photopea goes crazy and fails to save the file, creating a blank 0kb file, this is a workaround to save precious work.

**Comment by LinuXP15** [comment] 2025-10-08 09:24
i thought about trying Gimp again but im already used to your great program, which is available through phones too, online, while gimp isnt that advanced, and I found a workaround in reddit to make Photopea full screen, so life is good

**Comment by photopea** [comment] 2025-10-08 10:03
If you can make Photopea produce a 0kb file, please, record a short video of how you do it. I am ready to pay you for finding a bug in Photopea.

**Comment by LinuXP15** [comment] 2025-10-08 12:39
https://drive.google.com/drive/folders/1Z1-dKpxy48qLR24fuq3DnM_9zJpUZ76R?usp=sharing

i created two videos, the first was pretty long, over 3 min, so a shorter one of 1 min was created,
I already enjoy photopea, which is the prize, and I own you money for adblocking

if the videos arent clear enough I will try to create more or explain

edit: another maybe bug, i got a screenshot

disabling all the effects to the arrow make it appear as a white rectangle

<img width="1600" height="900" alt="Image" src="https://github.com/user-attachments/assets/6fc2a3a2-7569-4b06-8b6c-624be34f3b16" />

**Comment by photopea** [comment] 2025-10-08 15:54
I can not see your video :( Could you share a link which you can open yourself in the Incognito mode? That means that anybody can open your link.

**Comment by LinuXP15** [comment] 2025-10-09 03:37
Incognito is a nice idea, i hope I'll remember that

**Comment by LinuXP15** [comment] 2025-10-09 03:43
Is it working now? It worked for me in incognito

**Comment by photopea** [comment] 2025-10-09 10:28
This is how Photopea looks like (the way we made it). Your screenshot is not Photopea, as Photopea must have ads on the right side.

You are allowing some software to re-build Photopea (in order to remove ads). I think your software is also breaking many features of Photopea.

<img width="2097" height="1230" alt="Image" src="https://github.com/user-attachments/assets/f7ca0801-71b1-456c-830d-c41d334cb188" />

**Comment by LinuXP15** [comment] 2025-10-09 10:52
it is the same as if someone uses the full paid version, all i did was blocking the ads and letting photopea use the whole screen as there is no point for the empty recatngle on the side anymore

you dont have to fix it anyway, im just letting you know, although who wouldnt like Photopea fixed, but i can try reproduce it with ubo turned off, if it will convince you

**Comment by LinuXP15** [comment] 2025-10-09 10:52
I can also send you the psd file

**Comment by photopea** [comment] 2025-10-09 11:20
As I said, I do not know what your extensions do to Photopea. I can not guarantee a correct functionality of Photopea when you allow your extensions to rebuild it.

Do you have any problems when using Photopea with no extensions?

**Comment by LinuXP15** [comment] 2025-10-09 11:30
It doesn't rebuilt it, its like saying that adblocking YouTube's ads rebuilt it, i will update with a video with ubo off

**Comment by LinuXP15** [comment] 2025-10-09 13:44
i tried using it with no extension, and while I couldn't glitch photopea, my pc wasn't much useable, so the 20 minutes recording was for nothing, i hope either that someone with a paid version will prove this bug or photopea would work as intended, i didn't expect ads to affect the performance so much

**Comment by LinuXP15** [comment] 2025-10-09 13:53
the new popup that appear each time the cursor moves feels pretty mean, unless it is a bug too

<img width="1600" height="900" alt="Image" src="https://github.com/user-attachments/assets/594de5c2-6546-4218-81fd-137373008f52" />

**Comment by photopea** [comment] 2025-10-09 15:56
The message about Brave Shields breaking Photopea should appear only once. That is what happens when I use Photopea in Brave with brave Shields.

Do you see it more tha nonce? As I said, I probably need to install all browser extensions that you have, to see a problem that you have, but you did not tell me a full list of all extensions that you have.

**Comment by LinuXP15** [comment] 2025-10-09 16:17
i thought you have tighten the ads procedure, because using ubo and coding the site causes it to display the messege each time the mouse is moving ontop of the canvas, which was distracting, trying to disable it caused the whole site to freeze for a long time, and i couldnt make it work without the alert stopping

I feel too comfortable with pp so I try avoiding Gimp, but pp offline version seems cool, although im not sure how to run it on mobile

**Comment by LinuXP15** [comment] 2025-10-09 16:31
i uploaded another video, its long because i waited to the site to be responsive again, so you may skip the middle. I also use only ubo, no other extensions.

a link to the video
https://drive.google.com/file/d/1horaXJ9v-LylJ0GpQpVcccYCbnyn6Chj/view?usp=drive_link

**Comment by photopea** [comment] 2025-10-09 16:55
Your video has over 5 minutes and there is not a single word spoken in your video. Also, I do not understand Hebrew :( I have no idea what you are trying to do.

We can not fix any bugs caused by browser extensions. Please, report only bugs which happen when Photopa runs the way it was created. Why dont you report it to uBlock Origin?

**Comment by LinuXP15** [comment] 2025-10-09 17:36
i dont speak in this video, i only wanted to show that at the end the popup alert is showed more than once, endlessly, each time the cursor moves while on the canvas area.

the start and middle parts of the video arent important, you can jump to its last seconds seeing the alert poping back up again each time.

**Comment by photopea** [comment] 2025-10-09 18:05
are you using any browser extensions in your video?

**Comment by LinuXP15** [comment] 2025-10-09 19:30
Only ubo, and a custom command in the console
