### ISSUE TITLE
PSD templates not loading in Chrome

### ISSUE THREAD

**Issue by Cardi619** [photopea/photopea#2942] opened 2021-02-25 09:16 UTC
After selecting a PSD template the loading sign stays visible indefinitely and no template is loaded.

Version 88.0.4324.182 (Official Build) (64-bit) on Windows 10 Entreprise

**Comment by photopea** [comment] 2021-02-25 12:56
Do you have any browser extension or other software, which could be censoring network connections? Could you disable it?

**Comment by photopea** [comment] 2021-02-25 19:32
I will close it, I think the problem is in a browser extension, or in your internet provider (who is blocking the domain of our storage).

**Closed by photopea** 2021-02-25 19:32 UTC
