### ISSUE TITLE
Gradient map adj shown as gradient fill in properties panel after adding a following gradient fill layer

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#900] opened 2018-09-18 00:44 UTC
Gradient map adj shown as gradient fill in properties panel and not working, with and without the presence of a following gradient fill layer (both cases encountered)

related:
Gradient map adj layer turned into gradient fill layer after 2times+ gradient adjustments with presence of a following gradient fill layer

**Comment by photopea** [comment] 2018-09-18 06:17
Hi, I tried to do some experiments and the Gradient Map Adj. layer never "turned into" a Gradient Fill layer.

I really think, that you just got confused. When you have a Grad. Fill layer, and put Grad. Map Adj. layer over it, you just see the gradient beneath recolored.

If you are sure about a bug, please, tell us more about how to reproduce it, or send some screenshots.

**Comment by photopea** [comment] 2018-09-19 07:38
I tried it several times and it never happened :( Is there anything special what you do?

**Comment by photopea** [comment] 2018-09-30 22:31
I have to close it because of lack of details :(

**Closed by photopea** 2018-09-30 22:31 UTC

**Comment by hgs54371** [comment] 2018-10-02 19:03
Not anything special, just happened as described
