### ISSUE TITLE
Transform Menu Is Broken

### ISSUE THREAD

**Issue by BoomLingReady** [photopea/photopea#7330] opened 2024-11-14 20:51 UTC
Your Operating System: Windows 10
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: nah

**This must be done to see the problem**
1. Go to www.photopea.com
2. Place A Object
3. Click The Object And Go To "Edit" Tab In The Top Left
4. Hover Your Mouse Cursor On The "Transform" Button
5. Click Any Of The Buttons You See

**Comment by photopea** [comment] 2024-11-14 22:00
Your problem does not happen in the Incognito mode? Then, it is probably caused by your browser extensions.

**Comment by BoomLingReady** [comment] 2024-11-15 14:11
> Your problem does not happen in the Incognito mode? Then, it is probably caused by your browser extensions.

![unb](https://github.com/user-attachments/assets/71c0a7bb-e0fe-4fb5-9ba5-f837e16de525)

**Comment by photopea** [comment] 2024-11-15 14:34
It could be a bug in the Brave browser. Could you try to turn off the Brave shields?

**Comment by photopea** [comment] 2024-11-16 14:18
I have to close it, because nobody is replying :(

**Closed by photopea** 2024-11-16 14:18 UTC
