### ISSUE TITLE
Supporting PNG with palettes

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#105] opened 2016-09-27 01:31 UTC
I use a lot these feature, but i encounter this image: https://cdnx.jumpseller.com/lasmellizas/image/711659/resize/500/500?1463871435

For some reason it uploads as a black square with 3 little version of the picture in negative effect  :/

This is the resulting image:http://tinypic.com/r/34zna6v/9

Btw, it will be better for the UX to have all the URL already selected ready for paste the new one. Right now you have to click the text box, select all the last URL, delete it, and then paste the new one.

**Comment by photopea** [comment] 2016-09-27 13:14
Hi,  the problem is not with the opening a file from URL. You can save the image to your computer and open it with File - Open, you will have the same result.

The problem is, that your PNG is encoded using a color palette, which is not supported by our current PNG decoder https://github.com/devongovett/png.js/ . I could not find any better PNG decoder with palette support, so I am thinking about implementing my own in the future (which will be open source).

**Comment by avagp** [comment] 2016-09-27 13:17
Great.

Thank you, as always

**Comment by photopea** [comment] 2017-03-29 00:11
This issue is solved now. You should be able to open correctly any existing PNG file.

I have written my own PNG decoder, which I released as open-source here: https://github.com/photopea/UPNG.js .

**Closed by photopea** 2017-03-29 00:11 UTC

**Comment by avagp** [comment] 2017-03-29 00:12
You are so awesome and smart.






2017-03-28 21:11 GMT-03:00 Photopea <notifications@github.com>:
