### ISSUE TITLE
My Photopea Is Not Saving Images AND Being On Zero Bytes

### ISSUE THREAD

**Issue by CalebPlayzRoblox** [photopea/photopea#5153] opened 2022-12-03 23:39 UTC
I Try Saving A Image, No, How Many Bytes? ZERO

**Comment by DuckyMacfly** [comment] 2022-12-03 23:59
Yeah, same problem here.

**Comment by photopea** [comment] 2022-12-04 18:25
Does it still happen now?

**Comment by CalebPlayzRoblox** [comment] 2022-12-04 23:03
@photopea yes

**Comment by photopea** [comment] 2022-12-05 00:38
Try this https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment] 2022-12-05 13:39
I have to close it because of lack of details. The person did not provide any instructions on how to reproduce the issue.

**Closed by photopea** 2022-12-05 13:39 UTC
