### ISSUE TITLE
Text Tool Stuck On Loading

### ISSUE THREAD

**Issue by JunoJog** [photopea/photopea#4050] opened 2021-11-29 21:41 UTC
Whenever I try to add text to a file in photopea, it's stuck on a "loading" icon at the top that never goes away no matter how long I wait. I don't have any extensions, add-blockers, or anything to interfere with it. I've tried doing it on incognito and it's the same. I'm using Chrome btw.

**Comment by photopea** [comment] 2021-11-29 23:50
It seems like it is loading a font file. Do you have any antivirus or a firewall? Can you try it on a different computer, e.g. on your phone?

**Comment by avagp** [comment] 2021-11-30 04:25
You are uploading a .zip file or directly the font file?

**Comment by photopea** [comment] 2021-12-02 12:07
I have to close it because of lack of details :(

**Closed by photopea** 2021-12-02 12:07 UTC

**Comment by JunoJog** [comment] 2021-12-06 00:06
It works on my phone

**Comment by JunoJog** [comment] 2021-12-06 00:06
But i'm not going to do graphic design on my phone lol

**Comment by photopea** [comment] 2021-12-06 13:31
Do you have any browser extensions on your desktop? Maybe you are using the "Block fonts in Photopea" extension on your desktop, but you did not install that extension into your phone yet. We recommend trying Photopea with no browser extensions first, to check if your problem is caused by your extensions.
