### ISSUE TITLE
Something's up with the buttons.

### ISSUE THREAD

**Issue by MesaBlack** [photopea/photopea#6277] opened 2024-01-02 03:18 UTC
Your Operating System: ChromeOS
Your Web Browser: Web App
The problem happens in the Incognito Mode, too:

[Screen recording 2024-01-01 9.16.07 PM.webm](https://github.com/photopea/photopea/assets/132141735/4f7fa6a7-d889-4daa-8666-e5eeacb6eea0)

1. Go to www.photopea.com or webapp
2. open new project
3. do as the video shows
4. see error if it appears

**Comment by photopea** [comment] 2024-01-02 09:19
Did you try to use Photopea without any browser extensions?

**Comment by MesaBlack** [comment] 2024-01-02 13:09
What do you mean by browser extensions here? Like in general, or for photopea? And I'm on the webapp version

**Comment by photopea** [comment] 2024-01-02 13:32
browser extensions can modify every website which you open. Extensions can modify installed webapps, too.

**Comment by camoody1** [comment] 2024-01-02 21:53
@MesaBlack @photopea  That area of the buttons is unclickable because there's a text message still on the screen - that "Loading" message. When messages like that get stuck in Photopea, any button area on that same horizontal line are unclickable. I would love for that issue to be resolved.

**Comment by photopea** [comment] 2024-01-03 19:15
I have to close it because of lack of details. But I am quite sure that it is caused by browser extensions. The person did not try Photopea in the Incognito mode.

**Closed by photopea** 2024-01-03 19:15 UTC

**Comment by MesaBlack** [comment] 2024-01-03 23:37
No browser extensions were used that affected photopea. It's the area of the stuck message

**Comment by photopea** [comment] 2024-01-04 00:08
Yes, you should not do anything while there is a Loading message. How did you make Photopea show the Loading message for so long?

**Comment by MesaBlack** [comment] 2024-01-04 00:25
It was stuck. didn't you see camoody's messages?

**Comment by camoody1** [comment] 2024-01-04 00:50
@photopea Occasionally, the Loading or Saving messages get stuck in Photopea. I can't reproduce it on demand, or I would have recorded a video and sent it to you. But it does happen. I really wish you could add some sort of timeout to those messages that return and error after so long. When it gets stuck during a save (usually a large file to cloud storage), I know that I need to save the project locally or else I risk losing my work.

This problem is EXTRA bad on mobile, because the stuck messages make it very difficult - if not impossible - to access the File menu which prevents you from even having the option to save the project locally.

**Comment by photopea** [comment] 2024-01-04 09:51
It would really help if you could reproduce it somehow.
