### ISSUE TITLE
pleeeeeeese fix this bug

### ISSUE THREAD

**Issue by mustafaGFX** [photopea/photopea#2777] opened 2021-01-19 14:48 UTC
I have been working for 2 hours on a project, and photopea Suddenly stopped !!

guess why?
because I used the text tool, all I did was adding a text, and the whole program completely collapsed

this bug was Too violent to me, I even couldn't save the project before I restart photopea, it was completely Unresponsive and the whole interface was Collapsed

**Comment by photopea** [comment] 2021-01-19 15:00
Hi, a browser can shut down any website, if it uses too much RAM.

how much RAM do you have? How large is your document? If you open a 30 MPx photo and start duplicating layers, it will run out of memory at some point. There is nothing we can do about it :(

Unless it was a bug in Photopea, which we can reproduce.

**Comment by photopea** [comment] 2021-01-20 23:18
I have to close it because of lack of details.

**Closed by photopea** 2021-01-20 23:18 UTC
