### ISSUE TITLE
Raw development demosaicing artifacts?

### ISSUE THREAD

**Issue by jc-zeitraum** [photopea/photopea#3980] opened 2021-11-13 10:02 UTC
Hi!

I was using photopea to develop some raw images for testing. The image is from a Google Pixel 5 DNG.
I came across these artifacts, that might happen during demosaicing, but I'm not sure and I couldn't find anything on it here or in the subreddit. *The noise in the images is from heavyprocessing outside photopea.

It seems like segments of the image are misaligned.
Here are two images to compare the photopea development and the demosaicing from the adobe dng SDK "dng_validate.exe"

Here's photopea* at 600% magnification:
![photopea](https://user-images.githubusercontent.com/61283134/141614513-d7f2bacf-85d3-4f74-a3de-7884b7c89a39.jpg)

and here the dng_validate at 600% magnification:
![dng-sdk](https://user-images.githubusercontent.com/61283134/141614527-a6617971-1996-4fa9-a02f-8fee2aa011db.jpg)

Just thought I'd let you know.
Julian

_*The noise in the images is from heavy processing outside photopea._

**Comment by photopea** [comment] 2021-11-13 11:37
Every progarm has its own RAW processing. I dont know what is inside the Adobe SDK. Do you think the result of Photopea looks worse? They both look "equally bad" to me, there is not much you can do with a noisy image.

The result of Adobe looks more blurry, it could even be the same image, but the second version is enlarged with a bilinear interpolation.

**Comment by jc-zeitraum** [comment] 2021-11-13 12:17
Oh, I should have highlighted the parts of the image I was talking about, sorry. It's probably difficult to tell.
I'm talking about the misalignment, that looks like a crack going through the image, not about any color or acuuity differences.

I attached a gif, that should make it more clear. It switches between the two in a 1 sek interval.

![photopea](https://user-images.githubusercontent.com/61283134/141643391-42070756-52d5-45f1-846f-9e7cf2dbbb8e.gif)

**Comment by photopea** [comment] 2021-11-13 13:49
Oh, I see, could you share your DNG file with us?

**Comment by jc-zeitraum** [comment] 2021-11-13 14:45
Sure, here it is:

https://drive.google.com/file/d/1z2ag7qdBfBog01guIF1b4ZvAz-A20iMV/view?usp=sharing

I hope that helps!
And thanks for providing this software for free. Seems like a huge endeavor and a lot of work.

**Comment by photopea** [comment] 2021-11-18 15:55
It should be fixed now :)

The problem is not in demosaicing, but in the OpCode - WarpRectilinear . Your lens is probably not perfect, so the DNG file specifies, that the raw image should be processed by a specific geometric transformation (you can see the "before" and "after" below).  We switched to the bilinear interpolation, which requires additional 0.2 seconds, but the result is smooth now.

![image](https://user-images.githubusercontent.com/15955558/142449917-13480c60-cb3a-4c98-9bd7-edbc7682eb0b.gif)

**Closed by photopea** 2021-11-18 15:55 UTC
