### ISSUE TITLE
"Splitting Open Paths" Occurs On Every Save Attempt

### ISSUE THREAD

**Issue by kevinmotoa** [photopea/photopea#4351] opened 2022-02-21 11:44 UTC
Engineering drawing loaded from PDF, largely made up of paths. Edits fine, exports fine, but when I save to PSD a history step "splitting open paths" is created and, well, it splits a bunch of paths, rendering parts of the drawing invisible and making it functionally impossible to save the work.

I tested if it was a weird keyboard error by repeating the process using the menu only, same result. Tried recreating the drawing from the original PDF and editing, same result. 

I tried restarting Photopea and even checked if my CD tray was in the eject position, couldn't figure out why it's happening or how to create an alternative condition, so I'm stumped. Same process, same file - and previously the same - up until now was working fine. 

So after seeing if any other open reports mentioned splitting I'm submitting this bug report. 

If it turns out I'm doing something stupid, let me know - it may not be a bug with Photopea, but with the user!

**Comment by avagp** [comment] 2022-02-21 13:59
This is a intended behaviour.

Because it is the way Photoshop works.

You cannot have "open shapes" saved.  Like a "C" or "|" shape, rather than a "O" shape.

You can though, have merged closed shapes. So for example, you cannot merge an open shape like "|" with a closed one like "O".

So, in order to bypass it, i usually use thin squares as straight lines, or have a only one line that goes over itself on some parts creating the shape i want.

For example, this shape is a open shape (a line) that goes over itself:
![image](https://user-images.githubusercontent.com/11801254/154969139-391fd416-d592-4586-b952-35b50b842af4.png)
![image](https://user-images.githubusercontent.com/11801254/154969144-21e072ea-3725-4925-bfce-3178d88cfe7a.png)


Or this have "lines" that are thin squares, so i can successfully merge them:
![image](https://user-images.githubusercontent.com/11801254/154969281-6b475ccc-de3b-49aa-ae11-71606af344a6.png)
![image](https://user-images.githubusercontent.com/11801254/154969358-5a8c92e5-9925-4738-82b8-8b2debd80ea6.png)

**Comment by avagp** [comment] 2022-02-21 14:02
Hope it helps :)

**Comment by kevinmotoa** [comment] 2022-02-21 14:51
Hey avagp, thanks for that. If it's anticipated then fair enough!

What strikes me as odd is that the paths import fine, display fine and then the forced split on exit destroys the then-to-fore untouched shape, which I think would violate the "first do no harm" rule; However, if the internal logic of the PS engine is such that it can read the paths in without altering them, but cannot read them out without altering them that's not the strangest decision Adobe will have made in my lifetime.

I wish I could attach it, but it's part of a project under NDA, so I'll just suffer in silence.  As I mentioned, it's an engineering drawing so the vector part if itself a PDF export from SolidWorks or Autocad or something, full of many individual paths and vectors, then imported into Photopea to do some touchup visual work. It would be handy if the shape just read back out to file the same way it read in so I don't have to manually hunt down which of many paths don't connect up properly, then fix them by hand.

Thanks again!

**Comment by photopea** [comment] 2022-02-21 15:19
As mentioned above, Adobe Photoshop can not have two open paths in one layer. If you try to crate two open paths, it will close these two paths.. To make sure that a PSD file from Photopea looks the same in Adobe Photoshop, we must separate each open path into a separate layer.

But it should not change the look of a document. Please, create a case (a PSD), where separating paths by Photopea changes the look.

**Closed by photopea** 2022-02-21 15:19 UTC

**Comment by avagp** [comment] 2022-02-21 16:43
@kevinmotoa if you feel like, you can recreate that particular shape in a blank canvass, therefore not violating you NDA.

Only if you feel like it :)
