### ISSUE TITLE
saving as jpg file issue

### ISSUE THREAD

**Issue by bionavic** [photopea/photopea#2680] opened 2020-12-09 00:03 UTC
I was saving my project as a jpg file so I could use it as a thumbnail, When it sent me the coding of my project instead.

I was forced too exit without saving my work. I had too make it all over again.

**Comment by photopea** [comment] 2020-12-09 00:07
Hi, what do you mean by the "coding of your project"? What should I do to make the problem happen on my computer?

**Comment by bionavic** [comment] 2020-12-09 02:11
I guess I shouldn't say coding all though that's what it looked like. I'm not sure how it occurred but I was working on a thumbnail project for YouTube, So when I was finished I clicked File then Export AS then JPG. It sent me this JPG Notepad that had some kind of coding language or something, But no actual thumbnail ever appeared.

**Comment by photopea** [comment] 2020-12-09 10:47
Hi, can you make it happen again? We can solve only probelms which you can make happen several times (reproduce).

**Comment by MichalSZZ** [comment] 2020-12-09 11:40
Maybe he downloaded a txt file (browser addon problem)? And doesn't see file extension. And it's opening in notepad?

**Comment by bionavic** [comment] 2020-12-09 18:06
I'll try too make it happen again but it might take a bit because I don't know why or how it happened too begin with.

**Comment by photopea** [comment] 2020-12-27 23:23
I have to close it because of lack of details.

**Closed by photopea** 2020-12-27 23:23 UTC
