### ISSUE TITLE
Can't open my psd in photopea with google chrome

### ISSUE THREAD

**Issue by kahyan0729** [photopea/photopea#1833] opened 2019-12-05 09:48 UTC
I tried to open psd in my computer but cannot, while my friend can open it in her laptop (with google chrome). But im able to open the psd in my laptop with microsoft edge. Please help.

**Comment by photopea** [comment] 2019-12-05 10:32
Hi, some browser extensions can break the behaviour of websites.

Try to run Photopea in Incognito mode (with no extensions). Let me know if it works.

**Comment by kahyan0729** [comment] 2019-12-06 01:28
Hey Team,

I tried to run it in incognito mode, but it still pop up the same message
which said that the file structure is not supported.
I tried to open another psd, then the psd file can be opened, it can't be
opened without opening other psd files. May I know what's the reason for
this?

Thanks.

Regards,
Kah Yan

**Comment by photopea** [comment] 2019-12-06 09:26
How large is your PSD file? I guess the problem is in RAM memory. Sometimes, browsers allow us to use as much as we want, but sometimes, browsers simply crash Photopea,

**Comment by kahyan0729** [comment] 2019-12-09 04:01
Okay, I think can be, but I tried to create and shift layers that I need
into a new project, but it still crash sometimes.
Any suggestions? Would it be better if I install photopea?

**Comment by photopea** [comment] 2019-12-09 09:44
How large is your PSD file, in megabytes? How much RAM do you have?

**Comment by photopea** [comment] 2019-12-12 11:04
I have to close it because of lack of details.

**Closed by photopea** 2019-12-12 11:04 UTC
