### ISSUE TITLE
Copy and Pasting

### ISSUE THREAD

**Issue by MSK19J** [photopea/photopea#3496] opened 2021-07-04 16:39 UTC
Whenever I try to paste something(CTRL-V) on to Photopea, it doesn't show up for some reason.

**Comment by photopea** [comment] 2021-07-05 09:40
How can I reproduce the problem? What browser should I use? What image in what program or website should I copy, to try to paste it into Photopea?

**Comment by apollodwg** [comment] 2021-07-05 15:25
i have the same problem but with text. i copy text from word or browser and it wont paste in any way

**Comment by photopea** [comment] 2021-07-05 17:47
@apollodwg Are you pasting it into a text layer, which is entered with a Type tool?

**Comment by apollodwg** [comment] 2021-07-05 17:51
Yes thats what im doing

**Comment by apollodwg** [comment] 2021-07-05 17:53
even pasting it without a text layer doesnt work

**Comment by photopea** [comment] 2021-07-05 17:53
Maybe your browser extesnions are interfering with it. Can you try to paste it in Photopea in Incognito mode?

**Comment by apollodwg** [comment] 2021-07-05 17:56
incognito doesnt work either

**Comment by apollodwg** [comment] 2021-07-05 17:56
does it work for you

**Comment by photopea** [comment] 2021-07-05 18:22
Yes, it works for me. Could you record a video of what you are doing?

**Comment by peko46** [comment] 2021-07-06 08:49
Hi. I've got a similar problem. Can't paste anything (tried to paste a screenshot into blank for example) but just at Firefox. At chrome seems fine. Checked it on two different laptops, Cookies removed etc.

**Comment by photopea** [comment] 2021-07-06 09:19
There was a bug in Firefox since yesterday. It should be fixed now.

**Closed by photopea** 2021-07-06 09:19 UTC
