### ISSUE TITLE
Issues opening a file

### ISSUE THREAD

**Issue by morgansow** [photopea/photopea#2498] opened 2020-10-02 20:54 UTC
Photopea randomly restarted while I was editing my project and it after it refreshed my project was gone. I had saved my progress prior to this so if anything happened I would be able to reopen my project, but whenever I click to open the file on photopea, it either doesn't open or it opens but I am unable to see my different frames or click on anything. The file that saved was also quite strange. Instead of the project saving to my computer in a normal PDF or JEPG format, it saved as a folder with about 20 different strange downloads in it. I've uploaded a picture of the files that were downloaded when I saved my project and of what the screen looks like when I am able to go onto the file.

![image](https://user-images.githubusercontent.com/72280750/94968994-87e70780-04c7-11eb-8bf7-2ec81a01181a.png)
![image](https://user-images.githubusercontent.com/72280750/94969007-92a19c80-04c7-11eb-9fc0-f0f4bdc518f2.png)

**Comment by photopea** [comment] 2020-10-03 06:04
In order for website to detect keyboard shortcuts, you should click into the website. If you click outside the website (e.g. into the browser user interface), the website can  not detect shortcuts. You probably clicked outside Photopea, and pressed Ctrl+S, which your browser understood as saving a webpage, so you saved a webpage into your computer. Similarly, if you click into e.g. Microsoft Word, Ctrl+S will not save the image in Photopea, but it will save a Word document.

If it sounds too complicated, try to save files by pressing File - Save as PSD in Photopea, instead of shortcuts.

Photopea should never randomly restart. What web browser do you use? Your browser should not allow you to close or refresh Photopea, if there is any unsaved work.

**Comment by morgansow** [comment] 2020-10-03 20:03
I didn't use a shortcut, I clicked file and then save as a PSD, and I am using chrome as my browser. Is there any way I can recover my project?

**Comment by photopea** [comment] 2020-10-03 20:19
Hi, if you closed Photopea without saving your work, your work does not exist anywhere :(

Can you try to save a PSD again? Does it work? We really need some steps how to reproduce the problem, to be able to fix it.

**Comment by photopea** [comment] 2020-10-05 12:49
I have to close it because of lack of details. I was not able to reproduce the issue.

**Closed by photopea** 2020-10-05 12:49 UTC
