### ISSUE TITLE
Unknown File Format .PSD

### ISSUE THREAD

**Issue by Aoi-Marie27** [photopea/photopea#3813] opened 2021-10-06 10:02 UTC
I created and saved a PSD, but when I open it again, it says file format "u/00000....."
I've tried to send it to your support mail but it was error and says, 0 bytes.

Please help!

**Comment by photopea** [comment] 2021-10-15 21:10
I have to close it because of lack of details :(

**Closed by photopea** 2021-10-15 21:10 UTC

**Comment by REClark920** [comment] 2022-03-02 06:25
I created and saved a PSD, but when I open it again, it says file format "u/00000....."
I've tried to send it to your support mail but it was error and says, 0 bytes.

Please help I worked hard on this project and it's due this week. I can't open it. I working with Edge.

**Comment by photopea** [comment] 2022-03-02 07:39
Your file is damaged and your work is lost. It could be caused by an old browser, or some of your browser extensions. Or maybe it is an error of your operating system, which erased your file.

If you can make Photopea produce a 0-Byte file, let us know how to do it and we will look into it.
