### ISSUE TITLE
After using free transform and merging down, the site crashes and the transform box persists

### ISSUE THREAD

**Issue by jamesgott** [photopea/photopea#1145] opened 2018-12-14 17:19 UTC
To replicate, have two images. 
1. apply one image onto the other
2. Transform the top layer
3. Merge down
4. notice the transform box persists
5. try to use any other tool
6. notice nothing works on the site

https://imgur.com/a/PqjQ4vF

**Comment by photopea** [comment] 2018-12-15 14:11
Hi, I tried to do the same, but when I Merge down, the Transform Box disappears.

Could you be more precise on what should I do? Did you confirm the transformation with a Check mark in the top menu? Do you have "Transform Controls" in the Move tool enabled?

**Comment by photopea** [comment] 2019-01-11 16:21
I have to close it because I could reproduce it :(

**Closed by photopea** 2019-01-11 16:21 UTC
