### ISSUE TITLE
Unable to resize images when i drag them into the canvas

### ISSUE THREAD

**Issue by girlyteengirled** [photopea/photopea#7440] opened 2024-12-25 00:35 UTC
Your Operating System: MacOS
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Drag an image file / Import image from downloads
3. Theres no button that allows me to change the size of the image
4. Other than being unable to change the size, everything else works as it should? This hasn’t happened before and yesterday it was working fine

**Comment by photopea** [comment] 2024-12-25 00:59
At step 3, there is not supposed to be a button to change the size of the image after opening a document.

You can change the image size by pressign Image - Image - Size.

**Comment by girlyteengirled** [comment] 2024-12-25 01:41
The same thing happening in this video happens when I drag an image in, I press the image but nothing for resizing 

https://github.com/user-attachments/assets/fdedfa40-af06-47f8-9bb0-0a7af4e27bb8

**Comment by photopea** [comment] 2024-12-25 08:51
This is usually caused by your browser extensions. If you dont know what your browser extensions are doing, try to turn them all off.

Also, do not cut away parts of Photopea, show us the whole Photopea in your video. There should be ads on the right side, "www.photopea.com" at the top, etc.

**Comment by photopea** [comment] 2024-12-29 15:55
I have to close it, because the person is not responding.

**Closed by photopea** 2024-12-29 15:55 UTC
