### ISSUE TITLE
straight up broke and autosave failed

### ISSUE THREAD

**Issue by mrprairiedog** [photopea/photopea#7383] opened 2024-12-03 22:38 UTC
Your Operating System: Windows 11
Your Web Browser: Chrome
The problem happens in the Incognito Mode, too: True

**This must be done to see the problem**
1. Go to www.photopea.com
2. Make something
3. Breaks
4. Unsure how, it just freezes, deletes, and does not autosave
5. Reload, everything is gone
6. (It happens at random)

I had a whole character made, and I was getting ready to save it as a PSD when website broke my image and froze. I reloaded, thinking that it was going to load the autosave backup, but noooooo. I spent 2 days on that!

**Comment by photopea** [comment] 2024-12-04 00:34
What exactly should I do to see it break? You could be using browser extensions, which block cookies, so they break our backups (they prevent a website from storing anything on your computer).

If you think it is not caused by your extensions, plese, describe specific steps how to make Photopea break / freeze.

**Comment by mrprairiedog** [comment] 2024-12-04 01:18
There's one extension, but it's inactive, so it's not editing anything. All I know is that I made a lot of edits, and when I tried to use the spot healing brush tool at some point, it broke and deleted half a layer, and when I tried to undo it, it froze. I waited for a long time and it finally gave me the "aw snap" webpage error. When I reloaded, everything was gone.

**Comment by mrprairiedog** [comment] 2024-12-04 18:42
This computer has so much RAM that I really doubt it.

**Comment by photopea** [comment] 2024-12-04 19:35
How much?

**Comment by photopea** [comment] 2024-12-29 17:16
I have to close it because nobody is responding :(

**Closed by photopea** 2024-12-29 17:16 UTC
