### ISSUE TITLE
Layer comps window overflow

### ISSUE THREAD

**Issue by hallworth** [photopea/photopea#867] opened 2018-09-07 09:34 UTC
![selection_014](https://user-images.githubusercontent.com/10153155/45210978-03ded900-b289-11e8-873f-c34f43adb59f.png)

When I have more than 5 layer comps, the LC comps window does not expand to show the additional layer comps. 
The hidden layer functions are still shown and overflow the window.

I cannot manually resize the window to show the hidden layers.

I can access the other layers by scrolling the window.

The hidden layer comp functions still work.

**Comment by photopea** [comment] 2018-09-07 12:17
Hi, what browser is that? Can you try to update it?

**Comment by photopea** [comment] 2018-09-10 08:51
I have to close it because of lack of details :(

**Comment by hallworth** [comment] 2018-09-10 09:44
Version 69.0.3497.81 (Official Build) (64-bit) 
Ubuntu 17.10

**Comment by photopea** [comment] 2018-09-10 09:47
Is your browser Google Chrome, I guess?

I tried to do the same in Chrome on Windows, but did not have such problem. Are you using a standard Chrome, or Nightly / Canary build? Can you try to update the GPU drivers?

**Comment by hallworth** [comment] 2018-09-10 12:55
Ubuntu 17.10 
Drivers are up to date - using radeon driver on AMD Radeon Firepro 4800
Chrome - Version 69.0.3497.81 (Official Build) (64-bit)

Also using Chromium Version 67.0.3396.99 (Official Build) Built on Ubuntu , running on Ubuntu 17.10 (64-bit) - same thing happens.

**Comment by photopea** [comment] 2018-09-10 13:06
I really don't know what the problem is :(  I really think it is a bug in your environment (browser / OS / drivers).

Could you change the CSS of that element (in Developer Tools) and see if anything helps?

**Comment by hallworth** [comment] 2018-09-10 13:18
Removing the height here fixes it - is there a way I can make this persistent?
<div class="scrollable" style="/* height: 160px; */">

**Comment by photopea** [comment] 2018-09-10 14:39
I am very sorry, I just noticed, that it happens for me too both in Chrome and in Firefox. I will fix it properly as soon as possible.

**Comment by photopea** [comment] 2018-09-10 22:18
Hi, it should be fixed now. Thank you very much for your time and your patience! :)

**Closed by photopea** 2018-09-10 22:18 UTC

**Comment by hallworth** [comment] 2018-09-12 12:02
Yay yes you have! Many thanks. 
![selection_031](https://user-images.githubusercontent.com/10153155/45423670-f2803d00-b68b-11e8-8f6b-f10095a3c162.png)
