### ISSUE TITLE
[Bug] Long pressing always open layer context menu

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#6561] opened 2024-03-19 17:40 UTC
OS: Android 13
Browser: Chrome
Bug in Incognito mode too

When both the width and height of screen are greater than or equal to 599px, long pressing always open layer context menu, even "long-tap as a right click" is uncheck.
This bug occurs on my 2 Android devices. 

To reproduce:

1. Set smallest width to 599 or greater in developer options of Android device
2. Long press layer in photopea
3. The context menu is still opened even "long-tap as a right click" is uncheck
4. Change the smallest width to 598 or less
5. Refresh browser
6. Long press layer in photopea again
7. The context menu is not opened

**Comment by photopea** [comment] 2024-03-19 18:06
The context menu should appear only if long tapping the thumbnail of the layer.

Otherwise, Photopea listens to "contextmenu" event, which is usually a right-click on desktops, but maybe it is a long-tap on your device. 

Anyway, I dont have a device with Android 13 to try it out, I only have Android 14 :(

**Comment by photopea** [comment] 2024-03-19 20:15
In your step 2: "Long press layer in photopea" , are you talking about the layer in the layers panel, or the layer itself (on the canvas)?

**Comment by photopea** [comment] 2024-03-19 20:57
in Chrome on Android 14, long-tap starts "drag-and-dropping" the layer, no matter where you tap. 

If you enable "Long-tap as a right click", and long-tap the thumbnail, it opens a context menu.

**Comment by photopea** [comment] 2024-03-19 21:41
Yes, it always works like this. Does it really depend on the width in your case?

**Comment by photopea** [comment] 2024-03-19 22:32
Did you try to simply turn your screen? The width should become bigger.

**Comment by photopea** [comment] 2024-05-29 21:06
I have to close it, because I can not reproduce it :(

**Closed by photopea** 2024-05-29 21:06 UTC
