### ISSUE TITLE
Not able to move or edit layers

### ISSUE THREAD

**Issue by TopApexClips** [photopea/photopea#1477] opened 2019-06-28 06:14 UTC
Hello, photo pea went from working great for me to not in a spit second and hasn't gone back to normal. I can see layers in my project both on screen and side bar, but I can't move them around (FreeTransform) or use any tools on them like the magnetic crop.. please someone help as I need to use it urgently

**Comment by TopApexClips** [comment] 2019-06-28 06:31
Would appear previous psd projects open and work fine.. seems to be if want to start a new project, any image I load in to photo pea appears exactly as it should but seems completely non responsive when attempting to transform or crop or select to move the image, tried the obvious fixes like refreshing the page and restarting the machine etc please help

**Comment by photopea** [comment] 2019-06-28 06:36
Hi, I was not able to reproduce such behavior :(

Can you try basic things: reload www.Photopea.com multiple times. Update your browser. Try Photopea in Incognito mode (i.e. without browser extensions).

If nothing helps, could you tell us exactly what you did to make this problem happen? Or even record a short video?

**Comment by TopApexClips** [comment] 2019-06-28 07:27
I did nothing to make this issue it happen, it happend when I went to put an image to a new project, something I've done hundreds of times before, and now its stopped working, tried all the obvious things

________________________________

**Comment by TopApexClips** [comment] 2019-06-28 07:29
sorry, how do I run it without browser extensions or in incognito?

________________________________

**Comment by photopea** [comment] 2019-06-28 07:31
What browser do you use? Search the internet to find out how to start an incognito window in your browser.

**Comment by TopApexClips** [comment] 2019-06-28 07:31
Ive restarted photopea around 15 times in the last 6 - 8 hours problem still persists 🙁 I use it for my work as well looks like im going to have to spend some money

________________________________

**Comment by photopea** [comment] 2019-06-28 07:50
Photopea should work the same way for all users. And it works well for me (at least from what I have tried).

Please, record a short video of what exactly you do, start from opening www.Photopea.com

**Comment by TopApexClips** [comment] 2019-06-28 07:51
thank you that has sorted the issue!

________________________________

**Comment by photopea** [comment] 2019-06-28 07:55
What sorted the issue? What was the problem?

**Comment by photopea** [comment] 2019-06-28 19:24
Ok i will close it.

**Closed by photopea** 2019-06-28 19:24 UTC
