### ISSUE TITLE
Issue: Can't adjust specific channel of smart object

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3202] opened 2021-05-02 17:03 UTC
When adjust or apply filter, what will be affected is RGB channel instead of the channel which is selected.

**Comment by photopea** [comment] 2021-05-04 11:43
I just tried it, and only the active channel is modified.

Could you describe steps how to reproduce it?

**Comment by nothingshiru** [comment] 2021-05-04 12:04
I have just found out that it's smart object that has problem.

**Comment by photopea** [comment] 2021-05-04 12:09
adjustments and filters on smart objects are saved as smart adjustments and smart filters.

How exactly do you want e.g. a Smart Gaussian Blur work on a smart object, if only the red channel is selected? Do you want to blur only the red channel? And what if you enable all channels, should the smart object be redrawn?

**Comment by photopea** [comment] 2021-05-04 12:10
I will close it, because a Smart Object in PSD file can not have a smart filter applied just to one channel.

**Closed by photopea** 2021-05-04 12:10 UTC

**Comment by nothingshiru** [comment] 2021-05-04 12:25
I duplicated one of channels, selected and adjusted it. The adjustment was applied to RGB channel instead of the new channel that I selected. 

https://user-images.githubusercontent.com/79258245/117002966-d89d3800-ad16-11eb-9964-dbe9f8fa2089.mp4

**Comment by photopea** [comment] 2021-05-04 12:46
I have fixed it :) thanks!
