### ISSUE TITLE
Can't open this file

### ISSUE THREAD

**Issue by pippaholland82** [photopea/photopea#4924] opened 2022-08-18 09:23 UTC
I cannot open an XD file in photopea anymore? Comes up with the attached message - any idea why this is please?
![Screenshot 2022-08-18 at 09 29 27](https://user-images.githubusercontent.com/111498035/185360259-a8b943f5-c9e0-456f-a384-52c85ea00d6c.png)

**Comment by photopea** [comment] 2022-08-18 17:33
That is really strange. Are you opening it with File - Open? I think someone reported it before, but I can not reproduce such thing on my computer.

**Comment by photopea** [comment] 2022-08-18 17:33
Maybe get in touch with this user: https://github.com/photopea/photopea/issues/4398

Or try the regular steps: https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by photopea** [comment] 2022-08-21 13:02
I have to close it because of lack of details.

**Closed by photopea** 2022-08-21 13:02 UTC
