### ISSUE TITLE
Unable to drag a layer to change order in layer list

### ISSUE THREAD

**Issue by gybeasmz** [photopea/photopea#752] opened 2018-06-08 11:29 UTC
5 minutes into the project, I´m unable to change order of layers by draging them up or down inside the layer list.

**Comment by photopea** [comment] 2018-06-08 11:34
Hi. We really need more details about how to reproduce the bug.

**Comment by photopea** [comment] 2018-06-16 08:28
I have to close it because of lack of details.

**Closed by photopea** 2018-06-16 08:28 UTC
